"""AUTO-GENERATED — DO NOT EDIT.

Run `python3 /app/scripts/build_frontend_surface.py` to regenerate.

Captured by a grep of /app/frontend/src/**/*.{js,jsx,ts,tsx} for
`/api/…` literals. Consumed by routers/endpoint_audit_router.py to
compute the 'surface' dignity signal in production containers
that do not ship frontend source files.
"""
from __future__ import annotations

BUILT_AT: str = '2026-06-13T01:18:08.993288+00:00'
SRC_ROOT: str = '/app/frontend/src'
ENDPOINT_COUNT: int = 1100

SURFACE_MANIFEST: dict[str, list[str]] = {'/api/accounting/': ['services/_archive/api.legacy.js'],
 '/api/accounting/summary': ['services/_archive/api.legacy.js'],
 '/api/accounting/transactions': ['services/_archive/api.legacy.js'],
 '/api/acquisition/campaigns': ['platform/AcquisitionEngine.jsx'],
 '/api/acquisition/campaigns/': ['platform/AcquisitionEngine.jsx'],
 '/api/acquisition/config': ['platform/AcquisitionEngine.jsx'],
 '/api/acquisition/form/': ['platform/AcquisitionEngine.jsx'],
 '/api/acquisition/funnel-stats': ['platform/AcquisitionEngine.jsx'],
 '/api/acquisition/generate-voice-script': ['platform/AcquisitionEngine.jsx'],
 '/api/acquisition/leads': ['platform/AcquisitionEngine.jsx'],
 '/api/acquisition/voice-chat': ['platform/AcquisitionEngine.jsx'],
 '/api/admin/a2a/widget-signal': ['lib/emitWidgetSignal.js'],
 '/api/admin/activity-feed': ['platform/SystemOverview.jsx'],
 '/api/admin/agent/activity': ['platform/AgentObservatory.jsx'],
 '/api/admin/agent/seed-traces': ['platform/AgentObservatory.jsx'],
 '/api/admin/agent/status': ['components/SystemStatusBar.jsx', 'platform/AgentObservatory.jsx'],
 '/api/admin/agent/traces': ['platform/AgentObservatory.jsx'],
 '/api/admin/analytics/insights': ['platform/AnalyticsDashboard.jsx'],
 '/api/admin/anomaly/run-now': ['platform/AdminControlCenter.jsx'],
 '/api/admin/anomaly/status': ['platform/AdminControlCenter.jsx'],
 '/api/admin/antigravity-skills/broadcast': ['platform/AdminAntigravitySkills.jsx', 'platform/SystemOverview.jsx'],
 '/api/admin/antigravity-skills/broadcast/active': ['platform/AdminAntigravitySkills.jsx'],
 '/api/admin/antigravity-skills/broadcast/clear': ['platform/AdminAntigravitySkills.jsx'],
 '/api/admin/antigravity-skills/library': ['platform/AdminAntigravitySkills.jsx'],
 '/api/admin/antigravity-skills/library/': ['platform/AdminAntigravitySkills.jsx'],
 '/api/admin/antigravity-skills/library/categories': ['platform/AdminAntigravitySkills.jsx'],
 '/api/admin/antigravity-skills/library/meta': ['platform/AdminAntigravitySkills.jsx', 'platform/SystemOverview.jsx'],
 '/api/admin/antigravity-skills/sync': ['platform/AdminAntigravitySkills.jsx'],
 '/api/admin/apollo-cost/': ['platform/AdminApolloCostPage.jsx'],
 '/api/admin/apollo-cost/forecast': ['platform/AdminApolloCostPage.jsx'],
 '/api/admin/apollo-cost/summary': ['platform/AdminApolloCostPage.jsx'],
 '/api/admin/audit-log': ['platform/admin/AdminBrainPage.jsx'],
 '/api/admin/autonomous-repair': ['lib/sentinel.js'],
 '/api/admin/autonomous-repair/': ['platform/ApprovalInboxPanel.jsx', 'platform/AutonomousRepairPanel.jsx'],
 '/api/admin/autonomous-repair/approve/': ['platform/ApprovalInboxPanel.jsx'],
 '/api/admin/autonomous-repair/events': ['platform/AutonomousRepairPanel.jsx'],
 '/api/admin/autonomous-repair/list': ['platform/ApprovalInboxPanel.jsx'],
 '/api/admin/autonomous-repair/pending-fixes': ['platform/PendingCodeFixesPanel.jsx'],
 '/api/admin/autonomous-repair/pending-fixes/': ['platform/PendingCodeFixesPanel.jsx'],
 '/api/admin/autonomous-repair/pending-fixes/stats': ['platform/PendingCodeFixesPanel.jsx'],
 '/api/admin/autonomous-repair/reject/': ['platform/ApprovalInboxPanel.jsx'],
 '/api/admin/autonomous-repair/status': ['platform/AutonomousRepairPanel.jsx'],
 '/api/admin/autonomous-repair/trigger': ['platform/AutonomousRepairPanel.jsx'],
 '/api/admin/autonomous/notifications': ['platform/admin/AdminBrainPage.jsx'],
 '/api/admin/autonomous/overview': ['platform/admin/AdminBrainPage.jsx'],
 '/api/admin/autonomous/pipeline-flow': ['platform/admin/AdminBrainPage.jsx'],
 '/api/admin/autonomous/recent-decisions': ['platform/admin/CouncilAuditPage.jsx'],
 '/api/admin/autopilot/': ['platform/AutopilotMasterButton.jsx'],
 '/api/admin/autopilot/activate': ['platform/AutopilotMasterButton.jsx'],
 '/api/admin/autopilot/fire-now': ['platform/AutopilotMasterButton.jsx'],
 '/api/admin/autopilot/live-log': ['lib/sentinel.js', 'platform/AutopilotMasterButton.jsx'],
 '/api/admin/autopilot/pause': ['platform/AutopilotMasterButton.jsx'],
 '/api/admin/autopilot/status': ['lib/sentinel.js', 'platform/AutopilotMasterButton.jsx'],
 '/api/admin/avatars': ['platform/admin/AvatarManager.jsx'],
 '/api/admin/avatars/': ['platform/admin/AvatarManager.jsx'],
 '/api/admin/branding/': ['platform/SettingsPage.jsx',
                          'platform/SystemOverview.jsx',
                          'platform/customer/CustomerSettings.jsx',
                          'platform/luxe/LuxePages.jsx'],
 '/api/admin/breakers/status': ['lib/sentinel.js', 'platform/AdminControlCenter.jsx'],
 '/api/admin/bug-reports': ['platform/AdminBugReportsPage.jsx', 'platform/BugCatchWidget.jsx'],
 '/api/admin/bug-reports/': ['platform/AdminBugReportsPage.jsx'],
 '/api/admin/bug-reports/stats': ['platform/AdminBugReportsPage.jsx'],
 '/api/admin/builder/build': ['platform/SystemOverview.jsx'],
 '/api/admin/builder/stats': ['lib/sentinel.js', 'platform/AdminControlCenter.jsx'],
 '/api/admin/builder/status/': ['platform/AdminBuilderDetail.jsx'],
 '/api/admin/business-id/generate-all': ['platform/AdminBusinessIds.jsx'],
 '/api/admin/business-id/qr/': ['platform/AdminBusinessIds.jsx'],
 '/api/admin/business-id/regenerate/': ['platform/AdminBusinessIds.jsx'],
 '/api/admin/business-id/resend/': ['platform/AdminBusinessIds.jsx', 'platform/AdminMissionControl.jsx'],
 '/api/admin/business-ids': ['platform/AdminBusinessIds.jsx', 'platform/AdminMissionControl.jsx'],
 '/api/admin/cache/stats': ['lib/sentinel.js', 'platform/AdminControlCenter.jsx'],
 '/api/admin/campaign/autofix-all': ['platform/CampaignHealthPage.jsx'],
 '/api/admin/campaign/autofix/': ['platform/CampaignHealthPage.jsx'],
 '/api/admin/campaign/health': ['platform/CampaignHealthPage.jsx'],
 '/api/admin/campaigns/funnel': ['platform/CampaignCommandDashboard.jsx'],
 '/api/admin/campaigns/funnel/': ['platform/CampaignCommandDashboard.jsx'],
 '/api/admin/case-study/email': ['platform/AdminCaseStudy.jsx'],
 '/api/admin/case-study/generate': ['platform/AdminCaseStudy.jsx'],
 '/api/admin/case-study/list': ['platform/AdminCaseStudy.jsx'],
 '/api/admin/case-study/preview': ['platform/AdminCaseStudy.jsx'],
 '/api/admin/case-study/system-audit': ['platform/AdminCaseStudy.jsx'],
 '/api/admin/case-study/system-audit/download/': ['platform/AdminCaseStudy.jsx'],
 '/api/admin/case-study/system-audit/email': ['platform/AdminCaseStudy.jsx'],
 '/api/admin/case-study/system-audit/list': ['platform/AdminCaseStudy.jsx'],
 '/api/admin/case-study/tenants': ['platform/AdminCaseStudy.jsx'],
 '/api/admin/catalog': ['platform/AdminCommandHub.jsx', 'platform/admin/PricingStudio.jsx'],
 '/api/admin/catalog/': ['platform/admin/PricingStudio.jsx'],
 '/api/admin/codebase-health/latest': ['platform/AdminCodebaseHealth.jsx'],
 '/api/admin/codebase-health/refresh': ['platform/AdminCodebaseHealth.jsx'],
 '/api/admin/codebase-health/trend': ['platform/AdminCodebaseHealth.jsx'],
 '/api/admin/collective-scan/brain-growth': ['platform/admin/AdminBrainPage.jsx'],
 '/api/admin/collective-scan/last': ['platform/admin/AdminBrainPage.jsx'],
 '/api/admin/collective-scan/run': ['platform/SystemOverview.jsx', 'platform/admin/AdminBrainPage.jsx'],
 '/api/admin/console/approve': ['platform/AdminConsole.jsx'],
 '/api/admin/console/chip/fire': ['platform/AdminConsole.jsx'],
 '/api/admin/console/chips': ['platform/AdminConsole.jsx'],
 '/api/admin/console/history': ['platform/AdminConsole.jsx'],
 '/api/admin/console/intelligence': ['platform/AdminConsole.jsx'],
 '/api/admin/console/intelligence/': ['platform/AdminConsole.jsx'],
 '/api/admin/console/message': ['platform/AdminConsole.jsx'],
 '/api/admin/console/propose': ['platform/AdminConsole.jsx'],
 '/api/admin/console/voice': ['platform/AdminConsole.jsx'],
 '/api/admin/customer-360/': ['platform/AdminCustomer360.jsx', 'platform/Customer360ActionPanel.jsx'],
 '/api/admin/customer-360/actions/impersonation-log': ['platform/AdminImpersonationLog.jsx'],
 '/api/admin/customer-health/bin-detail/': ['platform/admin/CustomerHealthPanel.jsx'],
 '/api/admin/customer-health/customer/': ['platform/admin/CustomerHealthPanel.jsx'],
 '/api/admin/customer-health/force-unlock/': ['platform/admin/CustomerHealthPanel.jsx'],
 '/api/admin/customer-health/reset-password/': ['platform/admin/CustomerHealthPanel.jsx'],
 '/api/admin/customer-health/update/': ['platform/admin/CustomerHealthPanel.jsx'],
 '/api/admin/customers': ['components/SystemStatusBar.jsx', 'platform/ClientManager.jsx'],
 '/api/admin/customers/': ['platform/CustomerDetail.jsx', 'platform/CustomerServicesPopup.jsx'],
 '/api/admin/daily-log': ['platform/AdminDailyLog.jsx'],
 '/api/admin/daily-log/run-eod': ['platform/AdminDailyLog.jsx'],
 '/api/admin/daily-log/test-push/': ['platform/AdminDailyLog.jsx'],
 '/api/admin/dark-scout/investigate': ['platform/DarkScoutDashboard.jsx'],
 '/api/admin/dark-scout/investigations': ['platform/DarkScoutDashboard.jsx'],
 '/api/admin/dark-scout/status': ['components/SystemStatusBar.jsx', 'platform/DarkScoutDashboard.jsx'],
 '/api/admin/db-indexes/status': ['lib/sentinel.js', 'platform/AdminControlCenter.jsx'],
 '/api/admin/deploy-drift': ['lib/sentinel.js', 'platform/DeployStatusPanel.jsx', 'platform/SystemStatusChip.jsx'],
 '/api/admin/deploy-drift/invalidate': ['platform/DeployStatusPanel.jsx'],
 '/api/admin/deploy-readiness': ['platform/admin/AdminBrainPage.jsx'],
 '/api/admin/deploy/trigger': ['platform/SystemOverview.jsx'],
 '/api/admin/design-extract': ['platform/admin/DesignExtractStudio.jsx'],
 '/api/admin/design-extract/export/': ['platform/admin/DesignExtractStudio.jsx'],
 '/api/admin/design-extract/history': ['platform/admin/DesignExtractStudio.jsx'],
 '/api/admin/design-extract/run': ['platform/admin/DesignExtractStudio.jsx'],
 '/api/admin/design-extract/summary': ['platform/admin/DesignExtractStudio.jsx'],
 '/api/admin/dev-stack/health': ['platform/AdminPillarsMap.jsx', 'platform/SystemOverview.jsx'],
 '/api/admin/developers': ['platform/AdminDeveloperSignups.jsx'],
 '/api/admin/developers/export': ['platform/AdminDeveloperSignups.jsx'],
 '/api/admin/developers/health': ['platform/admin/DeveloperPortalPulseTile.jsx'],
 '/api/admin/developers/timeseries': ['platform/admin/DeveloperPortalPulseTile.jsx'],
 '/api/admin/diagnostics/': ['platform/admin/CustomerHealthPanel.jsx'],
 '/api/admin/diagnostics/all': ['platform/admin/CustomerHealthPanel.jsx'],
 '/api/admin/diagnostics/customer/': ['platform/admin/CustomerHealthPanel.jsx'],
 '/api/admin/diagnostics/fix-action/': ['platform/admin/CustomerHealthPanel.jsx'],
 '/api/admin/diagnostics/fix/': ['platform/admin/CustomerHealthPanel.jsx'],
 '/api/admin/diagnostics/run-all': ['platform/admin/CustomerHealthPanel.jsx'],
 '/api/admin/diagnostics/run/': ['platform/admin/CustomerHealthPanel.jsx'],
 '/api/admin/diagnostics/summary': ['platform/AdminConsole.jsx',
                                    'platform/AdminShell.jsx',
                                    'platform/admin/CustomerHealthPanel.jsx'],
 '/api/admin/dogfood/pulse': ['platform/admin/AdminBrainPage.jsx'],
 '/api/admin/empire/inject-key': ['platform/FrameworkMap.jsx'],
 '/api/admin/empire/live-metrics': ['platform/FrameworkMap.jsx'],
 '/api/admin/empire/pulse': ['components/SystemStatusBar.jsx', 'platform/FrameworkMap.jsx'],
 '/api/admin/empire/recent-events': ['platform/FrameworkMap.jsx'],
 '/api/admin/events/': ['platform/AgentCommandCenter.jsx',
                        'platform/AuremDashboard.jsx',
                        'platform/CampaignDashboard.jsx',
                        'platform/FrameworkMap.jsx',
                        'platform/ORACommandConsole.jsx'],
 '/api/admin/evolver/genes': ['platform/AdminEvolver.jsx'],
 '/api/admin/evolver/genes/': ['platform/AdminEvolver.jsx'],
 '/api/admin/evolver/run-review': ['platform/AdminEvolver.jsx'],
 '/api/admin/evolver/status': ['lib/sentinel.js', 'platform/AdminControlCenter.jsx', 'platform/AdminEvolver.jsx'],
 '/api/admin/founder-saves/': ['platform/SystemOverview.jsx'],
 '/api/admin/founder-saves/summary': ['platform/admin/FounderSaves.jsx'],
 '/api/admin/founder-saves/timeline': ['platform/admin/FounderSaves.jsx'],
 '/api/admin/founder/customers/cleanup': ['platform/AdminCustomersOnePane.jsx'],
 '/api/admin/founder/customers/list': ['platform/AdminCustomersOnePane.jsx'],
 '/api/admin/founder/customers/reonboard-bin': ['platform/AdminCustomersOnePane.jsx'],
 '/api/admin/git-gate/proposals': ['platform/admin/GitCommitGate.jsx'],
 '/api/admin/git-gate/proposals/': ['platform/admin/GitCommitGate.jsx'],
 '/api/admin/git-gate/summary': ['platform/admin/GitCommitGate.jsx'],
 '/api/admin/integrations/health': ['platform/AdminIntegrations.jsx'],
 '/api/admin/leads/': ['platform/AdminLeadsMining.jsx'],
 '/api/admin/leads/mine-emails/bulk': ['platform/AdminLeadsMining.jsx'],
 '/api/admin/leads/mine-emails/bulk/': ['platform/AdminLeadsMining.jsx'],
 '/api/admin/legion/health': ['lib/sentinel.js', 'platform/AdminControlCenter.jsx'],
 '/api/admin/links-hub': ['platform/AdminLinksHub.jsx'],
 '/api/admin/memoir/history': ['platform/AdminMemoir.jsx', 'platform/SystemOverview.jsx'],
 '/api/admin/memoir/info': ['platform/AdminMemoir.jsx', 'platform/SystemOverview.jsx'],
 '/api/admin/memoir/recall': ['platform/SystemOverview.jsx'],
 '/api/admin/memoir/remember': ['platform/SystemOverview.jsx'],
 '/api/admin/memoir/search': ['platform/AdminMemoir.jsx', 'platform/SystemOverview.jsx'],
 '/api/admin/memoir/stats': ['platform/AdminMemoir.jsx', 'platform/SystemOverview.jsx'],
 '/api/admin/mission-control/': ['lib/sentinel.js'],
 '/api/admin/mission-control/api-keys': ['platform/AdminMissionControl.jsx'],
 '/api/admin/mission-control/clients': ['platform/AdminMissionControl.jsx'],
 '/api/admin/mission-control/clients/': ['platform/AdminMissionControl.jsx'],
 '/api/admin/mission-control/dashboard': ['platform/AdminMissionControl.jsx'],
 '/api/admin/mission-control/hot-replies': ['platform/AdminControlCenter.jsx'],
 '/api/admin/mission-control/overview': ['platform/AdminMissionControl.jsx'],
 '/api/admin/mission-control/pixel-health': ['platform/AdminMissionControl.jsx'],
 '/api/admin/mission-control/services': ['platform/AdminMissionControl.jsx'],
 '/api/admin/mission-control/services/add-key': ['platform/AdminMissionControl.jsx'],
 '/api/admin/mission-control/subscriptions': ['platform/AdminMissionControl.jsx'],
 '/api/admin/mission-control/tenants-summary': ['platform/AdminControlCenter.jsx'],
 '/api/admin/mtth/by-tier': ['platform/MTTHCard.jsx'],
 '/api/admin/mtth/history': ['platform/MTTHCard.jsx'],
 '/api/admin/mtth/summary': ['platform/MTTHCard.jsx'],
 '/api/admin/ora-25/next-actions': ['platform/OraPhase25Panel.jsx'],
 '/api/admin/ora-25/policy-log': ['platform/OraPhase25Panel.jsx'],
 '/api/admin/ora-25/retention': ['platform/OraPhase25Panel.jsx'],
 '/api/admin/ora-25/retention/': ['platform/OraPhase25Panel.jsx'],
 '/api/admin/ora-25/scan-now': ['platform/OraPhase25Panel.jsx'],
 '/api/admin/ora-25/upsell': ['platform/OraPhase25Panel.jsx'],
 '/api/admin/ora-25/upsell/': ['platform/OraPhase25Panel.jsx'],
 '/api/admin/ora-cto/by-tool': ['platform/admin/OraCtoCockpit.jsx'],
 '/api/admin/ora-cto/invocations': ['platform/admin/OraCtoCockpit.jsx'],
 '/api/admin/ora-cto/overrides': ['platform/admin/OraCtoCockpit.jsx'],
 '/api/admin/ora-cto/summary': ['platform/admin/OraCtoCockpit.jsx'],
 '/api/admin/ora-dev': ['platform/AdminBrowserAgent.jsx'],
 '/api/admin/ora-dev/': ['platform/AdminBrowserAgent.jsx', 'platform/OraDevConsole.jsx'],
 '/api/admin/ora-dev/cleanup-orphans': ['platform/OraDevConsole.jsx'],
 '/api/admin/ora-dev/list': ['lib/__tests__/safeFetchJson.test.js', 'platform/OraDevConsole.jsx'],
 '/api/admin/ora-dev/stats': ['platform/OraDevConsole.jsx'],
 '/api/admin/ora-health/run-now': ['platform/OraSelfHealWidget.jsx'],
 '/api/admin/ora-health/status': ['platform/OraSelfHealWidget.jsx'],
 '/api/admin/ora-optimize': ['platform/admin/OraOptimizer.jsx'],
 '/api/admin/ora-optimize/purge-stale': ['platform/admin/OraOptimizer.jsx'],
 '/api/admin/ora-optimize/scan': ['platform/admin/OraOptimizer.jsx'],
 '/api/admin/ora-settings/': ['platform/admin/OraSettings.jsx'],
 '/api/admin/ora-settings/export-audit-csv': ['platform/admin/OraSettings.jsx'],
 '/api/admin/ora-settings/github-test': ['platform/admin/OraSettings.jsx'],
 '/api/admin/ora/cost-summary': ['platform/admin/DailySpendCard.jsx'],
 '/api/admin/ora/decisions': ['platform/admin/RecentDecisionsPanel.jsx'],
 '/api/admin/ora/email-health': ['platform/admin/EmailHealthCard.jsx'],
 '/api/admin/ora/github-lock': ['platform/admin/OraChat.jsx'],
 '/api/admin/ora/github-relock': ['platform/admin/OraChat.jsx'],
 '/api/admin/ora/github-unlock': ['platform/admin/OraChat.jsx'],
 '/api/admin/ora/health': ['platform/admin/OraHealthTile.jsx'],
 '/api/admin/ora/lesson-journal': ['platform/admin/LessonSources.jsx'],
 '/api/admin/ora/lesson-snapshot': ['platform/admin/LessonSources.jsx'],
 '/api/admin/ora/lesson-sources': ['platform/admin/LessonSources.jsx'],
 '/api/admin/ora/morning-brief': ['platform/admin/MorningBriefCard.jsx', 'platform/admin/MorningBriefMobile.jsx'],
 '/api/admin/ora/nightly-self-tests': ['platform/admin/LessonSources.jsx'],
 '/api/admin/ora/providers/health': ['platform/SystemOverview.jsx', 'platform/admin/OraCtoCockpit.jsx'],
 '/api/admin/ora/skills': ['platform/admin/SkillsMarketplace.jsx'],
 '/api/admin/ora/skills/': ['platform/admin/SkillsMarketplace.jsx'],
 '/api/admin/ora/specialist-cost-breakdown': ['platform/admin/SpecialistCostBreakdownTile.jsx',
                                              'platform/enterprise/EnterpriseAdminOverview.jsx'],
 '/api/admin/ora/validated-solutions': ['platform/admin/ValidatedSolutionsPanel.jsx'],
 '/api/admin/ora/validated-solutions/': ['platform/admin/ValidatedSolutionsPanel.jsx'],
 '/api/admin/ora/vanguard-status': ['platform/admin/OraHealthTile.jsx'],
 '/api/admin/ora/voice-profile/': ['platform/admin/VoiceProfileEditor.jsx'],
 '/api/admin/outreach/closer-day5/run': ['platform/admin/OutreachHealthCard.jsx'],
 '/api/admin/outreach/health': ['platform/admin/OutreachHealthCard.jsx'],
 '/api/admin/outreach/reply-inbox/run': ['platform/admin/OutreachHealthCard.jsx'],
 '/api/admin/outreach/social/post-now': ['platform/admin/OutreachHealthCard.jsx'],
 '/api/admin/outreach/tenants': ['platform/admin/OutreachHealthCard.jsx'],
 '/api/admin/outreach/unmatched-pixels': ['platform/admin/OutreachHealthCard.jsx'],
 '/api/admin/outreach/unmatched-pixels/link': ['platform/admin/OutreachHealthCard.jsx'],
 '/api/admin/pillars-map/collection/': ['platform/AdminPillarsMap.jsx'],
 '/api/admin/pillars-map/endpoint-audit/summary': ['platform/AdminPillarsMap.jsx'],
 '/api/admin/pillars-map/heartbeat': ['lib/sentinel.js',
                                      'platform/AdminPillarsMap.jsx',
                                      'platform/MissionControlRibbon.jsx',
                                      'platform/SystemPulseHUD.jsx'],
 '/api/admin/pillars-map/live-events': ['platform/AdminSidebarBlocks.jsx'],
 '/api/admin/pillars-map/overview': ['lib/sentinel.js', 'platform/CorePulseDot.jsx', 'platform/SystemStatusChip.jsx'],
 '/api/admin/pillars-map/sidebar-blocks': ['platform/AdminSidebarBlocks.jsx'],
 '/api/admin/pillars-map/subproduct/T2_subproduct_vanguard': ['platform/AdminVanguard.jsx'],
 '/api/admin/pillars-map/sync': ['platform/AdminPillarsMap.jsx', 'platform/MissionControlRibbon.jsx'],
 '/api/admin/pillars-map/wire/': ['platform/AdminPillarsMap.jsx'],
 '/api/admin/pixel-buffer/stats': ['platform/AdminControlCenter.jsx'],
 '/api/admin/plans/': ['platform/AdminPlanManager.jsx'],
 '/api/admin/plans/all': ['platform/AdminPlanManager.jsx'],
 '/api/admin/plans/custom/pricing': ['platform/AdminPlanManager.jsx'],
 '/api/admin/platform/campaign-leads': ['platform/AdminLeadsMining.jsx'],
 '/api/admin/platform/spine/health': ['platform/AdminConsole.jsx'],
 '/api/admin/platform/website-builder/autopilot': ['platform/AWBCockpit.jsx'],
 '/api/admin/platform/website-builder/cockpit': ['platform/AWBCockpit.jsx'],
 '/api/admin/platform/website-builder/domains': ['platform/AWBCockpit.jsx'],
 '/api/admin/platform/website-builder/run-batch': ['platform/AWBCockpit.jsx'],
 '/api/admin/poll-cache/stats': ['platform/CacheHitRateWidget.jsx'],
 '/api/admin/poll-cache/tune': ['platform/CacheHitRateWidget.jsx'],
 '/api/admin/promote-now/': ['platform/admin/CustomerHealthPanel.jsx'],
 '/api/admin/public-api-keys': ['platform/AdminApiKeysPage.jsx'],
 '/api/admin/public-api-keys/': ['platform/AdminApiKeysPage.jsx'],
 '/api/admin/public-api-keys/issue': ['platform/AdminApiKeysPage.jsx'],
 '/api/admin/repair/status': ['platform/RepairBanner.jsx'],
 '/api/admin/root-command/overview': ['platform/AdminRootCommand.jsx'],
 '/api/admin/security-keys': ['platform/AdminSecurityKeys.jsx'],
 '/api/admin/sentinel/': ['platform/AdminDevConsole.jsx'],
 '/api/admin/sentinel/analyze/': ['platform/AdminSentinelClient.jsx'],
 '/api/admin/sentinel/errors': ['platform/AdminDevConsole.jsx', 'platform/AdminSentinelClient.jsx'],
 '/api/admin/sentinel/overview': ['lib/sentinel.js',
                                  'platform/AdminCommandHub.jsx',
                                  'platform/AdminDevConsole.jsx',
                                  'platform/AdminMissionControl.jsx',
                                  'platform/AdminSentinelClient.jsx'],
 '/api/admin/sentinel/suggestions': ['platform/AdminDevConsole.jsx', 'platform/AdminSentinelClient.jsx'],
 '/api/admin/sentinel/suggestions/': ['platform/AdminSentinelClient.jsx'],
 '/api/admin/site-monitor/overview': ['platform/AdminSiteMonitor.jsx'],
 '/api/admin/site-monitor/scan-now': ['platform/AdminSiteMonitor.jsx'],
 '/api/admin/site-monitor/tenants': ['platform/AdminSiteMonitor.jsx'],
 '/api/admin/sla/snapshot': ['platform/admin/SlaCard.jsx'],
 '/api/admin/sovereignty/score': ['platform/AdminSovereigntyScore.jsx', 'platform/SystemOverview.jsx'],
 '/api/admin/ssot/config': ['platform/AdminSSOT.jsx'],
 '/api/admin/ssot/log': ['platform/AdminSSOT.jsx'],
 '/api/admin/ssot/reset': ['platform/AdminSSOT.jsx'],
 '/api/admin/ssot/update': ['platform/AdminSSOT.jsx'],
 '/api/admin/stem-fix/': ['platform/AdminStemFix.jsx'],
 '/api/admin/stem-fix/generate': ['platform/AdminRootCommand.jsx', 'platform/AdminStemFix.jsx'],
 '/api/admin/stem-fix/pending': ['platform/AdminStemFix.jsx'],
 '/api/admin/supply-chain/autofix': ['platform/admin/AdminSupplyChain.jsx'],
 '/api/admin/supply-chain/history': ['platform/admin/AdminSupplyChain.jsx'],
 '/api/admin/supply-chain/latest': ['platform/admin/AdminSupplyChain.jsx'],
 '/api/admin/supply-chain/remediate': ['platform/admin/AdminSupplyChain.jsx'],
 '/api/admin/supply-chain/remediations': ['platform/admin/AdminSupplyChain.jsx'],
 '/api/admin/supply-chain/scan': ['platform/admin/AdminSupplyChain.jsx'],
 '/api/admin/system-audit': ['lib/sentinel.js', 'platform/AdminControlCenter.jsx', 'platform/AdminSystemAudit.jsx'],
 '/api/admin/system-audit/run-health-check': ['platform/AdminSystemAudit.jsx'],
 '/api/admin/system-overview/stats': ['platform/SystemOverview.jsx'],
 '/api/admin/system-pulse-live': ['lib/sentinel.js'],
 '/api/admin/tenants': ['platform/SuperAdminDashboard.jsx'],
 '/api/admin/tenants/plan': ['platform/SuperAdminDashboard.jsx'],
 '/api/admin/transparency/wall': ['lib/sentinel.js', 'platform/TransparencyWall.jsx'],
 '/api/admin/truth-ledger': ['lib/sentinel.js'],
 '/api/admin/truth-ledger/recent': ['platform/TruthLedgerPanel.jsx'],
 '/api/admin/truth-ledger/stats': ['platform/TruthLedgerPanel.jsx'],
 '/api/admin/voice-agent/overview': ['platform/AdminCommandHub.jsx', 'platform/admin/VoiceAgentStudio.jsx'],
 '/api/admin/voice-agent/retell/': ['platform/SystemOverview.jsx'],
 '/api/admin/voice-agent/retell/voices': ['platform/admin/VoiceAgentStudio.jsx'],
 '/api/admin/voice-agent/test-call': ['platform/SettingsPage.jsx'],
 '/api/admin/wiring-audit': ['lib/sentinel.js', 'platform/AdminControlCenter.jsx', 'platform/AdminWiringAudit.jsx'],
 '/api/admin/wiring-audit/history': ['platform/AdminWiringAudit.jsx'],
 '/api/admin/wiring-audit/probe-override': ['platform/AdminWiringAudit.jsx'],
 '/api/admin/wiring-audit/run-nightly': ['platform/AdminWiringAudit.jsx'],
 '/api/admin/wiring-audit/suggest': ['platform/AdminWiringAudit.jsx'],
 '/api/agents/': ['platform/AdminSystemAudit.jsx', 'platform/AgentCommandCenter.jsx', 'platform/ORACommandConsole.jsx'],
 '/api/agents/audit-chain': ['platform/AgentSwarm.jsx'],
 '/api/agents/board/kill-switch': ['platform/BoardroomPage.jsx'],
 '/api/agents/board/meeting': ['platform/BoardroomPage.jsx'],
 '/api/agents/board/pulse': ['lib/sentinel.js', 'platform/AdminShell.jsx'],
 '/api/agents/board/rates': ['platform/BoardroomPage.jsx'],
 '/api/agents/board/rates/': ['platform/BoardroomPage.jsx'],
 '/api/agents/board/rollup': ['lib/sentinel.js', 'platform/AdminShell.jsx', 'platform/BoardroomPage.jsx'],
 '/api/agents/execute': ['platform/AgentSwarm.jsx'],
 '/api/agents/hunter/commands': ['platform/ORACommandConsole.jsx'],
 '/api/agents/hunter/csv-hunt': ['platform/ORACommandConsole.jsx'],
 '/api/agents/hunter/hunt-now': ['hooks/useAuthFetch.js', 'platform/ORACommandConsole.jsx'],
 '/api/agents/hunter/run-test': ['platform/AdminHunterTest.jsx'],
 '/api/agents/hunter/run-test/history': ['platform/AdminHunterTest.jsx'],
 '/api/agents/list': ['platform/AgentSwarm.jsx'],
 '/api/agents/stats': ['platform/ORACommandConsole.jsx'],
 '/api/agents/status': ['hooks/useAuthFetch.js', 'platform/AgentCommandCenter.jsx', 'platform/ORACommandConsole.jsx'],
 '/api/agents/swarm/execute': ['platform/AgentSwarm.jsx'],
 '/api/ai/chat': ['platform/ShopifyAppManager.jsx'],
 '/api/analytics/': ['services/_archive/api.legacy.js'],
 '/api/analytics/dashboard': ['services/_archive/api.legacy.js'],
 '/api/analytics/revenue': ['services/_archive/api.legacy.js'],
 '/api/approvals/': ['platform/ApprovalQueue.jsx', 'platform/MorningBrief.jsx', 'platform/ORACommandConsole.jsx'],
 '/api/approvals/bulk': ['platform/ApprovalQueue.jsx'],
 '/api/approvals/history': ['platform/ApprovalQueue.jsx'],
 '/api/approvals/patterns': ['platform/ApprovalQueue.jsx'],
 '/api/approvals/pending': ['platform/ApprovalQueue.jsx', 'platform/ORACommandConsole.jsx'],
 '/api/approvals/settings': ['platform/ApprovalQueue.jsx'],
 '/api/approvals/stats': ['platform/ApprovalQueue.jsx'],
 '/api/asi-evolve/active-instructions': ['platform/ASIEvolveDashboard.jsx'],
 '/api/asi-evolve/approve/': ['platform/ASIEvolveDashboard.jsx'],
 '/api/asi-evolve/history': ['platform/ASIEvolveDashboard.jsx'],
 '/api/asi-evolve/pending': ['platform/ASIEvolveDashboard.jsx'],
 '/api/asi-evolve/reject/': ['platform/ASIEvolveDashboard.jsx'],
 '/api/asi-evolve/stats': ['platform/ASIEvolveDashboard.jsx'],
 '/api/asi-evolve/trigger': ['platform/ASIEvolveDashboard.jsx'],
 '/api/attribution/sales': ['platform/NexusDataBridge.jsx'],
 '/api/attribution/summary': ['platform/NexusDataBridge.jsx'],
 '/api/aurem-billing/status': ['platform/admin/CustomerHealthPanel.jsx'],
 '/api/aurem-billing/stripe-status': ['platform/SettingsPage.jsx'],
 '/api/aurem/activity/feed': ['platform/APIGateway.jsx', 'platform/AuremDashboard.jsx'],
 '/api/aurem/admin/status': ['platform/AdminStatusBar.jsx'],
 '/api/aurem/admin/sync': ['platform/AdminStatusBar.jsx'],
 '/api/aurem/agents/status': ['platform/APIGateway.jsx',
                              'platform/AuremDashboard.jsx',
                              'platform/luxe/LuxePages.jsx',
                              'platform/luxe/LuxeV2Pages.jsx',
                              'platform/luxe/useLuxeDashboardData.js'],
 '/api/aurem/bug-engine/history': ['platform/AuremBugHistory.jsx'],
 '/api/aurem/bug-engine/scan': ['platform/AuremBugHistory.jsx'],
 '/api/aurem/bug-engine/stats': ['platform/AuremBugHistory.jsx'],
 '/api/aurem/chat': ['platform/APIGateway.jsx',
                     'platform/AuremDashboard.jsx',
                     'platform/RevenueForecastDashboard.jsx',
                     'platform/customer/CustomerOra.jsx'],
 '/api/aurem/chat/stream': ['platform/customer/CustomerOra.jsx'],
 '/api/aurem/metrics': ['platform/APIGateway.jsx', 'platform/AnalyticsHub.jsx', 'platform/AuremDashboard.jsx'],
 '/api/aurem/morning-brief': ['platform/ORACommandConsole.jsx'],
 '/api/auth/': ['lib/api.js', 'services/_archive/api.legacy.js'],
 '/api/auth/admin/2fa/disable': ['platform/Admin2FAEnroll.jsx'],
 '/api/auth/admin/2fa/enable': ['platform/Admin2FAEnroll.jsx'],
 '/api/auth/admin/2fa/setup': ['platform/Admin2FAEnroll.jsx'],
 '/api/auth/admin/2fa/status': ['platform/Admin2FAEnroll.jsx'],
 '/api/auth/admin/login': ['lib/api.js', 'lib/sentinel.js', 'platform/AdminLogin.jsx', 'utils/secureTokenStore.js'],
 '/api/auth/admin/logout': ['platform/AdminShell.jsx'],
 '/api/auth/admin/refresh': ['lib/api.js'],
 '/api/auth/forgot-password': ['platform/ForgotPassword.jsx', 'platform/luxe/LuxeAuthOverlay.jsx'],
 '/api/auth/google/callback': ['components/GoogleAuthButton.js',
                               'lib/sentinel.js',
                               'platform/GoogleAuthCallback.jsx',
                               'platform/SystemOverview.jsx'],
 '/api/auth/login': ['lib/api.js',
                     'lib/sentinel.js',
                     'platform/APIGateway.jsx',
                     'platform/PlatformAuth.jsx',
                     'services/_archive/api.legacy.js'],
 '/api/auth/logout': ['services/_archive/api.legacy.js'],
 '/api/auth/me': ['services/_archive/api.legacy.js'],
 '/api/auth/register': ['platform/APIGateway.jsx', 'services/_archive/api.legacy.js'],
 '/api/auth/reset-password': ['platform/ResetPassword.jsx', 'platform/luxe/LuxeAuthOverlay.jsx'],
 '/api/auth/signup': ['platform/SystemOverview.jsx'],
 '/api/auth/verify-email': ['platform/VerifyEmail.jsx'],
 '/api/auto-hunt/queue': ['platform/AgentCommandCenter.jsx'],
 '/api/auto-hunt/settings': ['platform/AgentCommandCenter.jsx', 'platform/ORACommandConsole.jsx'],
 '/api/auto-hunt/toggle': ['platform/AgentCommandCenter.jsx'],
 '/api/automations/workflows': ['platform/AutomationEngine.jsx', 'platform/luxe/LuxeV2Pages.jsx'],
 '/api/automations/workflows/': ['platform/luxe/LuxeV2Pages.jsx'],
 '/api/billing/plan/state': ['components/TrialBanner.jsx'],
 '/api/bin-auth/': ['lib/sentinel.js'],
 '/api/bin-auth/customer-context': ['platform/luxe/LuxePages.jsx'],
 '/api/bin-auth/first-login/set-password': ['platform/customer/CustomerSettings.jsx'],
 '/api/bin/ora/ask': ['components/ORAWidget.jsx'],
 '/api/bin/ora/settings': ['platform/luxe/LuxeV2Pages.jsx'],
 '/api/bin/settings': ['platform/luxe/LuxeV2Pages.jsx'],
 '/api/biometric/pin-verify': ['platform/APIGateway.jsx'],
 '/api/biometric/setup': ['components/FastBiometricSetup.jsx'],
 '/api/biometric/webauthn/auth/finish': ['components/FastBiometricLogin.jsx', 'platform/OraPWA.jsx'],
 '/api/biometric/webauthn/auth/start': ['components/FastBiometricLogin.jsx', 'platform/OraPWA.jsx'],
 '/api/biometric/webauthn/register/finish': ['components/FastBiometricSetup.jsx'],
 '/api/biometric/webauthn/register/start': ['components/FastBiometricSetup.jsx'],
 '/api/book': ['platform/developers/DevExamples.jsx'],
 '/api/brief/generate': ['platform/MorningBrief.jsx'],
 '/api/brief/history': ['platform/MorningBrief.jsx'],
 '/api/brief/settings': ['platform/MorningBrief.jsx'],
 '/api/brief/today': ['components/SystemStatusBar.jsx', 'platform/MorningBrief.jsx'],
 '/api/browser-agent-v2/recent': ['platform/AdminBrowserAgent.jsx'],
 '/api/browser-agent-v2/screenshot': ['platform/AdminBrowserAgent.jsx'],
 '/api/bugcatch/stream': ['lib/useReliableSSE.js'],
 '/api/build-journal/feed': ['platform/BuildLog.jsx'],
 '/api/build-journal/stats': ['platform/BuildLog.jsx'],
 '/api/builder-test': ['platform/AdminControlCenter.jsx'],
 '/api/business-id/dismiss-welcome': ['platform/WelcomeCard.jsx'],
 '/api/business-id/mine': ['platform/AuremDashboard.jsx',
                           'platform/SettingsPage.jsx',
                           'platform/WelcomeCard.jsx',
                           'platform/admin/CustomerHealthPanel.jsx'],
 '/api/business-id/qr/': ['platform/SettingsPage.jsx', 'platform/WelcomeCard.jsx'],
 '/api/business-id/regenerate': ['platform/SettingsPage.jsx'],
 '/api/business-id/resend-welcome': ['platform/SettingsPage.jsx', 'platform/WelcomeCard.jsx'],
 '/api/business-id/team': ['platform/SettingsPage.jsx'],
 '/api/business-id/welcome-status': ['platform/AuremDashboard.jsx'],
 '/api/business/': ['components/BusinessManagement.jsx'],
 '/api/business/create': ['components/BusinessManagement.jsx'],
 '/api/business/list': ['components/BusinessManagement.jsx'],
 '/api/cache/clear': ['components/SystemStatusBar.jsx'],
 '/api/campaign/': ['platform/CampaignDashboard.jsx'],
 '/api/campaign/auto-blast/run-now': ['platform/CampaignDashboard.jsx'],
 '/api/campaign/auto-blast/status': ['platform/CampaignDashboard.jsx'],
 '/api/campaign/auto-blast/toggle': ['platform/CampaignDashboard.jsx'],
 '/api/campaign/auto-blast/unflag-all-noise': ['platform/SystemOverview.jsx'],
 '/api/campaign/do-not-contact': ['platform/ORACommandConsole.jsx'],
 '/api/campaign/leads': ['platform/CampaignDashboard.jsx'],
 '/api/campaign/leads/': ['platform/CampaignDashboard.jsx'],
 '/api/campaign/ops-status': ['platform/CampaignDashboard.jsx'],
 '/api/campaign/overview': ['components/SystemStatusBar.jsx', 'platform/CampaignDashboard.jsx'],
 '/api/campaign/scrape': ['platform/CampaignDashboard.jsx'],
 '/api/campaign/seed-aurem': ['platform/CampaignDashboard.jsx'],
 '/api/campaign/stats': ['platform/CampaignDashboard.jsx'],
 '/api/campaign/why-not-sending': ['platform/SystemOverview.jsx'],
 '/api/campaigns': ['platform/developers/DevExamples.jsx'],
 '/api/campaigns/': ['platform/LiveCampaignPipeline.jsx'],
 '/api/case-study/download/': ['platform/AdminCaseStudy.jsx', 'platform/CustomerBoardReport.jsx'],
 '/api/case-study/generate': ['platform/CustomerBoardReport.jsx'],
 '/api/case-study/mine': ['platform/CustomerBoardReport.jsx'],
 '/api/case-study/preview': ['platform/CustomerBoardReport.jsx'],
 '/api/catalog/services': ['platform/customer/CustomerWebsite.jsx', 'platform/luxe/useLuxeDashboardData.js'],
 '/api/churn/analytics': ['components/SystemStatusBar.jsx'],
 '/api/clients': ['platform/ClientManager.jsx'],
 '/api/clients/': ['platform/ClientManager.jsx'],
 '/api/clients/platform/subscribers': ['platform/ClientManager.jsx'],
 '/api/clients/platform/subscribers/': ['platform/ClientManager.jsx'],
 '/api/clients/stats/overview': ['platform/ClientManager.jsx'],
 '/api/cloudinary/upload': ['lib/imageOptimization.js'],
 '/api/coach/start-invisible': ['platform/InvisibleCoach.jsx'],
 '/api/comms/bulk-recovery': ['platform/OmnichannelHub.jsx'],
 '/api/comms/campaigns': ['platform/LiveCampaignPipeline.jsx', 'platform/OmnichannelHub.jsx'],
 '/api/comms/chat': ['components/LiveChatWidget.jsx'],
 '/api/comms/sent-messages': ['platform/OmnichannelHub.jsx'],
 '/api/comms/stats': ['platform/OmnichannelHub.jsx'],
 '/api/compliance/': ['platform/enterprise/EnterpriseCompliance.jsx'],
 '/api/compliance/audit-report': ['platform/AgentCommandCenter.jsx'],
 '/api/compliance/audit-trail': ['platform/SOC2ComplianceDashboard.jsx'],
 '/api/compliance/audit-trail/stats': ['platform/SOC2ComplianceDashboard.jsx'],
 '/api/compliance/daily-report/generate': ['platform/SOC2ComplianceDashboard.jsx'],
 '/api/compliance/daily-report/history': ['platform/SOC2ComplianceDashboard.jsx'],
 '/api/compliance/daily-report/latest': ['platform/SOC2ComplianceDashboard.jsx'],
 '/api/compliance/data-deletion': ['platform/SOC2ComplianceDashboard.jsx'],
 '/api/compliance/encryption-evidence': ['platform/SOC2ComplianceDashboard.jsx'],
 '/api/compliance/evidence-snapshot': ['platform/SOC2ComplianceDashboard.jsx'],
 '/api/compliance/kill-switch/': ['platform/SOC2ComplianceDashboard.jsx'],
 '/api/compliance/rbac-matrix': ['platform/SOC2ComplianceDashboard.jsx'],
 '/api/compliance/regions': ['platform/TrustCenter.jsx'],
 '/api/compliance/sla': ['platform/EnterpriseSLA.jsx', 'platform/TrustCenter.jsx'],
 '/api/compliance/soc2/sample': ['platform/SystemOverview.jsx', 'platform/TrustCenter.jsx'],
 '/api/compliance/status': ['platform/ORACommandConsole.jsx'],
 '/api/compliance/subprocessors': ['platform/TrustCenter.jsx'],
 '/api/compliance/summary': ['platform/SOC2ComplianceDashboard.jsx'],
 '/api/contacts/import': ['platform/developers/DevExamples.jsx'],
 '/api/content-engine/generate-video': ['platform/VideoMarketing.jsx'],
 '/api/content-engine/usage': ['platform/VideoMarketing.jsx'],
 '/api/content-engine/video-history': ['platform/VideoMarketing.jsx'],
 '/api/conviction/activity': ['platform/CampaignDashboard.jsx'],
 '/api/conviction/config': ['platform/CampaignDashboard.jsx', 'platform/LeadsDashboard.jsx'],
 '/api/critic/parseltongue': ['platform/AuremDashboard.jsx'],
 '/api/critic/ultraplinian': ['platform/AuremDashboard.jsx'],
 '/api/crm-sync/connect': ['platform/CRMConnect.jsx', 'platform/NexusDataBridge.jsx'],
 '/api/crm-sync/connections': ['platform/CRMConnect.jsx', 'platform/NexusDataBridge.jsx'],
 '/api/crm-sync/disconnect/': ['platform/CRMConnect.jsx'],
 '/api/crm-sync/sync-contacts': ['platform/CRMConnect.jsx', 'platform/NexusDataBridge.jsx'],
 '/api/crm-sync/sync-jobs': ['platform/CRMConnect.jsx'],
 '/api/crm/': ['services/_archive/api.legacy.js'],
 '/api/crm/customers': ['services/_archive/api.legacy.js'],
 '/api/crm/subscribers': ['services/_archive/api.legacy.js'],
 '/api/crm/subscribers/': ['services/_archive/api.legacy.js'],
 '/api/cto/leads/hot': ['platform/developers/HotLeadsBar.jsx'],
 '/api/cto/rules': ['platform/AuremRulesEditor.jsx'],
 '/api/customer/activity': ['platform/customer/CustomerActivity.jsx'],
 '/api/customer/api-key': ['platform/customer/CustomerIntegrations.jsx',
                           'platform/customer/CustomerSettings.jsx',
                           'platform/luxe/LuxePages.jsx'],
 '/api/customer/api-key/regenerate': ['platform/customer/CustomerSettings.jsx'],
 '/api/customer/appointments': ['platform/customer/CustomerAppointments.jsx'],
 '/api/customer/audit/': ['platform/SystemOverview.jsx'],
 '/api/customer/audit/admin/live': ['platform/admin/AuditLiveDashboard.jsx'],
 '/api/customer/audit/history': ['platform/SystemOverview.jsx'],
 '/api/customer/audit/latest': ['platform/SystemOverview.jsx', 'platform/customer/AuditWidget.jsx'],
 '/api/customer/audit/run': ['platform/SystemOverview.jsx', 'platform/customer/AuditWidget.jsx'],
 '/api/customer/billing': ['platform/customer/CustomerBilling.jsx'],
 '/api/customer/billing/portal': ['platform/customer/CustomerBilling.jsx'],
 '/api/customer/diagnostic/run-now/': ['platform/luxe/LuxeV2Pages.jsx'],
 '/api/customer/friend-scan': ['platform/FrameworkMap.jsx', 'platform/customer/CustomerWebsite.jsx'],
 '/api/customer/inbox/reply': ['platform/luxe/CustomerResultsRow.jsx'],
 '/api/customer/inbox/thread/': ['platform/luxe/CustomerResultsRow.jsx'],
 '/api/customer/inbox/threads': ['platform/luxe/CustomerResultsRow.jsx', 'platform/luxe/useLuxeDashboardData.js'],
 '/api/customer/intelligence/buckets': ['platform/customer/IntelligenceWidget.jsx'],
 '/api/customer/intelligence/import-csv': ['platform/customer/IntelligenceWidget.jsx'],
 '/api/customer/intelligence/merge-now': ['platform/customer/IntelligenceWidget.jsx'],
 '/api/customer/intelligence/summary': ['platform/customer/IntelligenceWidget.jsx'],
 '/api/customer/leads': ['platform/customer/CustomerLeads.jsx'],
 '/api/customer/leads/funnel': ['platform/customer/CustomerLeads.jsx'],
 '/api/customer/orchestrator/queue': ['platform/luxe/LuxePages.jsx'],
 '/api/customer/orchestrator/workflows': ['platform/luxe/LuxePages.jsx'],
 '/api/customer/pipeline/scan-events': ['platform/luxe/LuxeV2Pages.jsx', 'platform/luxe/useLuxeDashboardData.js'],
 '/api/customer/pipeline/trigger': ['platform/luxe/LuxePages.jsx'],
 '/api/customer/pixel/install': ['platform/customer/CustomerWebsite.jsx'],
 '/api/customer/pixel/status': ['lib/sentinel.js',
                                'platform/customer/CustomerIntegrations.jsx',
                                'platform/luxe/LuxePages.jsx'],
 '/api/customer/referrals': ['platform/customer/CustomerReferrals.jsx'],
 '/api/customer/repair/': ['platform/customer/CouncilRepairPanel.jsx'],
 '/api/customer/repair/eligibility': ['platform/customer/CouncilRepairPanel.jsx'],
 '/api/customer/repair/initiate': ['platform/customer/CouncilRepairPanel.jsx'],
 '/api/customer/reports': ['platform/customer/CustomerReport.jsx'],
 '/api/customer/reports/generate': ['platform/customer/CustomerReport.jsx'],
 '/api/customer/results-activity': ['platform/luxe/CustomerResultsRow.jsx'],
 '/api/customer/results-pipeline': ['platform/luxe/CustomerResultsRow.jsx',
                                    'platform/luxe/components/PipelineCard.jsx',
                                    'platform/luxe/useLuxeDashboardData.js'],
 '/api/customer/results-summary': ['platform/luxe/CustomerResultsRow.jsx', 'platform/luxe/useLuxeDashboardData.js'],
 '/api/customer/reviews': ['platform/customer/CustomerReviews.jsx'],
 '/api/customer/reviews/request-batch': ['platform/customer/CustomerReviews.jsx'],
 '/api/customer/scan-schedule': ['platform/luxe/LuxePages.jsx', 'platform/luxe/LuxeV2Pages.jsx'],
 '/api/customer/scan/now': ['platform/luxe/LuxePages.jsx'],
 '/api/customer/social/status': ['platform/customer/CustomerSocial.jsx'],
 '/api/customer/social/toggle': ['platform/customer/CustomerSocial.jsx'],
 '/api/customer/subscriptions': ['platform/customer/CustomerWebsite.jsx',
                                 'platform/luxe/LuxePages.jsx',
                                 'platform/luxe/LuxeV2Pages.jsx',
                                 'platform/luxe/useLuxeDashboardData.js'],
 '/api/customer/subscriptions/cancel': ['platform/customer/CustomerWebsite.jsx'],
 '/api/customer/subscriptions/subscribe': ['platform/customer/CustomerWebsite.jsx'],
 '/api/customer/vanguard/status': ['platform/luxe/useLuxeDashboardData.js'],
 '/api/customer/voice-agent/status': ['platform/SettingsPage.jsx',
                                      'platform/customer/CustomerSettings.jsx',
                                      'platform/luxe/LuxePages.jsx'],
 '/api/customer/website/repair/start': ['platform/customer/CustomerWebsite.jsx'],
 '/api/customer/website/repair/status': ['platform/customer/CustomerWebsite.jsx'],
 '/api/customer/website/scan': ['platform/customer/CustomerWebsite.jsx'],
 '/api/customers/list': ['platform/NexusDataBridge.jsx'],
 '/api/customers/stats/overview': ['platform/NexusDataBridge.jsx'],
 '/api/dashboard-feeds/call-logs': ['platform/feeds/CallLogsFeed.jsx'],
 '/api/dashboard-feeds/email-history': ['platform/feeds/EmailHistoryFeed.jsx'],
 '/api/dashboard-feeds/fallback-monitor': ['platform/feeds/FallbackMonitorFeed.jsx'],
 '/api/dashboard-feeds/flame-alerts/test': ['platform/feeds/HotLeadsFeed.jsx'],
 '/api/dashboard-feeds/hot-leads': ['platform/feeds/HotLeadsFeed.jsx'],
 '/api/deep-scout/search': ['platform/DeepScoutDashboard.jsx'],
 '/api/deep-scout/stats': ['platform/DeepScoutDashboard.jsx'],
 '/api/design-extract/public/run': ['platform/DesignExtractPublic.jsx', 'platform/SystemOverview.jsx'],
 '/api/design-extract/public/sample': ['platform/DesignExtractPublic.jsx'],
 '/api/developers/byok': ['platform/developers/DevConnect.jsx', 'platform/developers/DevSettings.jsx'],
 '/api/developers/checkout/start': ['platform/developers/DevTokens.jsx'],
 '/api/developers/checkout/status/': ['platform/developers/DevTokens.jsx'],
 '/api/developers/cto/chat/history': ['platform/developers/DevCtoChatPanel.jsx'],
 '/api/developers/cto/chat/stream': ['platform/developers/DevCtoChatPanel.jsx'],
 '/api/developers/cto/file/tree': ['platform/developers/CodebaseMap.jsx'],
 '/api/developers/cto/learning/confidence': ['platform/developers/ConfidenceBadge.jsx'],
 '/api/developers/cto/learning/record': ['platform/developers/DeployProgressDialog.jsx',
                                         'platform/developers/SaveToGithubDialog.jsx'],
 '/api/developers/cto/uploads': ['platform/developers/DevCtoChatPanel.jsx'],
 '/api/developers/cto/verify/deploy': ['platform/developers/DeployProgressDialog.jsx'],
 '/api/developers/cto/verify/github': ['platform/developers/SaveToGithubDialog.jsx'],
 '/api/developers/database/info': ['platform/developers/DevDatabase.jsx'],
 '/api/developers/delete-request': ['platform/developers/DevSettings.jsx'],
 '/api/developers/deploy/config': ['platform/developers/DevConnect.jsx', 'platform/developers/DevDeploy.jsx'],
 '/api/developers/deploy/history': ['platform/developers/DevConnect.jsx', 'platform/developers/DevDeploy.jsx'],
 '/api/developers/deploy/log/': ['platform/developers/DevConnect.jsx', 'platform/developers/DevDeploy.jsx'],
 '/api/developers/deploy/run': ['platform/developers/DevConnect.jsx',
                                'platform/developers/DevCtoChatPanel.jsx',
                                'platform/developers/DevDeploy.jsx'],
 '/api/developers/domain/config': ['platform/developers/DevConnect.jsx', 'platform/developers/DevDomain.jsx'],
 '/api/developers/github/commit': ['platform/developers/SaveToGithubDialog.jsx'],
 '/api/developers/github/link': ['platform/developers/DevConnect.jsx'],
 '/api/developers/github/me': ['platform/developers/DevConnect.jsx', 'platform/developers/DeveloperShell.jsx'],
 '/api/developers/github/oauth/callback': ['platform/developers/PlatformCredentialsBlock.jsx'],
 '/api/developers/github/oauth/start': ['platform/developers/DevConnect.jsx'],
 '/api/developers/github/repos': ['platform/developers/SaveToGithubDialog.jsx'],
 '/api/developers/github/repos/': ['platform/developers/SaveToGithubDialog.jsx'],
 '/api/developers/login': ['platform/developers/DevLogin.jsx'],
 '/api/developers/me': ['platform/developers/DevAnalytics.jsx', 'platform/developers/DeveloperShell.jsx'],
 '/api/developers/openapi': ['platform/developers/DevApiDocs.jsx'],
 '/api/developers/projects': ['platform/developers/DevCtoChatPanel.jsx', 'platform/developers/DeveloperShell.jsx'],
 '/api/developers/projects/': ['platform/developers/DevCtoChatPanel.jsx'],
 '/api/developers/public/stats': ['platform/developers/DevLanding.jsx'],
 '/api/developers/security/generate-keys': ['platform/developers/SecurityKeysBlock.jsx'],
 '/api/developers/security/status': ['platform/developers/SecurityKeysBlock.jsx'],
 '/api/developers/session/release': ['platform/developers/DevSettings.jsx'],
 '/api/developers/sessions': ['platform/developers/DevSettings.jsx'],
 '/api/developers/settings/secrets': ['platform/developers/PlatformCredentialsBlock.jsx'],
 '/api/developers/settings/secrets/': ['platform/developers/PlatformCredentialsBlock.jsx'],
 '/api/developers/signup': ['platform/developers/DevSignup.jsx'],
 '/api/developers/verify-otp': ['platform/developers/DevSignup.jsx'],
 '/api/docs/campaign-report': ['platform/ClientManager.jsx'],
 '/api/docs/download/': ['platform/ClientManager.jsx'],
 '/api/docs/health-deck': ['platform/ClientManager.jsx'],
 '/api/docs/proposal': ['platform/ClientManager.jsx'],
 '/api/documents/': ['platform/KnowledgeDocuments.jsx'],
 '/api/documents/list': ['platform/KnowledgeDocuments.jsx'],
 '/api/documents/query': ['platform/KnowledgeDocuments.jsx'],
 '/api/documents/rag/status': ['platform/KnowledgeDocuments.jsx'],
 '/api/documents/upload': ['platform/KnowledgeDocuments.jsx'],
 '/api/edit/admin/send-link': ['platform/AWBCockpit.jsx'],
 '/api/edit/nps': ['pages/CustomerEditPortal.jsx'],
 '/api/edit/request-access': ['pages/CustomerEditPortal.jsx'],
 '/api/edit/save': ['pages/CustomerEditPortal.jsx'],
 '/api/edit/upload-image': ['pages/CustomerEditPortal.jsx'],
 '/api/edit/verify': ['pages/CustomerEditPortal.jsx'],
 '/api/empire-hud/nodes': ['lib/sentinel.js', 'platform/EmpireHUDMap.jsx'],
 '/api/enrichment/bulk-enrich': ['platform/NexusDataBridge.jsx'],
 '/api/enrichment/enrich-all': ['platform/LeadEnrichmentDashboard.jsx'],
 '/api/enrichment/enrich-contact': ['platform/NexusDataBridge.jsx'],
 '/api/enrichment/enrich/': ['platform/LeadsDashboard.jsx'],
 '/api/enrichment/stats': ['platform/LeadEnrichmentDashboard.jsx'],
 '/api/enrichment/status': ['platform/NexusDataBridge.jsx'],
 '/api/enterprise/audit': ['platform/EnterpriseFeatures.jsx', 'platform/enterprise/EnterpriseAdminOverview.jsx'],
 '/api/enterprise/branding': ['platform/enterprise/EnterpriseBranding.jsx'],
 '/api/enterprise/domain': ['platform/enterprise/EnterpriseDomain.jsx'],
 '/api/enterprise/domain/verify': ['platform/enterprise/EnterpriseDomain.jsx'],
 '/api/enterprise/export/': ['platform/EnterpriseFeatures.jsx'],
 '/api/enterprise/keys': ['platform/enterprise/EnterpriseApiKeys.jsx'],
 '/api/enterprise/keys/': ['platform/enterprise/EnterpriseApiKeys.jsx'],
 '/api/enterprise/leads': ['platform/ContactSales.jsx'],
 '/api/enterprise/leads/track': ['platform/ContactSales.jsx'],
 '/api/enterprise/roles': ['platform/EnterpriseFeatures.jsx'],
 '/api/enterprise/team': ['platform/EnterpriseFeatures.jsx'],
 '/api/enterprise/team/': ['platform/EnterpriseFeatures.jsx'],
 '/api/enterprise/team/invite': ['platform/EnterpriseFeatures.jsx'],
 '/api/enterprise/whitelabel': ['platform/EnterpriseFeatures.jsx'],
 '/api/extension/download': ['platform/AcquisitionEngine.jsx'],
 '/api/extension/leads': ['platform/AcquisitionEngine.jsx'],
 '/api/extension/leads/': ['platform/AcquisitionEngine.jsx'],
 '/api/extension/leads/export': ['platform/AcquisitionEngine.jsx'],
 '/api/extension/leads/stats': ['platform/AcquisitionEngine.jsx'],
 '/api/feedback': ['platform/developers/DevExamples.jsx'],
 '/api/feedback/': ['platform/developers/DevExamples.jsx'],
 '/api/foo': ['hooks/useAuthFetch.js', 'hooks/useLivePolling.js', 'lib/__tests__/safeFetchJson.test.js'],
 '/api/forensic-miner/history': ['platform/ShopifyAppManager.jsx'],
 '/api/forensic-miner/queue-outreach': ['platform/ShopifyAppManager.jsx'],
 '/api/forensic-miner/scan': ['platform/ShopifyAppManager.jsx'],
 '/api/forensic/analyze/screenshot': ['components/ForensicUploader.jsx'],
 '/api/forensic/analyze/text': ['components/ForensicUploader.jsx'],
 '/api/forensic/repair': ['components/ForensicUploader.jsx'],
 '/api/founder/sovereign-truth/state': ['platform/OraPWA.jsx'],
 '/api/founder/sovereign-truth/toggle': ['platform/OraPWA.jsx'],
 '/api/fraud/dashboard': ['components/SystemStatusBar.jsx'],
 '/api/gateway/request-logs': ['platform/APIGateway.jsx'],
 '/api/gateway/stats': ['platform/APIGateway.jsx'],
 '/api/gateway/webhooks': ['platform/APIGateway.jsx'],
 '/api/geo/history': ['platform/GEODashboard.jsx'],
 '/api/geo/live-check': ['platform/GEODashboard.jsx'],
 '/api/geo/score': ['platform/GEODashboard.jsx'],
 '/api/ghost/config': ['platform/GhostModePanel.jsx'],
 '/api/ghost/history': ['platform/GhostModePanel.jsx'],
 '/api/ghost/morning-brief': ['platform/GhostModePanel.jsx'],
 '/api/ghost/run-cycle': ['platform/GhostModePanel.jsx'],
 '/api/ghost/toggle': ['platform/GhostModePanel.jsx'],
 '/api/global-pulse/boc': ['platform/GlobalPulseDashboard.jsx'],
 '/api/global-pulse/deltas': ['platform/GlobalPulseDashboard.jsx'],
 '/api/global-pulse/geo-context': ['platform/GlobalPulseDashboard.jsx'],
 '/api/global-pulse/latest': ['platform/GlobalPulseDashboard.jsx'],
 '/api/global-pulse/scan': ['platform/GlobalPulseDashboard.jsx'],
 '/api/global-pulse/ticker': ['platform/EconomicTicker.jsx'],
 '/api/gmail/': ['platform/APIGateway.jsx', 'platform/GmailIntegration.jsx'],
 '/api/graphify/share/': ['pages/BrainGraphShare.jsx', 'platform/AdminBrainGraph.jsx'],
 '/api/graphify/snapshot': ['platform/AdminBrainGraph.jsx'],
 '/api/graphify/snapshot/': ['platform/AdminBrainGraph.jsx'],
 '/api/graphify/snapshots': ['platform/AdminBrainGraph.jsx'],
 '/api/growth/github/sync': ['components/GitHubLeadMiner.jsx'],
 '/api/growth/leads': ['components/GitHubLeadMiner.jsx'],
 '/api/growth/outreach/trigger': ['components/GitHubLeadMiner.jsx'],
 '/api/growth/stats': ['components/GitHubLeadMiner.jsx'],
 '/api/health': ['lib/BuildBadge.jsx', 'lib/sentinel.js', 'platform/SystemStatusChip.jsx', 'utils/fetchWithRetry.js'],
 '/api/highsignal/autotune/feedback': ['platform/AuremDashboard.jsx'],
 '/api/inbox/reply': ['platform/SystemOverview.jsx'],
 '/api/incident/fingerprints': ['platform/admin/IncidentLedger.jsx'],
 '/api/incident/list': ['platform/admin/IncidentLedger.jsx'],
 '/api/incident/report': ['index.js', 'utils/incidentReporter.js'],
 '/api/incident/resolve/': ['platform/admin/IncidentLedger.jsx'],
 '/api/incident/status/': ['platform/admin/IncidentLedger.jsx'],
 '/api/incident/triage/': ['platform/admin/IncidentLedger.jsx'],
 '/api/incidents/list': ['platform/luxe/LuxeV2Pages.jsx'],
 '/api/incidents/resolve/': ['platform/luxe/LuxeV2Pages.jsx'],
 '/api/integration/keys': ['platform/APIGateway.jsx', 'platform/APIKeysManager.jsx', 'platform/MissionControl.jsx'],
 '/api/integration/keys/': ['platform/APIKeysManager.jsx'],
 '/api/integrations/': ['platform/ConnectionWizard.jsx'],
 '/api/integrations/email/configure/': ['platform/ConnectionWizard.jsx'],
 '/api/integrations/email/test/': ['platform/ConnectionWizard.jsx'],
 '/api/integrations/polaris-built-001/whatsapp/status': ['platform/CampaignDashboard.jsx'],
 '/api/integrations/status/': ['platform/ConnectionWizard.jsx'],
 '/api/intelligence/all-clients': ['components/SystemStatusBar.jsx', 'platform/WebsiteIntelligence.jsx'],
 '/api/intelligence/checkout': ['platform/IntelligenceHub.jsx'],
 '/api/intelligence/dashboard': ['platform/AnalyticsHub.jsx'],
 '/api/intelligence/dna-profile': ['platform/IntelligenceHub.jsx'],
 '/api/intelligence/generate-offer': ['platform/IntelligenceHub.jsx'],
 '/api/intelligence/latest/': ['platform/WebsiteIntelligence.jsx'],
 '/api/intelligence/pipeline/predictions': ['platform/SalesPipelineDashboard.jsx'],
 '/api/intelligence/report/': ['platform/ClientReport.jsx'],
 '/api/intelligence/revenue/forecast': ['platform/AnalyticsHub.jsx'],
 '/api/intelligence/scan/': ['platform/WebsiteIntelligence.jsx'],
 '/api/invoices': ['platform/developers/DevExamples.jsx'],
 '/api/leads': ['platform/LeadsDashboard.jsx', 'platform/developers/DevExamples.jsx', 'platform/luxe/LuxePages.jsx'],
 '/api/leads/': ['platform/LeadsDashboard.jsx', 'platform/luxe/LuxeV2Pages.jsx'],
 '/api/leads/health': ['lib/sentinel.js'],
 '/api/leads/hot': ['platform/developers/DevCtoChatPanel.jsx', 'platform/developers/HotLeadsBar.jsx'],
 '/api/leads/stats': ['platform/LeadsDashboard.jsx',
                      'platform/luxe/LuxePages.jsx',
                      'platform/luxe/LuxeV2Pages.jsx',
                      'platform/luxe/useLuxeDashboardData.js'],
 '/api/legal/': ['platform/LegalPages.jsx'],
 '/api/legal/documents': ['platform/LegalPages.jsx'],
 '/api/legion/install': ['platform/SystemOverview.jsx'],
 '/api/lifecycle/add-note': ['platform/feeds/LeadPipelineKanban.jsx'],
 '/api/lifecycle/lead/': ['platform/feeds/LeadPipelineKanban.jsx'],
 '/api/lifecycle/manual-blast': ['platform/feeds/LeadPipelineKanban.jsx'],
 '/api/lifecycle/metrics': ['platform/feeds/LeadPipelineKanban.jsx'],
 '/api/lifecycle/move-stage': ['platform/feeds/LeadPipelineKanban.jsx'],
 '/api/lifecycle/pipeline': ['platform/feeds/LeadPipelineKanban.jsx'],
 '/api/lifecycle/webhook/resend': ['platform/FrameworkMap.jsx'],
 '/api/lifecycle/webhook/whapi': ['platform/FrameworkMap.jsx'],
 '/api/linkedin/auth': ['platform/SettingsPage.jsx'],
 '/api/linkedin/disconnect': ['platform/SettingsPage.jsx'],
 '/api/linkedin/stats': ['platform/SettingsPage.jsx'],
 '/api/linkedin/status': ['platform/SettingsPage.jsx'],
 '/api/local-llm/config': ['platform/FrameworkMap.jsx'],
 '/api/local-llm/status': ['platform/SidebarAddons.jsx', 'platform/_archive/SentinelOverwatch.jsx'],
 '/api/local-llm/test': ['platform/FrameworkMap.jsx'],
 '/api/loyalty/': ['services/_archive/api.legacy.js'],
 '/api/loyalty/me': ['services/_archive/api.legacy.js'],
 '/api/loyalty/redeem': ['services/_archive/api.legacy.js'],
 '/api/marketing/': ['services/_archive/api.legacy.js'],
 '/api/marketing/send-offer': ['services/_archive/api.legacy.js'],
 '/api/me/': ['platform/OraPWA.jsx'],
 '/api/me/billing/summary': ['platform/OraPWA.jsx'],
 '/api/me/consent': ['platform/developers/ConsentToggleCard.jsx'],
 '/api/me/history': ['platform/OraPWA.jsx'],
 '/api/me/home/dashboard': ['platform/customer/CustomerHome.jsx', 'platform/luxe/useLuxeDashboardData.js'],
 '/api/me/identity': ['platform/OraPWA.jsx'],
 '/api/me/leads/today': ['platform/OraPWA.jsx'],
 '/api/me/notifications/today': ['platform/OraPWA.jsx'],
 '/api/me/scout/status': ['platform/OraPWA.jsx'],
 '/api/memory/ask-user': ['platform/MemoryDashboard.jsx'],
 '/api/memory/episodes': ['platform/MemoryDashboard.jsx'],
 '/api/memory/learning-velocity': ['platform/MemoryDashboard.jsx'],
 '/api/memory/loop-stats': ['platform/MemoryDashboard.jsx'],
 '/api/memory/plans/recent': ['platform/MemoryDashboard.jsx'],
 '/api/memory/promotions': ['platform/MemoryDashboard.jsx'],
 '/api/memory/stats': ['platform/MemoryDashboard.jsx'],
 '/api/modularization/history': ['platform/ModularizationEngine.jsx'],
 '/api/modularization/stats': ['platform/ModularizationEngine.jsx'],
 '/api/negotiate/': ['platform/NegotiationDashboard.jsx'],
 '/api/negotiate/sessions/recent': ['platform/NegotiationDashboard.jsx'],
 '/api/negotiate/start': ['platform/NegotiationDashboard.jsx'],
 '/api/nexus/connect/key': ['platform/NexusPage.jsx'],
 '/api/nexus/connectors': ['platform/NexusPage.jsx'],
 '/api/nexus/disconnect/': ['platform/NexusPage.jsx'],
 '/api/nexus/oauth/': ['platform/NexusPage.jsx'],
 '/api/oauth/gmail/authorize': ['platform/GmailIntegration.jsx'],
 '/api/oauth/gmail/disconnect/': ['platform/GmailIntegration.jsx'],
 '/api/oauth/gmail/status/': ['platform/GmailIntegration.jsx', 'platform/SettingsPage.jsx'],
 '/api/onboarding/activate-pipeline': ['platform/luxe/LuxeV2Pages.jsx'],
 '/api/onboarding/business-profile': ['platform/OnboardingBusinessProfile.jsx', 'platform/luxe/LuxeV2Pages.jsx'],
 '/api/onboarding/by-session/': ['platform/OnboardingWelcome.jsx'],
 '/api/onboarding/complete-step': ['components/QuickStartWizard.jsx'],
 '/api/onboarding/dismiss': ['components/QuickStartWizard.jsx'],
 '/api/onboarding/projects': ['platform/developers/NewProjectFlow.jsx'],
 '/api/onboarding/projects/': ['platform/developers/ProjectWorkspace.jsx'],
 '/api/onboarding/projects/dogfood/aurem-live-init': ['platform/developers/NewProjectFlow.jsx'],
 '/api/onboarding/projects/dogfood/aurem-live-status': ['platform/developers/NewProjectFlow.jsx',
                                                        'platform/developers/ProjectWorkspace.jsx'],
 '/api/onboarding/share/submit': ['platform/developers/NewProjectFlow.jsx'],
 '/api/onboarding/status': ['components/QuickStartWizard.jsx', 'platform/admin/CustomerHealthPanel.jsx'],
 '/api/onboarding/tenant/': ['platform/AuremDashboard.jsx',
                             'platform/OnboardingPixelStep.jsx',
                             'platform/OnboardingWelcome.jsx'],
 '/api/onboarding/urgency/stats': ['platform/AuremReport.jsx'],
 '/api/onboarding/wallet': ['platform/developers/NewProjectFlow.jsx', 'platform/developers/ProjectWorkspace.jsx'],
 '/api/openclaw/branding/': ['platform/OpenClawDashboard.jsx'],
 '/api/openclaw/cost/': ['platform/OpenClawDashboard.jsx'],
 '/api/openclaw/heartbeat/': ['platform/OpenClawDashboard.jsx'],
 '/api/openclaw/permissions/': ['platform/OpenClawDashboard.jsx'],
 '/api/openclaw/persona/': ['platform/OpenClawDashboard.jsx'],
 '/api/openclaw/tiers': ['platform/OpenClawDashboard.jsx'],
 '/api/openfang/leads': ['platform/AdminOpenFang.jsx'],
 '/api/openfang/leads/recent': ['platform/AdminOpenFang.jsx'],
 '/api/openfang/status': ['platform/AdminOpenFang.jsx'],
 '/api/openfang/verify-signature': ['platform/AdminOpenFang.jsx'],
 '/api/optimization/advance-stage/': ['platform/TenantOptimization.jsx'],
 '/api/optimization/dashboard': ['platform/TenantOptimization.jsx'],
 '/api/optimization/metrics/': ['platform/TenantOptimization.jsx'],
 '/api/optimization/profile-all': ['platform/TenantOptimization.jsx'],
 '/api/optimization/profile/': ['platform/TenantOptimization.jsx'],
 '/api/optimization/profiles': ['platform/TenantOptimization.jsx'],
 '/api/optimization/rollback/': ['platform/TenantOptimization.jsx'],
 '/api/optimization/toggle/': ['platform/TenantOptimization.jsx'],
 '/api/ora/actions': ['platform/UniversalConnector.jsx'],
 '/api/ora/agent/': ['platform/admin/OraChat.jsx'],
 '/api/ora/agent/attach': ['platform/admin/OraChat.jsx'],
 '/api/ora/agent/clear/': ['platform/admin/OraChat.jsx'],
 '/api/ora/agent/history/': ['platform/admin/OraChat.jsx'],
 '/api/ora/agent/run': ['platform/admin/OraChat.jsx'],
 '/api/ora/agent/run-async': ['platform/admin/CommandPalette.jsx', 'platform/admin/OraChat.jsx'],
 '/api/ora/agent/status/': ['platform/admin/CommandPalette.jsx', 'platform/admin/OraChat.jsx'],
 '/api/ora/avatar-preference': ['components/ORASelector.jsx'],
 '/api/ora/command': ['platform/AdminShell.jsx', 'platform/SidebarAddons.jsx'],
 '/api/ora/feedback': ['platform/admin/OraChat.jsx'],
 '/api/ora/health': ['lib/sentinel.js', 'platform/luxe/LuxeV2Pages.jsx'],
 '/api/ora/knowledge/force-sync': ['platform/TrainingDashboard.jsx'],
 '/api/ora/knowledge/status': ['platform/TrainingDashboard.jsx'],
 '/api/ora/leads': ['platform/ORARepairEngine.jsx'],
 '/api/ora/pipeline/status': ['platform/luxe/LuxePages.jsx'],
 '/api/ora/pulse/stats': ['platform/UniversalConnector.jsx'],
 '/api/ora/settings': ['platform/ORARepairEngine.jsx'],
 '/api/ora/support-chat': ['components/ORAWidget.jsx'],
 '/api/ora/training/': ['platform/ORARepairEngine.jsx'],
 '/api/ora/training/files': ['platform/ORARepairEngine.jsx'],
 '/api/ora/training/link': ['platform/ORARepairEngine.jsx'],
 '/api/ora/training/upload': ['platform/AuremDashboard.jsx', 'platform/ORARepairEngine.jsx'],
 '/api/ora/tts': ['platform/OraPWA.jsx'],
 '/api/orders': ['services/_archive/api.legacy.js'],
 '/api/orders/': ['services/_archive/api.legacy.js'],
 '/api/orders/my': ['services/_archive/api.legacy.js'],
 '/api/orgs': ['platform/enterprise/EnterpriseCompliance.jsx', 'platform/enterprise/EnterpriseSSO.jsx'],
 '/api/orgs/me': ['platform/OrgSwitcher.jsx',
                  'platform/enterprise/EnterpriseCompliance.jsx',
                  'platform/enterprise/EnterpriseSSO.jsx'],
 '/api/orgs/switch': ['platform/OrgSwitcher.jsx'],
 '/api/overwatch/auth/pin': ['platform/_archive/SentinelOverwatch.jsx'],
 '/api/overwatch/kill-switch': ['platform/_archive/SentinelOverwatch.jsx'],
 '/api/overwatch/pulse': ['platform/_archive/SentinelOverwatch.jsx'],
 '/api/panic/events': ['platform/PanicAlerts.jsx'],
 '/api/panic/resume/': ['components/AuremVoice.jsx'],
 '/api/panic/settings': ['platform/PanicSettings.jsx'],
 '/api/panic/takeover/': ['components/AuremVoice.jsx', 'platform/PanicAlerts.jsx'],
 '/api/password': ['lib/sentinel.js'],
 '/api/payments/checkout': ['platform/AuremReport.jsx', 'platform/PricingPage.jsx'],
 '/api/pillars/health': ['lib/sentinel.js', 'platform/PillarHealthContext.jsx'],
 '/api/pipeline/abort/': ['platform/PipelineDashboard.jsx'],
 '/api/pipeline/contracts/': ['platform/SalesPipelineDashboard.jsx'],
 '/api/pipeline/demo/cleanup/': ['platform/DemoMode.jsx'],
 '/api/pipeline/demo/launch': ['platform/DemoMode.jsx'],
 '/api/pipeline/demo/progress/': ['platform/DemoMode.jsx'],
 '/api/pipeline/demo/run/': ['platform/DemoMode.jsx'],
 '/api/pipeline/find-decision-makers': ['platform/SalesPipelineDashboard.jsx'],
 '/api/pipeline/generate-contract': ['platform/SalesPipelineDashboard.jsx'],
 '/api/pipeline/generate-proposal': ['platform/SalesPipelineDashboard.jsx'],
 '/api/pipeline/history/all': ['platform/PipelineDashboard.jsx'],
 '/api/pipeline/onboarding-status/': ['platform/SalesPipelineDashboard.jsx'],
 '/api/pipeline/runs/active': ['platform/PipelineDashboard.jsx'],
 '/api/pipeline/stats': ['platform/PipelineDashboard.jsx'],
 '/api/pipeline/trigger/': ['platform/PipelineDashboard.jsx'],
 '/api/pixel/aurem-pixel': ['platform/UniversalConnector.jsx', 'platform/admin/CustomerHealthPanel.jsx'],
 '/api/plan/available': ['platform/PricingPage.jsx'],
 '/api/plan/my-usage': ['platform/AuremDashboard.jsx'],
 '/api/platform/auth/2fa/toggle': ['platform/luxe/LuxeV2Pages.jsx'],
 '/api/platform/auth/api-key/regenerate': ['platform/luxe/LuxeV2Pages.jsx'],
 '/api/platform/auth/change-pin': ['platform/AccountSecurity.jsx'],
 '/api/platform/auth/forgot-pin/confirm': ['platform/ForgotPin.jsx'],
 '/api/platform/auth/forgot-pin/request': ['platform/ForgotPin.jsx'],
 '/api/platform/auth/login': ['lib/api.js',
                              'lib/sentinel.js',
                              'platform/PlatformAuth.jsx',
                              'platform/luxe/LuxeAuthContext.jsx'],
 '/api/platform/auth/login-pin': ['platform/PlatformAuth.jsx'],
 '/api/platform/auth/me': ['platform/luxe/LuxeV2Pages.jsx'],
 '/api/platform/auth/pin-status': ['platform/AccountSecurity.jsx'],
 '/api/platform/auth/register': ['lib/sentinel.js', 'platform/PlatformAuth.jsx', 'platform/luxe/LuxeAuthContext.jsx'],
 '/api/platform/auth/session': ['platform/luxe/LuxeV2Pages.jsx'],
 '/api/platform/auth/sessions/all': ['platform/luxe/LuxeV2Pages.jsx'],
 '/api/platform/auth/setup-pin': ['platform/AccountSecurity.jsx'],
 '/api/platform/me': ['platform/luxe/LuxeAuthContext.jsx'],
 '/api/platform/me/update': ['platform/luxe/LuxePages.jsx'],
 '/api/plugins/wordpress': ['platform/FrameworkMap.jsx', 'platform/SystemOverview.jsx'],
 '/api/preview/': ['platform/AWBCockpit.jsx'],
 '/api/preview/projects/': ['platform/PublicProjectPreview.jsx'],
 '/api/products': ['services/_archive/api.legacy.js'],
 '/api/products/': ['services/_archive/api.legacy.js'],
 '/api/proximity/blast': ['platform/ProximityBlast.jsx'],
 '/api/proximity/campaigns': ['platform/LiveCampaignPipeline.jsx', 'platform/ProximityBlast.jsx'],
 '/api/proximity/config': ['platform/ProximityBlast.jsx'],
 '/api/proximity/conversion-metrics': ['platform/RevenueForecastDashboard.jsx'],
 '/api/proximity/deploy-envoy': ['platform/ProximityBlast.jsx'],
 '/api/public/audit-request': ['platform/ContactPage.jsx'],
 '/api/public/aurem-stats': ['lib/sentinel.js'],
 '/api/public/booking/': ['platform/SystemOverview.jsx', 'platform/luxe/LuxePages.jsx'],
 '/api/public/config': ['config/aurem.config.js', 'lib/sentinel.js'],
 '/api/public/ora/chat': ['platform/AuremHomepage.jsx', 'platform/OraPWA.jsx', 'platform/luxe/LuxeV2Pages.jsx'],
 '/api/public/ora/chat/stream': ['platform/OraPWA.jsx'],
 '/api/public/ora/metrics/summary': ['platform/AdminConsole.jsx'],
 '/api/public/repair-quote/': ['pages/ShareableReport.jsx'],
 '/api/public/repair-quote/audit': ['pages/RepairQuote.jsx'],
 '/api/public/repair-quote/health': ['platform/AuremHomepage.jsx'],
 '/api/public/report/': ['platform/SharedReportPage.jsx'],
 '/api/public/seo-funnel/checkout': ['platform/FreeSeoAudit.jsx'],
 '/api/public/seo-funnel/scan': ['platform/FreeSeoAudit.jsx'],
 '/api/public/site-monitor/status/': ['platform/PublicStatusPage.jsx'],
 '/api/public/status': ['platform/AuremHomepage.jsx',
                        'platform/PublicStatus.jsx',
                        'platform/SystemOverview.jsx',
                        'platform/developers/DevStatus.jsx'],
 '/api/public/status/badge': ['platform/PublicStatus.jsx'],
 '/api/public/subscribe': ['platform/OnboardingWelcome.jsx'],
 '/api/public/system-overview/stats': ['platform/SystemOverview.jsx'],
 '/api/push/subscribe': ['hooks/usePushNotifications.js'],
 '/api/push/unsubscribe': ['hooks/usePushNotifications.js'],
 '/api/qa/deep/latest': ['platform/SystemPulseLive.jsx'],
 '/api/qa/deep/run-now': ['platform/SystemPulseLive.jsx'],
 '/api/qa/guardian/actions': ['platform/SystemPulseLive.jsx'],
 '/api/qa/guardian/status': ['platform/SystemPulseLive.jsx'],
 '/api/qa/pulse/endpoints': ['platform/SystemPulseLive.jsx'],
 '/api/qa/pulse/history': ['platform/SystemPulseLive.jsx'],
 '/api/qa/pulse/latest': ['platform/AdminDevConsole.jsx', 'platform/SystemPulseLive.jsx'],
 '/api/qa/pulse/run-now': ['lib/sentinel.js', 'platform/SystemPulseLive.jsx'],
 '/api/referrals/dashboard': ['platform/PartnerReferralPortal.jsx'],
 '/api/repair-report/': ['platform/AuremReport.jsx'],
 '/api/repair/': ['platform/AdminAutoFixer.jsx', 'platform/ORARepairEngine.jsx'],
 '/api/repair/accessibility/generate': ['platform/ORARepairEngine.jsx'],
 '/api/repair/deploy/checkout': ['platform/ORARepairEngine.jsx'],
 '/api/repair/deploy/download/': ['platform/ORARepairEngine.jsx'],
 '/api/repair/deploy/free/': ['platform/ORARepairEngine.jsx'],
 '/api/repair/deploy/github-check': ['platform/ORARepairEngine.jsx'],
 '/api/repair/deploy/github-pr/': ['platform/ORARepairEngine.jsx'],
 '/api/repair/deploy/preview': ['platform/ORARepairEngine.jsx'],
 '/api/repair/deploy/status/': ['platform/ORARepairEngine.jsx'],
 '/api/repair/geo/generate': ['platform/ORARepairEngine.jsx'],
 '/api/repair/health/heartbeat/last': ['platform/SiteHealthLeaderboard.jsx'],
 '/api/repair/health/heartbeat/run': ['platform/SiteHealthLeaderboard.jsx'],
 '/api/repair/health/leaderboard': ['platform/SiteHealthLeaderboard.jsx', 'platform/luxe/useLuxeDashboardData.js'],
 '/api/repair/health/mark-pixel-deployed': ['platform/SiteHealthLeaderboard.jsx'],
 '/api/repair/health/verify-pixel': ['platform/SiteHealthLeaderboard.jsx'],
 '/api/repair/history': ['platform/AdminAutoFixer.jsx',
                         'platform/ORARepairEngine.jsx',
                         'platform/luxe/LuxePages.jsx',
                         'platform/luxe/useLuxeDashboardData.js'],
 '/api/repair/origin/commit': ['platform/ORARepairEngine.jsx'],
 '/api/repair/origin/serve/': ['platform/SiteHealthLeaderboard.jsx'],
 '/api/repair/origin/status': ['platform/ORARepairEngine.jsx'],
 '/api/repair/origin/verify': ['platform/ORARepairEngine.jsx'],
 '/api/repair/pending': ['platform/AdminAutoFixer.jsx'],
 '/api/repair/scoreboard': ['platform/luxe/LuxeV2Pages.jsx'],
 '/api/repair/scores': ['platform/luxe/LuxeV2Pages.jsx', 'platform/luxe/useLuxeDashboardData.js'],
 '/api/repair/seo/generate': ['platform/ORARepairEngine.jsx'],
 '/api/repair/trigger-scan': ['platform/luxe/LuxeV2Pages.jsx'],
 '/api/report/': ['platform/AuremReport.jsx'],
 '/api/reset-password': ['lib/sentinel.js'],
 '/api/revenue-forecast/90day': ['platform/RevenueForecastDashboard.jsx'],
 '/api/revenue-forecast/brief-line': ['platform/RevenueForecastDashboard.jsx'],
 '/api/revenue/auto-invoice': ['platform/RevenueAutomation.jsx'],
 '/api/revenue/dashboard': ['platform/RevenueAutomation.jsx'],
 '/api/revenue/forecast': ['platform/RevenueAutomation.jsx'],
 '/api/revenue/invoices': ['platform/RevenueAutomation.jsx'],
 '/api/revenue/invoices/': ['platform/RevenueAutomation.jsx'],
 '/api/revenue/reminders': ['platform/RevenueAutomation.jsx'],
 '/api/revenue/reminders/history': ['platform/RevenueAutomation.jsx'],
 '/api/revenue/reminders/send/': ['platform/RevenueAutomation.jsx'],
 '/api/revenue/usage/summary': ['platform/RevenueAutomation.jsx'],
 '/api/sales/pipeline': ['platform/APIGateway.jsx'],
 '/api/saml/': ['platform/SamlAcsLanding.jsx', 'platform/enterprise/EnterpriseSSO.jsx'],
 '/api/scan/quick': ['platform/Demo.jsx'],
 '/api/scan/quick/email-report': ['platform/Demo.jsx'],
 '/api/scan/quick/quota': ['platform/Demo.jsx'],
 '/api/scanner/analyze': ['platform/APIGateway.jsx'],
 '/api/scanner/history': ['platform/CustomerScanner.jsx'],
 '/api/scanner/push-fixes': ['platform/CustomerScanner.jsx'],
 '/api/scanner/repair-live': ['platform/CustomerScanner.jsx'],
 '/api/scanner/save': ['platform/CustomerScanner.jsx'],
 '/api/scanner/scan-live': ['platform/CustomerScanner.jsx'],
 '/api/scanner/scans': ['platform/InvisibleCoach.jsx',
                        'platform/SalesPipelineDashboard.jsx',
                        'platform/VoiceSalesAgent.jsx'],
 '/api/scanner/share': ['platform/CustomerScanner.jsx'],
 '/api/scim/': ['platform/enterprise/EnterpriseSSO.jsx'],
 '/api/scout/unified': ['platform/ORACommandConsole.jsx'],
 '/api/scout/verify/lead': ['platform/CampaignDashboard.jsx'],
 '/api/scout/verify/lead/': ['platform/CampaignDashboard.jsx'],
 '/api/security/audit/agentic': ['platform/SecurityDashboard.jsx'],
 '/api/security/audit/asvs': ['platform/SecurityDashboard.jsx'],
 '/api/security/compliance/badge': ['platform/SecurityDashboard.jsx'],
 '/api/security/pentest/health': ['platform/SecurityDashboard.jsx'],
 '/api/security/pentest/history': ['platform/SecurityDashboard.jsx'],
 '/api/security/pentest/run': ['platform/SecurityDashboard.jsx'],
 '/api/security/scan/full': ['platform/SecurityDashboard.jsx'],
 '/api/security/shannon/mock-audit': ['platform/_archive/SentinelOverwatch.jsx'],
 '/api/self-audit/backups': ['platform/AutonomyLog.jsx'],
 '/api/self-audit/cron-status': ['platform/AutonomyLog.jsx'],
 '/api/self-audit/cron-trigger': ['platform/AutonomyLog.jsx'],
 '/api/self-audit/log': ['platform/AutonomyLog.jsx'],
 '/api/self-audit/rollback/': ['platform/AutonomyLog.jsx'],
 '/api/self-audit/run': ['platform/AutonomyLog.jsx'],
 '/api/self-audit/stats': ['platform/AutonomyLog.jsx'],
 '/api/self-audit/tier': ['platform/AutonomyLog.jsx'],
 '/api/self-repair/customers': ['platform/AdminSelfRepair.jsx'],
 '/api/self-repair/customers/': ['platform/AdminSelfRepair.jsx'],
 '/api/self-repair/trigger': ['platform/AdminSelfRepair.jsx'],
 '/api/self-repair/unfixable': ['platform/AdminSelfRepair.jsx'],
 '/api/self-repair/unfixable/': ['platform/AdminSelfRepair.jsx'],
 '/api/sentinel-anomaly/history': ['platform/SentinelAnomalyDashboard.jsx'],
 '/api/sentinel-anomaly/scan': ['platform/SentinelAnomalyDashboard.jsx'],
 '/api/sentinel-anomaly/stats': ['platform/SentinelAnomalyDashboard.jsx'],
 '/api/sentinel/alerts': ['platform/SentinelDashboard.jsx'],
 '/api/sentinel/client-error': ['index.js', 'lib/sentinel.js'],
 '/api/sentinel/cost/alltime': ['platform/SentinelDashboard.jsx'],
 '/api/sentinel/cost/chart': ['platform/SentinelDashboard.jsx'],
 '/api/sentinel/cost/month': ['platform/SentinelDashboard.jsx'],
 '/api/sentinel/cost/today': ['platform/SentinelDashboard.jsx'],
 '/api/sentinel/fixes-log': ['platform/SentinelDashboard.jsx', 'platform/luxe/LuxePages.jsx'],
 '/api/sentinel/git-backup': ['platform/SentinelDashboard.jsx'],
 '/api/sentinel/heartbeat': ['lib/sentinel.js', 'platform/AuremDashboard.jsx'],
 '/api/sentinel/known-fixes': ['platform/SentinelDashboard.jsx'],
 '/api/sentinel/model-routing': ['platform/SentinelDashboard.jsx'],
 '/api/sentinel/pulse-history': ['platform/SentinelDashboard.jsx', 'platform/luxe/LuxePages.jsx'],
 '/api/sentinel/search-stats': ['platform/SentinelDashboard.jsx'],
 '/api/sentinel/status': ['platform/SentinelDashboard.jsx', 'platform/luxe/LuxePages.jsx'],
 '/api/sentinel/trigger-cycle': ['platform/SentinelDashboard.jsx'],
 '/api/seo-audit/checkout': ['platform/SEOAuditPage.jsx'],
 '/api/seo-audit/report/': ['platform/SEOAuditPage.jsx'],
 '/api/seo-audit/scan': ['lib/sentinel.js', 'platform/SEOAuditPage.jsx'],
 '/api/service-catalog': ['lib/sentinel.js'],
 '/api/services/catalog': ['lib/sentinel.js'],
 '/api/settings/api-keys': ['platform/ApiKeysSettings.jsx'],
 '/api/settings/api-keys/': ['platform/ApiKeysSettings.jsx'],
 '/api/settings/buffer': ['platform/SettingsPage.jsx'],
 '/api/settings/infrastructure': ['platform/SettingsPage.jsx'],
 '/api/settings/infrastructure/create-indexes': ['platform/SettingsPage.jsx'],
 '/api/settings/infrastructure/test-redis': ['platform/SettingsPage.jsx'],
 '/api/settings/notifications': ['platform/SettingsPage.jsx'],
 '/api/settings/password': ['platform/SettingsPage.jsx'],
 '/api/settings/profile': ['platform/SettingsPage.jsx'],
 '/api/settings/sidebar-order': ['platform/AuremDashboard.jsx'],
 '/api/shopify-app/compliance/generate-snippet': ['platform/ShopifyAppManager.jsx'],
 '/api/shopify-app/compliance/status': ['platform/ShopifyAppManager.jsx'],
 '/api/shopify-app/connections': ['platform/ShopifyAppManager.jsx'],
 '/api/shopify-app/connections/': ['platform/ShopifyAppManager.jsx'],
 '/api/shopify-app/pixel/analytics': ['platform/ShopifyAppManager.jsx'],
 '/api/shopify-app/sync/status': ['platform/ShopifyAppManager.jsx'],
 '/api/shopify-billing/plans': ['platform/ShopifyAppManager.jsx'],
 '/api/shopify-listing/content': ['platform/ShopifyAppManager.jsx'],
 '/api/shopify-listing/submission-checklist': ['platform/ShopifyAppManager.jsx'],
 '/api/shopify/auth': ['platform/SettingsPage.jsx',
                       'platform/SystemOverview.jsx',
                       'platform/customer/CustomerIntegrations.jsx',
                       'platform/luxe/LuxePages.jsx'],
 '/api/shopify/auth/callback': ['platform/SystemOverview.jsx'],
 '/api/shopify/auth/status': ['platform/SettingsPage.jsx',
                              'platform/SystemOverview.jsx',
                              'platform/customer/CustomerIntegrations.jsx',
                              'platform/luxe/LuxePages.jsx'],
 '/api/shopify/connect': ['platform/NexusDataBridge.jsx'],
 '/api/shopify/connections': ['platform/NexusDataBridge.jsx'],
 '/api/shopify/pulse/fix/alt-text': ['platform/ShopifyAppManager.jsx'],
 '/api/shopify/pulse/recovery/stats': ['platform/ShopifyAppManager.jsx'],
 '/api/shopify/pulse/scan': ['platform/ShopifyAppManager.jsx'],
 '/api/shopify/sync-customers': ['platform/NexusDataBridge.jsx'],
 '/api/shopify/sync-jobs': ['platform/NexusDataBridge.jsx'],
 '/api/site-monitor/free/signup': ['platform/MonitorFreeLanding.jsx'],
 '/api/site-monitor/me/endpoints': ['platform/CustomerSiteMonitor.jsx'],
 '/api/site-monitor/me/endpoints/': ['platform/CustomerSiteMonitor.jsx'],
 '/api/site-monitor/me/incidents': ['platform/CustomerSiteMonitor.jsx'],
 '/api/site-monitor/me/plan': ['platform/CustomerSiteMonitor.jsx'],
 '/api/site-monitor/me/sites': ['platform/luxe/LuxeV2Pages.jsx'],
 '/api/site-monitor/me/upgrade': ['platform/CustomerSiteMonitor.jsx'],
 '/api/slots': ['platform/developers/DevExamples.jsx'],
 '/api/smart-onboarding/detect': ['platform/customer/CustomerOnboarding.jsx'],
 '/api/smart-onboarding/start': ['platform/customer/CustomerOnboarding.jsx'],
 '/api/sovereign-voice/stats': ['platform/FrameworkMap.jsx'],
 '/api/sovereign-voice/status': ['platform/FrameworkMap.jsx'],
 '/api/sovereign/telemetry-status': ['platform/SystemOverview.jsx', 'platform/SystemPulseLive.jsx'],
 '/api/static/admin-dashboard-bg': ['platform/AuremDashboard.jsx'],
 '/api/static/aurem-badge': ['platform/CustomerSiteMonitor.jsx'],
 '/api/static/customer-360-bg': ['platform/AdminCustomer360.jsx'],
 '/api/static/plugins/aurem-pixel': ['platform/SystemOverview.jsx'],
 '/api/stripe-embed/create-session': ['platform/ApplePayCheckout.jsx'],
 '/api/stripe-embed/publishable-key': ['platform/ApplePayCheckout.jsx'],
 '/api/subscription/checkout': ['platform/UsageBilling.jsx'],
 '/api/subscriptions/custom/available-services': ['platform/CustomSubscriptionBuilder.jsx'],
 '/api/subscriptions/custom/calculate-pricing': ['platform/CustomSubscriptionBuilder.jsx'],
 '/api/subscriptions/custom/create': ['platform/CustomSubscriptionBuilder.jsx'],
 '/api/system/circuit-breakers': ['components/CircuitBreakerDashboard.jsx'],
 '/api/system/circuit-breakers/reset': ['components/CircuitBreakerDashboard.jsx'],
 '/api/system/modules': ['platform/TenantOptimization.jsx'],
 '/api/system/overview/public': ['lib/sentinel.js'],
 '/api/system/status': ['components/SystemStatusBar.jsx'],
 '/api/system/sync': ['components/SystemStatusBar.jsx'],
 '/api/telegram/status': ['platform/AdminControlCenter.jsx'],
 '/api/training/a2a': ['platform/TrainingDashboard.jsx'],
 '/api/training/a2a/trigger': ['platform/TrainingDashboard.jsx'],
 '/api/training/autotune': ['platform/TrainingDashboard.jsx'],
 '/api/training/autotune/analytics': ['platform/TrainingDashboard.jsx'],
 '/api/training/knowledge': ['platform/TrainingDashboard.jsx'],
 '/api/training/knowledge/': ['platform/TrainingDashboard.jsx'],
 '/api/training/knowledge/upload': ['platform/TrainingDashboard.jsx'],
 '/api/training/overview': ['platform/TrainingDashboard.jsx'],
 '/api/training/voice': ['platform/TrainingDashboard.jsx'],
 '/api/trial/activate': ['platform/customer/CustomerWebsite.jsx'],
 '/api/trial/status': ['platform/TrialBanner.jsx', 'platform/customer/CustomerWebsite.jsx'],
 '/api/ucp/manifest': ['platform/UniversalConnector.jsx'],
 '/api/universal/connections': ['platform/UniversalConnector.jsx'],
 '/api/universal/connections/': ['platform/UniversalConnector.jsx'],
 '/api/universal/import/analyze': ['platform/UniversalConnector.jsx'],
 '/api/universal/import/execute': ['platform/UniversalConnector.jsx'],
 '/api/universal/platforms': ['platform/UniversalConnector.jsx'],
 '/api/universal/products': ['platform/UniversalConnector.jsx'],
 '/api/universal/products/': ['platform/UniversalConnector.jsx'],
 '/api/universal/stats': ['platform/UniversalConnector.jsx'],
 '/api/universal/templates/': ['platform/UniversalConnector.jsx'],
 '/api/upload': ['services/_archive/api.legacy.js'],
 '/api/usage/current': ['platform/UsageBilling.jsx'],
 '/api/usage/history': ['platform/UsageBilling.jsx'],
 '/api/usage/quota': ['platform/UsageBilling.jsx'],
 '/api/v1/public/': ['platform/AdminApiKeysPage.jsx'],
 '/api/vault/audit': ['platform/SecretVault.jsx'],
 '/api/vault/audit/summary': ['platform/SecretVault.jsx'],
 '/api/vault/secrets': ['platform/SecretVault.jsx'],
 '/api/vault/secrets/': ['platform/SecretVault.jsx'],
 '/api/version': ['platform/developers/DeployProgressDialog.jsx',
                  'platform/developers/DevCtoChatPanel.jsx',
                  'platform/developers/DeveloperShell.jsx'],
 '/api/viral-gate/start-trial': ['platform/AuremDashboard.jsx'],
 '/api/viral-gate/status': ['platform/AuremDashboard.jsx'],
 '/api/voice-agent/config': ['platform/luxe/LuxeV2Pages.jsx'],
 '/api/voice-agent/health': ['lib/sentinel.js', 'platform/luxe/LuxeV2Pages.jsx'],
 '/api/voice-analytics/data': ['platform/MissionControl.jsx', 'platform/VoiceAnalytics.jsx'],
 '/api/voice/call-history': ['platform/VoiceSalesAgent.jsx'],
 '/api/voice/command': ['components/VoiceWakeWord.jsx'],
 '/api/voice/profiles': ['platform/VoiceSalesAgent.jsx'],
 '/api/voice/start-sales-call': ['platform/VoiceSalesAgent.jsx'],
 '/api/voice/stream': ['components/AuremVoice.jsx'],
 '/api/voice/tts-stream': ['components/VoiceWakeWord.jsx'],
 '/api/voice/web-call': ['components/AuremVoice.jsx'],
 '/api/website-builder/': ['platform/AuremSampleWebsite.jsx'],
 '/api/website-builder/live-viewers': ['platform/CampaignDashboard.jsx'],
 '/api/website-builder/no-website': ['pages/RepairQuote.jsx'],
 '/api/website-builder/sample/': ['platform/AuremSampleWebsite.jsx'],
 '/api/whatsapp/': ['platform/APIGateway.jsx', 'platform/WhatsAppIntegration.jsx']}
