"""
AUREM AI Platform — Proprietary Software
Copyright (c) 2026 Polaris Built Inc.

Legal Documents Router — Policy Management
============================================
Serves all legal/compliance documents from MongoDB.
Public endpoints (no auth required) for legal pages.
"""
import logging
import os
from datetime import datetime, timezone
from fastapi import APIRouter, HTTPException

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/legal", tags=["Legal"])

_db = None


def set_db(database):
    global _db
    _db = database


POLICY_DOCS = {
    "economic_compliance": {
        "doc_id": "economic_compliance_001",
        "tenant_id": "system",
        "title": "Economic Intelligence \u2014 Compliance Statement",
        "slug": "economic-intelligence",
        "content": """AUREM aggregates publicly available economic data from official government sources including the Bank of Canada Valet API and other public data providers. All data is presented for general business context purposes only.

AUREM does not provide investment advice, securities recommendations, or trading signals. AUREM is not registered as an investment advisor, portfolio manager, or dealer under the Securities Act (Ontario) or any other securities legislation.

Users should consult a registered financial professional before making any investment decisions.

Data Sources:
- Bank of Canada Valet API (public, free, no API key required)
- Alpha Vantage (free tier, public market data)
- Public RSS news feeds (Google News, Reuters, TechCrunch)

All economic indicators displayed are historical data points presented for business context. No forward-looking statements, trading recommendations, or investment signals are generated by this platform.""",
        "effective_date": "2026-04-08",
        "company": "Polaris Built Inc.",
        "jurisdiction": "Ontario, Canada",
        "version": "1.0",
        "category": "compliance",
    },
    "terms": {
        "doc_id": "terms_of_service_001",
        "tenant_id": "system",
        "title": "Terms of Service",
        "slug": "terms",
        "content": """AUREM AI PLATFORM \u2014 TERMS OF SERVICE
Effective Date: April 8, 2026
Company: Polaris Built Inc., Mississauga, Ontario, Canada
Contact: Pawandeep19may1985@gmail.com

1. SERVICE DESCRIPTION
AUREM is an autonomous AI-powered business automation platform designed for small and medium businesses. The platform provides autonomous lead generation, customer relationship management, outreach automation, revenue analytics, and economic business intelligence. AUREM operates through AI agents (ORA, Scout, Envoy, Oracle) that perform business tasks on behalf of the user.

2. ACCEPTABLE USE
AUREM is intended for legitimate business purposes only. Users agree to use the platform solely for lawful business operations including but not limited to: lead management, customer outreach, business analytics, and operational automation.

3. PROHIBITED USES
Users shall NOT:
- Resell, sublicense, or redistribute access to AUREM or any of its components
- Reverse engineer, decompile, or attempt to extract source code from the platform
- Use AUREM for any illegal activities including but not limited to fraud, harassment, or unauthorized data collection
- Use AUREM to send unsolicited communications in violation of Canada's Anti-Spam Legislation (CASL) or any other applicable anti-spam laws
- Use the Economic Intelligence features for securities trading, investment advisory, or any regulated financial activity
- Attempt to circumvent usage limits, security measures, or access controls

4. SUBSCRIPTION TERMS
- All subscriptions are billed monthly in Canadian Dollars (CAD)
- Payment is due at the start of each billing period
- Pricing is subject to change with 30 days written notice
- Usage is subject to the limits of your selected plan

5. CANCELLATION POLICY
- You may cancel your subscription at any time through your account settings or by contacting support
- Cancellation takes effect at the end of the current billing period
- No refunds are issued for the current billing period after cancellation
- Your data will be retained for 90 days after cancellation, after which it will be permanently deleted

6. SERVICE AVAILABILITY
- AUREM is provided on a best-effort basis
- We do not guarantee 100% uptime at this stage of the platform
- Scheduled maintenance windows will be communicated in advance when possible
- We reserve the right to modify, suspend, or discontinue features with reasonable notice

7. LIMITATION OF LIABILITY
To the maximum extent permitted by law, Polaris Built Inc. shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of AUREM. Our total liability shall not exceed the amount paid by you in the 12 months preceding any claim.

AUREM's Economic Intelligence features provide general business context only and do not constitute investment advice. Polaris Built Inc. assumes no liability for any business or investment decisions made based on data displayed in the platform.

8. INTELLECTUAL PROPERTY
All content, features, and functionality of AUREM are owned by Polaris Built Inc. and are protected by international copyright, trademark, and other intellectual property laws. Your subscription grants you a limited, non-exclusive, non-transferable license to use the platform.

9. GOVERNING LAW
These Terms shall be governed by and construed in accordance with the laws of the Province of Ontario and the federal laws of Canada applicable therein. Any disputes shall be resolved in the courts of Ontario, Canada.

10. CHANGES TO TERMS
We may update these Terms from time to time. We will notify users of material changes via email or in-platform notification. Continued use of AUREM after changes constitutes acceptance of the updated Terms.

11. CONTACT
For questions about these Terms:
Polaris Built Inc.
Mississauga, Ontario, Canada
Email: Pawandeep19may1985@gmail.com""",
        "effective_date": "2026-04-08",
        "company": "Polaris Built Inc.",
        "jurisdiction": "Ontario, Canada",
        "version": "1.0",
        "category": "terms",
    },
    "privacy": {
        "doc_id": "privacy_policy_001",
        "tenant_id": "system",
        "title": "Privacy Policy",
        "slug": "privacy",
        "content": """AUREM AI PLATFORM \u2014 PRIVACY POLICY
Effective Date: April 8, 2026
Company: Polaris Built Inc., Mississauga, Ontario, Canada
Contact: Pawandeep19may1985@gmail.com

This Privacy Policy describes how Polaris Built Inc. ("we", "us", "our") collects, uses, and protects your information when you use the AUREM AI Platform ("AUREM", "the platform").

1. WHAT DATA WE COLLECT
- Business profile data: company name, contact information, industry, location
- Lead and customer data: information you upload or generate through the platform for your business operations
- Usage analytics: anonymized platform usage patterns to improve our services
- IP address: for security, fraud prevention, and access logging
- Authentication data: email, encrypted password hash, session tokens
- Economic Intelligence interactions: which data views you access (anonymized)

2. WHAT WE DO NOT COLLECT OR DO
- We do NOT sell your data to third parties
- We do NOT share your data with advertisers
- We do NOT use your business data to train AI models for other customers
- Your client data remains your property at all times
- We do NOT track your browsing activity outside of AUREM

3. DATA STORAGE
- All data is stored on Canada-based servers
- Data is encrypted at rest and in transit using industry-standard encryption
- Access to production data is restricted to authorized personnel only

4. DATA RETENTION
- Active accounts: data is retained for the duration of your subscription
- After cancellation: data is retained for 90 days, then permanently deleted
- You may request immediate deletion at any time (see Your Rights below)
- Anonymized usage analytics may be retained indefinitely

5. YOUR RIGHTS
Under PIPEDA and applicable privacy laws, you have the right to:
- Request access to your personal data
- Request correction of inaccurate data
- Request deletion of your data at any time
- Withdraw consent for data processing
- Receive a copy of your data in a portable format

To exercise any of these rights, contact: Pawandeep19may1985@gmail.com
We will respond to all requests within 30 days.

6. PIPEDA COMPLIANCE
This Privacy Policy is designed to comply with the Personal Information Protection and Electronic Documents Act (PIPEDA), Canada's federal privacy law. We adhere to PIPEDA's 10 fair information principles:
- Accountability, Identifying Purposes, Consent, Limiting Collection, Limiting Use/Disclosure/Retention, Accuracy, Safeguards, Openness, Individual Access, and Challenging Compliance.

7. THIRD-PARTY SERVICES
AUREM may integrate with third-party services at your direction (e.g., payment processors, communication APIs). These services have their own privacy policies. We only share the minimum data necessary for the integration to function.

8. COOKIES
See our Cookie Policy at /legal/cookies for details on our cookie usage.

9. CHILDREN'S PRIVACY
AUREM is a business platform and is not intended for use by individuals under 18 years of age.

10. CHANGES TO THIS POLICY
We will notify you of material changes to this Privacy Policy via email or in-platform notification at least 30 days before changes take effect.

11. CONTACT
Privacy Officer:
Polaris Built Inc.
Mississauga, Ontario, Canada
Email: Pawandeep19may1985@gmail.com""",
        "effective_date": "2026-04-08",
        "company": "Polaris Built Inc.",
        "jurisdiction": "Ontario, Canada",
        "version": "1.0",
        "category": "privacy",
    },
    "acceptable_use": {
        "doc_id": "acceptable_use_001",
        "tenant_id": "system",
        "title": "Acceptable Use Policy",
        "slug": "acceptable-use",
        "content": """AUREM AI PLATFORM \u2014 ACCEPTABLE USE POLICY
Effective Date: April 8, 2026
Company: Polaris Built Inc., Mississauga, Ontario, Canada

1. PURPOSE
This Acceptable Use Policy governs your use of the AUREM AI Platform. By using AUREM, you agree to comply with this policy. Violation of this policy may result in immediate account suspension or termination.

2. LEGITIMATE BUSINESS USE ONLY
AUREM is designed exclusively for legitimate business operations. All features, including AI agents, outreach tools, lead generation, and economic intelligence, must be used for lawful business purposes.

3. PROHIBITED ACTIVITIES
You shall NOT use AUREM to:
- Send spam, unsolicited bulk messages, or unwanted communications
- Harass, threaten, or intimidate any individual or organization
- Conduct or facilitate fraud, phishing, or any deceptive practices
- Scrape competitor data illegally or violate any third-party terms of service
- Contact individuals who have not provided consent for communication
- Distribute malware, viruses, or any harmful code
- Impersonate any person or entity
- Violate any applicable local, provincial, federal, or international law

4. CASL COMPLIANCE
Canada's Anti-Spam Legislation (CASL) is one of the strictest anti-spam laws in the world. All AUREM outreach features (Envoy, Proximity Blast, email campaigns) must ONLY be used for contacts who have given:
- Express consent: the individual has explicitly agreed to receive communications from you, OR
- Implied consent: you have an existing business relationship (e.g., they are a current customer, or they inquired about your services within the past 6 months)

It is YOUR responsibility to ensure you have valid consent before using any AUREM outreach feature. AUREM does not verify consent status \u2014 you must maintain your own records.

Violation of CASL through AUREM may result in:
- Immediate account suspension
- Permanent account termination
- Reporting to the Canadian Radio-television and Telecommunications Commission (CRTC)

5. ECONOMIC INTELLIGENCE MODULE
The Economic Intelligence features in AUREM display publicly available economic data for general business context. You shall NOT:
- Use this data as the basis for securities trading or investment decisions
- Represent AUREM's economic data as investment advice to any third party
- Redistribute economic data obtained through AUREM for commercial purposes

6. DATA RESPONSIBILITY
You are responsible for:
- The accuracy of data you upload to AUREM
- Ensuring you have the right to use any customer or lead data you import
- Complying with all applicable privacy laws regarding the personal data you process through AUREM

7. RESOURCE USAGE
You shall not:
- Attempt to circumvent plan limits or usage quotas
- Use automated tools to excessively query AUREM APIs
- Intentionally overload or stress-test the platform without permission

8. ENFORCEMENT
Polaris Built Inc. reserves the right to:
- Investigate suspected violations of this policy
- Suspend or terminate accounts that violate this policy
- Report illegal activities to appropriate authorities
- Remove content that violates this policy

9. REPORTING VIOLATIONS
If you become aware of any violation of this policy, please report it to: Pawandeep19may1985@gmail.com

10. CONTACT
Polaris Built Inc.
Mississauga, Ontario, Canada
Email: Pawandeep19may1985@gmail.com""",
        "effective_date": "2026-04-08",
        "company": "Polaris Built Inc.",
        "jurisdiction": "Ontario, Canada",
        "version": "1.0",
        "category": "acceptable_use",
    },
    "refunds": {
        "doc_id": "refund_policy_001",
        "tenant_id": "system",
        "title": "Refund Policy",
        "slug": "refunds",
        "content": """AUREM AI PLATFORM \u2014 REFUND POLICY
Effective Date: April 8, 2026
Company: Polaris Built Inc., Mississauga, Ontario, Canada

1. MONTHLY SUBSCRIPTIONS
- No refunds are issued for the current billing period
- Cancel before your next billing date to avoid the next charge
- Your access continues until the end of the current billing period after cancellation

2. ANNUAL PLANS (if offered)
- Pro-rated refund available, minus one month of service
- Refund calculated from the date of cancellation request
- Refunds processed within 14 business days

3. FREE TRIAL
- No payment is collected during the free trial period
- If you cancel before the trial ends, you will not be charged
- If you do not cancel, your selected plan will begin billing automatically

4. DISPUTES
- All billing disputes must be raised within 7 days of the charge
- Contact Pawandeep19may1985@gmail.com with your account email and the charge in question
- We will investigate and respond within 5 business days

5. HOW TO CANCEL
- Through your AUREM dashboard: Settings > Subscription > Cancel
- By email: send cancellation request to Pawandeep19may1985@gmail.com
- Cancellation confirmation will be sent to your registered email

6. CONTACT
Polaris Built Inc.
Mississauga, Ontario, Canada
Email: Pawandeep19may1985@gmail.com""",
        "effective_date": "2026-04-08",
        "company": "Polaris Built Inc.",
        "jurisdiction": "Ontario, Canada",
        "version": "1.0",
        "category": "refunds",
    },
    "cookies": {
        "doc_id": "cookie_policy_001",
        "tenant_id": "system",
        "title": "Cookie Policy",
        "slug": "cookies",
        "content": """AUREM AI PLATFORM \u2014 COOKIE POLICY
Effective Date: April 8, 2026
Company: Polaris Built Inc., Mississauga, Ontario, Canada

1. WHAT COOKIES WE USE
AUREM uses only essential cookies required for the platform to function:

Session Cookies:
- Purpose: to keep you logged in during your session
- Duration: expires when you close your browser or after 24 hours
- Required: yes, the platform cannot function without these

Authentication Tokens:
- Purpose: to securely identify your account
- Storage: browser localStorage (not a cookie, but similar function)
- Duration: 24 hours, then you must log in again

2. WHAT WE DO NOT USE
- No advertising cookies
- No third-party tracking cookies
- No social media tracking pixels
- No cross-site tracking of any kind

3. ANALYTICS
- We collect anonymized usage data only (e.g., which features are used most frequently)
- This data cannot be traced back to individual users
- We do not use Google Analytics, Facebook Pixel, or any third-party analytics service that tracks individual users

4. YOUR CHOICES
Since we only use essential cookies, there is no option to disable them without losing platform functionality. If you do not wish to accept cookies, you should not use AUREM.

5. CONTACT
Polaris Built Inc.
Mississauga, Ontario, Canada
Email: Pawandeep19may1985@gmail.com""",
        "effective_date": "2026-04-08",
        "company": "Polaris Built Inc.",
        "jurisdiction": "Ontario, Canada",
        "version": "1.0",
        "category": "cookies",
    },
}


async def seed_legal_documents():
    """Seed or update all legal documents in MongoDB."""
    if _db is None:
        logger.warning("[Legal] No database available for seeding")
        return

    for key, doc in POLICY_DOCS.items():
        try:
            existing = await _db.legal_documents.find_one({"doc_id": doc["doc_id"]})
            doc_data = {
                **doc,
                "last_updated": datetime.now(timezone.utc).isoformat(),
            }
            if existing:
                await _db.legal_documents.update_one(
                    {"doc_id": doc["doc_id"]},
                    {"$set": doc_data}
                )
                logger.info(f"[Legal] Updated: {doc['title']}")
            else:
                doc_data["created_at"] = datetime.now(timezone.utc).isoformat()
                await _db.legal_documents.insert_one(doc_data)
                logger.info(f"[Legal] Created: {doc['title']}")
        except Exception as e:
            logger.error(f"[Legal] Error seeding {key}: {e}")


# ─── Routes ───

@router.get("/documents")
async def list_legal_documents():
    """List all legal documents (index page)."""
    if _db is None:
        return {"documents": list(POLICY_DOCS.values())}
    docs = await _db.legal_documents.find(
        {"tenant_id": "system"},
        {"_id": 0, "content": 0}
    ).to_list(length=20)
    return {"documents": docs if docs else list({k: {kk: vv for kk, vv in v.items() if kk != "content"} for k, v in POLICY_DOCS.items()}.values())}


@router.get("/economic-compliance")
async def get_economic_compliance():
    """Get the Economic Intelligence Compliance Statement."""
    if _db is not None:
        doc = await _db.legal_documents.find_one({"doc_id": "economic_compliance_001"}, {"_id": 0})
        if doc:
            return doc
    return POLICY_DOCS["economic_compliance"]


@router.get("/{slug}")
async def get_legal_document(slug: str):
    """Get a legal document by slug."""
    if _db is not None:
        doc = await _db.legal_documents.find_one({"slug": slug}, {"_id": 0})
        if doc:
            return doc
    # Fallback to in-memory
    for doc in POLICY_DOCS.values():
        if doc["slug"] == slug:
            return doc
    raise HTTPException(status_code=404, detail="Document not found")
