"""
ORA Dev Actions Router (iter 281.2 — Phase 2.2)
================================================
Admin-gated CRUD over `db.ora_dev_actions` — the queue of code-change
proposals generated by ORA's Mode 2 (Software Engineer) brain.

Contract:
  - GET  /api/admin/ora-dev/pending           list pending proposals
  - GET  /api/admin/ora-dev/list?status=...   filtered list (last 100)
  - GET  /api/admin/ora-dev/stats             counts by status
  - POST /api/admin/ora-dev/{id}/approve      mark approved
  - POST /api/admin/ora-dev/{id}/reject       mark rejected
  - POST /api/admin/ora-dev/{id}/applied      mark applied (admin did it)
  - POST /api/admin/ora-dev/{id}/rollback     mark rolled back
  - GET  /api/admin/ora-dev/health            public liveness probe

Hard rule: ORA NEVER auto-applies code. Status transitions only.
Admin still does the actual file editing manually (or uses the
existing pending_code_fixes pipeline for tier-3 auto-heal).
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any, Dict, Optional

from fastapi import APIRouter, Header, HTTPException, Query

from utils.admin_guard import verify_admin

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/admin/ora-dev", tags=["ORA Dev Console"])

_db = None
_VALID_STATUSES = {"pending", "approved", "rejected", "applied", "rolled_back"}


def set_db(db):
    global _db
    _db = db


def _get_db():
    return _db


def _serialize(doc: Dict[str, Any]) -> Dict[str, Any]:
    """Strip MongoDB _id before JSON return."""
    if not doc:
        return {}
    out = {k: v for k, v in doc.items() if k != "_id"}
    return out


@router.get("/health")
async def health():
    db = _get_db()
    return {"ok": True, "db_wired": db is not None}


@router.get("/pending")
async def list_pending(authorization: Optional[str] = Header(None)):
    verify_admin(authorization)
    db = _get_db()
    if db is None:
        raise HTTPException(503, "Database not wired")
    cursor = (
        db.ora_dev_actions
        .find({"status": "pending"})
        .sort("created_at", -1)
        .limit(50)
    )
    items = [_serialize(d) async for d in cursor]
    return {"ok": True, "count": len(items), "items": items}


@router.get("/list")
async def list_actions(
    authorization: Optional[str] = Header(None),
    status: Optional[str] = Query(None),
    limit: int = Query(50, ge=1, le=200),
):
    verify_admin(authorization)
    db = _get_db()
    if db is None:
        raise HTTPException(503, "Database not wired")
    q: Dict[str, Any] = {}
    if status:
        if status not in _VALID_STATUSES:
            raise HTTPException(400, f"Invalid status (allowed: {sorted(_VALID_STATUSES)})")
        q["status"] = status
    cursor = db.ora_dev_actions.find(q).sort("created_at", -1).limit(limit)
    items = [_serialize(d) async for d in cursor]
    return {"ok": True, "count": len(items), "items": items}


@router.get("/stats")
async def stats(authorization: Optional[str] = Header(None)):
    verify_admin(authorization)
    db = _get_db()
    if db is None:
        raise HTTPException(503, "Database not wired")
    counts = {s: 0 for s in _VALID_STATUSES}
    pipeline = [{"$group": {"_id": "$status", "n": {"$sum": 1}}}]
    async for row in db.ora_dev_actions.aggregate(pipeline):
        s = row.get("_id") or "pending"
        counts[s] = int(row.get("n", 0))
    counts["total"] = sum(counts.values())
    return {"ok": True, **counts}


async def _transition(
    proposal_id: str,
    *,
    new_status: str,
    admin_email: Optional[str],
    extra: Optional[Dict[str, Any]] = None,
    allowed_from: Optional[set] = None,
) -> Dict[str, Any]:
    db = _get_db()
    if db is None:
        raise HTTPException(503, "Database not wired")
    doc = await db.ora_dev_actions.find_one({"proposal_id": proposal_id})
    if not doc:
        raise HTTPException(404, f"Proposal {proposal_id} not found")
    if allowed_from and doc.get("status") not in allowed_from:
        raise HTTPException(
            409,
            f"Cannot transition from `{doc.get('status')}` to `{new_status}`",
        )
    update = {
        "status": new_status,
        f"{new_status}_at": datetime.now(timezone.utc).isoformat(),
        f"{new_status}_by": admin_email or "admin",
    }
    if new_status == "approved":
        update["approved_at"] = update[f"{new_status}_at"]
        update["approved_by"] = admin_email or "admin"
    if extra:
        update.update(extra)
    await db.ora_dev_actions.update_one(
        {"proposal_id": proposal_id}, {"$set": update}
    )
    refreshed = await db.ora_dev_actions.find_one({"proposal_id": proposal_id})
    return _serialize(refreshed or {})


@router.post("/{proposal_id}/approve")
async def approve(proposal_id: str, authorization: Optional[str] = Header(None)):
    payload = verify_admin(authorization)
    db = _get_db()
    if db is None:
        raise HTTPException(503, "Database not wired")
    # iter D-34 — Pre-flight seal check BEFORE transition. The previous
    # version updated `status` to "approved" then raised 409 if sealed,
    # leaving the DB in an inconsistent state. Now we refuse the write
    # entirely when sealed_blocked is set.
    pre = await db.ora_dev_actions.find_one(
        {"proposal_id": proposal_id},
        {"sealed_blocked": 1, "status": 1, "_id": 0},
    )
    if not pre:
        raise HTTPException(404, f"Proposal {proposal_id} not found")
    if pre.get("status") != "pending":
        raise HTTPException(
            409, f"Cannot approve from `{pre.get('status')}` — already past pending"
        )
    if pre.get("sealed_blocked"):
        raise HTTPException(
            409,
            {"code": "sealed_blocked",
             "msg":  "Proposal touches sealed file(s) — manual unseal required."},
        )
    doc = await _transition(
        proposal_id,
        new_status="approved",
        admin_email=payload.get("email"),
        allowed_from={"pending"},
    )
    # iter 282e — browser-action proposals auto-execute on approve.
    # Other proposal kinds (code change, ORA action, etc.) stay at
    # "approved" and wait for their existing applier paths.
    if doc.get("kind") == "browser_action":
        try:
            from services.browser_agent_service import execute_approved_action
            exec_result = await execute_approved_action(proposal_id)
            doc["execution_result"] = exec_result
        except Exception as e:
            doc["execution_result"] = {"ok": False, "error": str(e)[:200]}
    # iter 322 — auto_bridge proposals carry a structured `approve_action`
    # the executor knows how to run server-side (e.g., run_migration_iter322,
    # mark_safe_apply). When admin clicks Approve, fire the action and
    # transition status to "applied" + capture the audit payload.
    elif doc.get("source") == "auto_bridge" and doc.get("approve_action"):
        try:
            from services.ora_proposal_bridge import execute_approve_action
            db = _get_db()
            exec_result = await execute_approve_action(db, doc["approve_action"])
            doc["execution_result"] = exec_result
            if exec_result.get("ok"):
                await db.ora_dev_actions.update_one(
                    {"proposal_id": proposal_id},
                    {"$set": {
                        "status": "applied",
                        "applied_at": datetime.now(timezone.utc).isoformat(),
                        "applied_payload": exec_result,
                    }},
                )
                doc["status"] = "applied"
                doc["applied_at"] = datetime.now(timezone.utc).isoformat()
                doc["applied_payload"] = exec_result
        except Exception as e:
            doc["execution_result"] = {"ok": False, "error": str(e)[:200]}
    return {"ok": True, "proposal": doc}


@router.post("/{proposal_id}/reject")
async def reject(proposal_id: str, authorization: Optional[str] = Header(None)):
    payload = verify_admin(authorization)
    doc = await _transition(
        proposal_id,
        new_status="rejected",
        admin_email=payload.get("email"),
        allowed_from={"pending", "approved"},
    )
    return {"ok": True, "proposal": doc}


@router.post("/{proposal_id}/applied")
async def mark_applied(proposal_id: str, authorization: Optional[str] = Header(None)):
    payload = verify_admin(authorization)
    doc = await _transition(
        proposal_id,
        new_status="applied",
        admin_email=payload.get("email"),
        allowed_from={"approved"},
    )
    return {"ok": True, "proposal": doc}


@router.post("/{proposal_id}/rollback")
async def rollback(proposal_id: str, authorization: Optional[str] = Header(None)):
    payload = verify_admin(authorization)
    doc = await _transition(
        proposal_id,
        new_status="rolled_back",
        admin_email=payload.get("email"),
        allowed_from={"applied", "approved"},
    )
    return {"ok": True, "proposal": doc}


# ─── iter 322s — Tier-1 auto-approval cancel window ─────────────────
@router.post("/{proposal_id}/cancel-auto")
async def cancel_auto_approval(
    proposal_id: str, authorization: Optional[str] = Header(None),
):
    """Cancel a tier_1 proposal during its 5-minute auto-execute window.

    Only succeeds if:
      - status == "pending"
      - tier == "tier_1"
      - auto_execute_at is in the future (still in cancel window)
    """
    payload = verify_admin(authorization)
    db = _get_db()
    if db is None:
        raise HTTPException(503, "Database not wired")
    existing = await db.ora_dev_actions.find_one({"proposal_id": proposal_id})
    if not existing:
        raise HTTPException(404, "Proposal not found")
    if existing.get("status") != "pending":
        raise HTTPException(409, f"Cannot cancel — current status is {existing.get('status')}")
    if existing.get("tier") != "tier_1":
        raise HTTPException(409, "Cancel-auto is tier_1 only — use /reject for tier_2")
    aex = existing.get("auto_execute_at")
    if aex and isinstance(aex, datetime) and aex < datetime.now(timezone.utc):
        raise HTTPException(409, "Auto-execute window has already elapsed")
    await db.ora_dev_actions.update_one(
        {"proposal_id": proposal_id},
        {"$set": {
            "status": "cancelled",
            "cancelled_by": payload.get("email"),
            "cancelled_at": datetime.now(timezone.utc).isoformat(),
        }},
    )
    refreshed = await db.ora_dev_actions.find_one({"proposal_id": proposal_id})
    return {"ok": True, "proposal": _serialize(refreshed or {})}


# ─── iter 322t — Plain-Hinglish translation (retro-fill for old proposals) ─
@router.post("/{proposal_id}/translate")
async def translate_proposal(
    proposal_id: str, authorization: Optional[str] = Header(None),
):
    """Retro-translate an existing proposal's request_text + proposal_text
    into plain Hinglish. Useful for proposals created before iter 322t
    that don't yet carry `plain_language`. Idempotent — overwrites any
    existing translation."""
    verify_admin(authorization)
    db = _get_db()
    if db is None:
        raise HTTPException(503, "Database not wired")
    existing = await db.ora_dev_actions.find_one({"proposal_id": proposal_id})
    if not existing:
        raise HTTPException(404, "Proposal not found")

    from services.ora_proposal_bridge import (
        _classify_safety_level, _translate_to_plain_language,
    )
    action_kind = ((existing.get("approve_action") or {}).get("kind")
                   if existing.get("approve_action") else None)
    # Always recompute fresh on retro-translate — don't reuse stale values.
    safety_level = _classify_safety_level(
        action_kind,
        existing.get("source_kind"),
        existing.get("request_text") or "",
        existing.get("proposal_text") or "",
    )
    plain = await _translate_to_plain_language(
        request_text=existing.get("request_text") or "",
        proposal_text=existing.get("proposal_text") or "",
        severity=existing.get("severity") or "P2",
        action_kind=action_kind,
        safety_level=safety_level,
    )
    await db.ora_dev_actions.update_one(
        {"proposal_id": proposal_id},
        {"$set": {
            "plain_language": plain,
            "safety_level": safety_level,
            "translated_at": datetime.now(timezone.utc).isoformat(),
        }},
    )
    refreshed = await db.ora_dev_actions.find_one({"proposal_id": proposal_id})
    return {"ok": True, "proposal": _serialize(refreshed or {})}


# ─── iter 281.3 — Apply via PR (Phase 2.3 add-on) ──────────────────
def _slugify(s: str, n: int = 32) -> str:
    import re
    s = re.sub(r"[^a-zA-Z0-9]+", "-", (s or "").lower()).strip("-")
    return s[:n] or "ora-mode2"


def _extract_target_files(proposal_text: str) -> list:
    """Best-effort parse of TARGET FILE(S) section from Mode 2 prompt output."""
    import re
    lines = (proposal_text or "").splitlines()
    files = []
    in_target = False
    for ln in lines:
        if "TARGET FILE" in ln.upper():
            in_target = True
            continue
        if in_target:
            t = ln.strip().strip("`").strip("*").strip()
            if not t or t.startswith("#"):
                continue
            if t.upper().startswith(("INTENT", "REASONING", "SUGGESTED", "RISKS", "TEST")):
                break
            # Strict: must look like a path — no spaces, has extension,
            # short enough to be a file path (not a sentence).
            if " " in t or len(t) > 200:
                continue
            if not re.search(r"\.[a-zA-Z]{1,6}$", t):
                continue
            if t.startswith("/") or t.startswith(("backend/", "frontend/", "app/")) or "/" in t:
                files.append(t)
    return files[:10]


@router.post("/{proposal_id}/prepare-pr")
async def prepare_pr(proposal_id: str, authorization: Optional[str] = Header(None)):
    """Generate a GitHub-friendly commit message + branch suggestion for an
    approved Mode 2 proposal. Does NOT push — admin uses the platform's
    'Save to GitHub' feature with the suggested commit message.

    The commit message uses the `[ora-mode2]` prefix (parallels the existing
    `[auto-heal]` convention) so the deploy workflow can identify it.
    """
    payload = verify_admin(authorization)
    db = _get_db()
    if db is None:
        raise HTTPException(503, "Database not wired")
    doc = await db.ora_dev_actions.find_one({"proposal_id": proposal_id})
    if not doc:
        raise HTTPException(404, f"Proposal {proposal_id} not found")
    if doc.get("sealed_blocked"):
        raise HTTPException(409, "Sealed-blocked proposal — cannot prepare PR")
    if doc.get("status") not in ("approved", "applied"):
        raise HTTPException(
            409,
            f"Status `{doc.get('status')}` — approve the proposal first before preparing a PR",
        )

    request_text = (doc.get("request_text") or "")[:80]
    intent_short = _slugify(request_text or doc.get("proposal_id", ""), 32)
    branch = f"ora-mode2/{proposal_id[:8]}-{intent_short}"
    commit_msg = f"[ora-mode2] {request_text}".strip()
    if len(commit_msg) > 100:
        commit_msg = commit_msg[:97] + "..."

    target_files = _extract_target_files(doc.get("proposal_text") or "")
    pr_body = (
        f"Auto-generated by ORA Mode 2 (Sovereign Brain).\n\n"
        f"**Proposal ID**: `{proposal_id}`\n"
        f"**Approved by**: {doc.get('approved_by') or 'admin'}\n\n"
        f"**Original request**:\n> {doc.get('request_text', '')}\n\n"
        f"**Proposal**:\n```\n{(doc.get('proposal_text') or '')[:3000]}\n```\n"
    )

    await db.ora_dev_actions.update_one(
        {"proposal_id": proposal_id},
        {"$set": {
            "pr_prepared_at": datetime.now(timezone.utc).isoformat(),
            "pr_prepared_by": payload.get("email") or "admin",
            "pr_branch_suggested": branch,
            "pr_commit_message": commit_msg,
        }},
    )

    return {
        "ok": True,
        "proposal_id": proposal_id,
        "branch": branch,
        "commit_message": commit_msg,
        "target_files": target_files,
        "pr_body": pr_body,
        "next_step": (
            "Copy the commit_message, then click 'Save to GitHub' in the chat "
            "input to push. The [ora-mode2] prefix is parsed by the deploy "
            "workflow."
        ),
    }


# ─── iter D-34: bulk approve safe proposals ──────────────────────────
# Watchdog-approved Path B — clear the 1055-proposal backlog with one
# click per SAFE category. A proposal is "safe to bulk-approve" only
# when ALL of the following are true:
#   • status == "pending"
#   • sealed_blocked is not set / False
#   • does NOT touch files matching the danger glob (auth/billing/schema)
#   • diff_size (added + removed lines) <= 50 — anything bigger is a
#     single-click decision, not a sweep.
#
# Caller picks a `kind` filter so they can sweep one bucket at a time
# (e.g. "copy_only" or "css_only") — see _classify_kind below.

import re as _re

_DANGEROUS_PATH_RE = _re.compile(
    r"(auth|login|password|jwt|stripe|payment|invoice|"
    r"migration|schema|\.env|secrets?\.|credentials)",
    _re.IGNORECASE,
)


def _classify_kind(doc: Dict[str, Any]) -> str:
    """Cheap heuristic — what bucket does this proposal fall in?"""
    files = doc.get("files_touched") or doc.get("paths") or []
    if not files and doc.get("diff"):
        files = _re.findall(r"^[+-]{3}\s+[ab]/(\S+)", doc.get("diff", ""), _re.MULTILINE)
    files = [f for f in files if isinstance(f, str)]
    if not files:
        return "unknown"
    if all(f.endswith((".md", ".txt")) for f in files):
        return "docs"
    if all(f.endswith((".css", ".scss")) for f in files):
        return "css_only"
    if all(_DANGEROUS_PATH_RE.search(f) for f in files):
        return "risky_auth_or_billing"
    if any(_DANGEROUS_PATH_RE.search(f) for f in files):
        return "mixed_with_risky"
    if all(f.startswith(("frontend/src/", "app/frontend/src/")) for f in files):
        return "frontend_only"
    if all(f.startswith(("backend/", "app/backend/")) for f in files):
        return "backend_only"
    return "mixed"


def _diff_size(doc: Dict[str, Any]) -> int:
    d = doc.get("diff") or ""
    if not d:
        return int(doc.get("added_lines", 0)) + int(doc.get("removed_lines", 0))
    return sum(1 for line in d.splitlines()
                if line and line[0] in ("+", "-")
                and not line.startswith(("+++", "---")))


_SAFE_KINDS = {"docs", "css_only", "frontend_only", "backend_only"}


@router.get("/buckets")
async def buckets(authorization: Optional[str] = Header(None)) -> Dict[str, Any]:
    """Returns the kind-classified summary of the pending queue so the
    UI can offer category-level bulk approve."""
    verify_admin(authorization)
    db = _get_db()
    if db is None:
        raise HTTPException(503, "Database not wired")
    out: Dict[str, Dict[str, Any]] = {}
    async for doc in db.ora_dev_actions.find(
        {"status": "pending"},
        {"_id": 0, "proposal_id": 1, "sealed_blocked": 1,
         "files_touched": 1, "paths": 1, "diff": 1,
         "added_lines": 1, "removed_lines": 1},
    ).limit(2000):
        kind = _classify_kind(doc)
        size = _diff_size(doc)
        sealed = bool(doc.get("sealed_blocked"))
        bucket = out.setdefault(kind, {
            "kind":   kind,
            "safe":   kind in _SAFE_KINDS,
            "total":  0,
            "sealed": 0,
            "small_diffs": 0,
            "large_diffs": 0,
            "sample_ids": [],
        })
        bucket["total"] += 1
        if sealed:
            bucket["sealed"] += 1
        elif size <= 50:
            bucket["small_diffs"] += 1
        else:
            bucket["large_diffs"] += 1
        if len(bucket["sample_ids"]) < 5:
            bucket["sample_ids"].append(doc.get("proposal_id"))
    return {"ok": True, "buckets": list(out.values())}


@router.post("/bulk-approve")
async def bulk_approve(
    body: Dict[str, Any],
    authorization: Optional[str] = Header(None),
) -> Dict[str, Any]:
    """Bulk-approve every pending proposal in the given `kind` bucket
    that passes the safety guards. Returns counts of approved / skipped
    plus the IDs of the skipped ones so the admin can review them.

    Body:
      { "kind": "css_only" | "docs" | "frontend_only" | "backend_only",
        "max":  100  (optional cap, default 100, hard limit 500) }
    """
    payload = verify_admin(authorization)
    db = _get_db()
    if db is None:
        raise HTTPException(503, "Database not wired")
    kind   = (body or {}).get("kind", "").strip().lower()
    max_n  = min(int((body or {}).get("max", 100)), 500)
    if kind not in _SAFE_KINDS:
        raise HTTPException(400, {
            "code": "kind_not_safe",
            "msg":  f"`{kind}` is not in the bulk-approvable list "
                    f"({sorted(_SAFE_KINDS)}). Use single-click approve.",
        })
    admin_email = payload.get("email") or "admin"
    approved: list[str] = []
    skipped:  list[dict] = []
    cursor = db.ora_dev_actions.find(
        {"status": "pending"},
        {"_id": 0, "proposal_id": 1, "sealed_blocked": 1,
         "files_touched": 1, "paths": 1, "diff": 1,
         "added_lines": 1, "removed_lines": 1},
    ).limit(max_n * 3)  # over-fetch since most may filter out
    async for doc in cursor:
        if len(approved) >= max_n:
            break
        pid = doc.get("proposal_id")
        # Safety gate
        if _classify_kind(doc) != kind:
            continue
        if doc.get("sealed_blocked"):
            skipped.append({"proposal_id": pid, "why": "sealed_blocked"})
            continue
        if _diff_size(doc) > 50:
            skipped.append({"proposal_id": pid, "why": "diff_too_large"})
            continue
        # Approve.
        try:
            await _transition(
                pid,
                new_status="approved",
                admin_email=admin_email,
                allowed_from={"pending"},
                extra={"approved_via": "bulk", "approved_kind": kind},
            )
            approved.append(pid)
        except HTTPException as e:
            skipped.append({"proposal_id": pid, "why": f"http_{e.status_code}"})
    return {
        "ok":         True,
        "kind":       kind,
        "approved":   len(approved),
        "skipped":    len(skipped),
        "approved_ids": approved[:20],
        "skipped_sample": skipped[:20],
        "approved_via": "bulk",
        "approved_by":  admin_email,
    }

