"""
ORA Dev Actions Router (iter 281.2 — Phase 2.2)
================================================
Admin-gated CRUD over `db.ora_dev_actions` — the queue of code-change
proposals generated by ORA's Mode 2 (Software Engineer) brain.

Contract:
  - GET  /api/admin/ora-dev/pending           list pending proposals
  - GET  /api/admin/ora-dev/list?status=...   filtered list (last 100)
  - GET  /api/admin/ora-dev/stats             counts by status
  - POST /api/admin/ora-dev/{id}/approve      mark approved
  - POST /api/admin/ora-dev/{id}/reject       mark rejected
  - POST /api/admin/ora-dev/{id}/applied      mark applied (admin did it)
  - POST /api/admin/ora-dev/{id}/rollback     mark rolled back
  - GET  /api/admin/ora-dev/health            public liveness probe

Hard rule: ORA NEVER auto-applies code. Status transitions only.
Admin still does the actual file editing manually (or uses the
existing pending_code_fixes pipeline for tier-3 auto-heal).
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any, Dict, Optional

from fastapi import APIRouter, Header, HTTPException, Query

from utils.admin_guard import verify_admin

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/admin/ora-dev", tags=["ORA Dev Console"])

_db = None
_VALID_STATUSES = {"pending", "approved", "rejected", "applied", "rolled_back"}


def set_db(db):
    global _db
    _db = db


def _get_db():
    return _db


def _serialize(doc: Dict[str, Any]) -> Dict[str, Any]:
    """Strip MongoDB _id before JSON return."""
    if not doc:
        return {}
    out = {k: v for k, v in doc.items() if k != "_id"}
    return out


@router.get("/health")
async def health():
    db = _get_db()
    return {"ok": True, "db_wired": db is not None}


@router.get("/pending")
async def list_pending(authorization: Optional[str] = Header(None)):
    verify_admin(authorization)
    db = _get_db()
    if db is None:
        raise HTTPException(503, "Database not wired")
    cursor = (
        db.ora_dev_actions
        .find({"status": "pending"})
        .sort("created_at", -1)
        .limit(50)
    )
    items = [_serialize(d) async for d in cursor]
    return {"ok": True, "count": len(items), "items": items}


@router.get("/list")
async def list_actions(
    authorization: Optional[str] = Header(None),
    status: Optional[str] = Query(None),
    limit: int = Query(50, ge=1, le=200),
):
    verify_admin(authorization)
    db = _get_db()
    if db is None:
        raise HTTPException(503, "Database not wired")
    q: Dict[str, Any] = {}
    if status:
        if status not in _VALID_STATUSES:
            raise HTTPException(400, f"Invalid status (allowed: {sorted(_VALID_STATUSES)})")
        q["status"] = status
    cursor = db.ora_dev_actions.find(q).sort("created_at", -1).limit(limit)
    items = [_serialize(d) async for d in cursor]
    return {"ok": True, "count": len(items), "items": items}


@router.get("/stats")
async def stats(authorization: Optional[str] = Header(None)):
    verify_admin(authorization)
    db = _get_db()
    if db is None:
        raise HTTPException(503, "Database not wired")
    counts = {s: 0 for s in _VALID_STATUSES}
    pipeline = [{"$group": {"_id": "$status", "n": {"$sum": 1}}}]
    async for row in db.ora_dev_actions.aggregate(pipeline):
        s = row.get("_id") or "pending"
        counts[s] = int(row.get("n", 0))
    counts["total"] = sum(counts.values())
    return {"ok": True, **counts}


async def _transition(
    proposal_id: str,
    *,
    new_status: str,
    admin_email: Optional[str],
    extra: Optional[Dict[str, Any]] = None,
    allowed_from: Optional[set] = None,
) -> Dict[str, Any]:
    db = _get_db()
    if db is None:
        raise HTTPException(503, "Database not wired")
    doc = await db.ora_dev_actions.find_one({"proposal_id": proposal_id})
    if not doc:
        raise HTTPException(404, f"Proposal {proposal_id} not found")
    if allowed_from and doc.get("status") not in allowed_from:
        raise HTTPException(
            409,
            f"Cannot transition from `{doc.get('status')}` to `{new_status}`",
        )
    update = {
        "status": new_status,
        f"{new_status}_at": datetime.now(timezone.utc).isoformat(),
        f"{new_status}_by": admin_email or "admin",
    }
    if new_status == "approved":
        update["approved_at"] = update[f"{new_status}_at"]
        update["approved_by"] = admin_email or "admin"
    if extra:
        update.update(extra)
    await db.ora_dev_actions.update_one(
        {"proposal_id": proposal_id}, {"$set": update}
    )
    refreshed = await db.ora_dev_actions.find_one({"proposal_id": proposal_id})
    return _serialize(refreshed or {})


@router.post("/{proposal_id}/approve")
async def approve(proposal_id: str, authorization: Optional[str] = Header(None)):
    payload = verify_admin(authorization)
    if (payload.get("sealed_blocked") or False) is True:
        # cosmetic: not relevant on token, kept for symmetry
        pass
    doc = await _transition(
        proposal_id,
        new_status="approved",
        admin_email=payload.get("email"),
        allowed_from={"pending"},
    )
    if doc.get("sealed_blocked"):
        raise HTTPException(409, "Proposal touches sealed file(s) — cannot approve")
    # iter 282e — browser-action proposals auto-execute on approve.
    # Other proposal kinds (code change, ORA action, etc.) stay at
    # "approved" and wait for their existing applier paths.
    if doc.get("kind") == "browser_action":
        try:
            from services.browser_agent_service import execute_approved_action
            exec_result = await execute_approved_action(proposal_id)
            doc["execution_result"] = exec_result
        except Exception as e:
            doc["execution_result"] = {"ok": False, "error": str(e)[:200]}
    return {"ok": True, "proposal": doc}


@router.post("/{proposal_id}/reject")
async def reject(proposal_id: str, authorization: Optional[str] = Header(None)):
    payload = verify_admin(authorization)
    doc = await _transition(
        proposal_id,
        new_status="rejected",
        admin_email=payload.get("email"),
        allowed_from={"pending", "approved"},
    )
    return {"ok": True, "proposal": doc}


@router.post("/{proposal_id}/applied")
async def mark_applied(proposal_id: str, authorization: Optional[str] = Header(None)):
    payload = verify_admin(authorization)
    doc = await _transition(
        proposal_id,
        new_status="applied",
        admin_email=payload.get("email"),
        allowed_from={"approved"},
    )
    return {"ok": True, "proposal": doc}


@router.post("/{proposal_id}/rollback")
async def rollback(proposal_id: str, authorization: Optional[str] = Header(None)):
    payload = verify_admin(authorization)
    doc = await _transition(
        proposal_id,
        new_status="rolled_back",
        admin_email=payload.get("email"),
        allowed_from={"applied", "approved"},
    )
    return {"ok": True, "proposal": doc}


# ─── iter 281.3 — Apply via PR (Phase 2.3 add-on) ──────────────────
def _slugify(s: str, n: int = 32) -> str:
    import re
    s = re.sub(r"[^a-zA-Z0-9]+", "-", (s or "").lower()).strip("-")
    return s[:n] or "ora-mode2"


def _extract_target_files(proposal_text: str) -> list:
    """Best-effort parse of TARGET FILE(S) section from Mode 2 prompt output."""
    import re
    lines = (proposal_text or "").splitlines()
    files = []
    in_target = False
    for ln in lines:
        if "TARGET FILE" in ln.upper():
            in_target = True
            continue
        if in_target:
            t = ln.strip().strip("`").strip("*").strip()
            if not t or t.startswith("#"):
                continue
            if t.upper().startswith(("INTENT", "REASONING", "SUGGESTED", "RISKS", "TEST")):
                break
            # Strict: must look like a path — no spaces, has extension,
            # short enough to be a file path (not a sentence).
            if " " in t or len(t) > 200:
                continue
            if not re.search(r"\.[a-zA-Z]{1,6}$", t):
                continue
            if t.startswith("/") or t.startswith(("backend/", "frontend/", "app/")) or "/" in t:
                files.append(t)
    return files[:10]


@router.post("/{proposal_id}/prepare-pr")
async def prepare_pr(proposal_id: str, authorization: Optional[str] = Header(None)):
    """Generate a GitHub-friendly commit message + branch suggestion for an
    approved Mode 2 proposal. Does NOT push — admin uses the platform's
    'Save to GitHub' feature with the suggested commit message.

    The commit message uses the `[ora-mode2]` prefix (parallels the existing
    `[auto-heal]` convention) so the deploy workflow can identify it.
    """
    payload = verify_admin(authorization)
    db = _get_db()
    if db is None:
        raise HTTPException(503, "Database not wired")
    doc = await db.ora_dev_actions.find_one({"proposal_id": proposal_id})
    if not doc:
        raise HTTPException(404, f"Proposal {proposal_id} not found")
    if doc.get("sealed_blocked"):
        raise HTTPException(409, "Sealed-blocked proposal — cannot prepare PR")
    if doc.get("status") not in ("approved", "applied"):
        raise HTTPException(
            409,
            f"Status `{doc.get('status')}` — approve the proposal first before preparing a PR",
        )

    request_text = (doc.get("request_text") or "")[:80]
    intent_short = _slugify(request_text or doc.get("proposal_id", ""), 32)
    branch = f"ora-mode2/{proposal_id[:8]}-{intent_short}"
    commit_msg = f"[ora-mode2] {request_text}".strip()
    if len(commit_msg) > 100:
        commit_msg = commit_msg[:97] + "..."

    target_files = _extract_target_files(doc.get("proposal_text") or "")
    pr_body = (
        f"Auto-generated by ORA Mode 2 (Sovereign Brain).\n\n"
        f"**Proposal ID**: `{proposal_id}`\n"
        f"**Approved by**: {doc.get('approved_by') or 'admin'}\n\n"
        f"**Original request**:\n> {doc.get('request_text', '')}\n\n"
        f"**Proposal**:\n```\n{(doc.get('proposal_text') or '')[:3000]}\n```\n"
    )

    await db.ora_dev_actions.update_one(
        {"proposal_id": proposal_id},
        {"$set": {
            "pr_prepared_at": datetime.now(timezone.utc).isoformat(),
            "pr_prepared_by": payload.get("email") or "admin",
            "pr_branch_suggested": branch,
            "pr_commit_message": commit_msg,
        }},
    )

    return {
        "ok": True,
        "proposal_id": proposal_id,
        "branch": branch,
        "commit_message": commit_msg,
        "target_files": target_files,
        "pr_body": pr_body,
        "next_step": (
            "Copy the commit_message, then click 'Save to GitHub' in the chat "
            "input to push. The [ora-mode2] prefix is parsed by the deploy "
            "workflow."
        ),
    }
