"""
AUREM Document Skills — DOCX + PPTX + PDF Generation
=====================================================
Inspired by Anthropic official document-skills.
3 document types, all brand-consistent with AUREM aesthetic.

DOCX — Client proposals, welcome packages, outreach documents
PPTX — Monthly Shopify health reports, campaign performance decks
PDF  — Formal reports, contracts, summaries (via reportlab)

CRM Auto-Triggers:
  New client → welcome proposal DOCX
  Campaign completed → performance report PDF
  Forensic Miner lead → outreach proposal DOCX
  Monthly → Shopify health deck PPTX
"""
import os
import io
import secrets
import logging
from datetime import datetime, timezone
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)

_db = None


def set_db(database):
    global _db
    _db = database


def _get_db():
    global _db
    if _db is not None:
        return _db
    try:
        import server
        if hasattr(server, "db") and server.db is not None:
            _db = server.db
    except Exception:
        pass
    return _db


DOC_DIR = "/app/backend/uploads/documents"
os.makedirs(DOC_DIR, exist_ok=True)

AUREM_COLORS = {"primary": "2D2A2E", "accent": "D4AF37", "copper": "B87333", "white": "FFFFFF", "light_gray": "F5F5F5"}


# ═══════════════════════════════════════════════════════════════
# DOCX GENERATION — Proposals, Welcome Packages, Outreach
# ═══════════════════════════════════════════════════════════════

async def generate_docx(
    title: str,
    sections: List[Dict],
    doc_type: str = "proposal",
    metadata: Dict = None,
    tenant_id: str = "aurem_platform",
) -> Dict:
    """
    Generate branded DOCX document.
    sections: [{"heading": "...", "content": "...", "style": "normal|bullet|table"}]
    """
    from docx import Document
    from docx.shared import Inches, Pt, Cm, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.section import WD_ORIENT

    doc = Document()

    # Page setup
    section = doc.sections[0]
    section.top_margin = Cm(2)
    section.bottom_margin = Cm(2)
    section.left_margin = Cm(2.5)
    section.right_margin = Cm(2.5)

    # Title
    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run = title_p.add_run(title)
    run.font.size = Pt(28)
    run.font.color.rgb = RGBColor(0x2D, 0x2A, 0x2E)
    run.font.bold = True
    run.font.name = "Calibri"

    # Accent line
    line_p = doc.add_paragraph()
    line_run = line_p.add_run("━" * 60)
    line_run.font.color.rgb = RGBColor(0xD4, 0xAF, 0x37)
    line_run.font.size = Pt(8)

    # Metadata
    if metadata:
        meta_p = doc.add_paragraph()
        meta_p.alignment = WD_ALIGN_PARAGRAPH.LEFT
        for k, v in metadata.items():
            run = meta_p.add_run(f"{k}: {v}\n")
            run.font.size = Pt(10)
            run.font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    doc.add_paragraph()  # spacer

    # Sections
    for sec in sections:
        heading = sec.get("heading", "")
        content = sec.get("content", "")
        style = sec.get("style", "normal")

        if heading:
            h = doc.add_heading(heading, level=2)
            for run in h.runs:
                run.font.color.rgb = RGBColor(0x2D, 0x2A, 0x2E)
                run.font.name = "Calibri"

        if style == "bullet" and isinstance(content, list):
            for item in content:
                p = doc.add_paragraph(str(item), style="List Bullet")
                for run in p.runs:
                    run.font.size = Pt(11)
        elif style == "table" and isinstance(content, list) and content:
            cols = list(content[0].keys()) if isinstance(content[0], dict) else ["Item"]
            table = doc.add_table(rows=1, cols=len(cols))
            table.style = "Light Grid Accent 1"
            for i, col in enumerate(cols):
                table.rows[0].cells[i].text = str(col).title()
            for row_data in content:
                row = table.add_row()
                if isinstance(row_data, dict):
                    for i, col in enumerate(cols):
                        row.cells[i].text = str(row_data.get(col, ""))
                else:
                    row.cells[0].text = str(row_data)
        else:
            p = doc.add_paragraph(str(content))
            for run in p.runs:
                run.font.size = Pt(11)
                run.font.name = "Calibri"

    # Footer
    doc.add_paragraph()
    footer_p = doc.add_paragraph()
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer_p.add_run("Generated by AUREM AI — Sovereign Business Automation")
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(0xD4, 0xAF, 0x37)
    run.font.italic = True

    # Save
    doc_id = f"doc_{secrets.token_hex(6)}"
    fpath = f"{DOC_DIR}/{doc_id}.docx"
    doc.save(fpath)

    db = _get_db()
    if db:
        await db.generated_documents.insert_one({
            "doc_id": doc_id, "type": doc_type, "format": "docx", "title": title,
            "tenant_id": tenant_id, "file_path": fpath, "sections": len(sections),
            "created_at": datetime.now(timezone.utc).isoformat(),
        })

    return {"doc_id": doc_id, "format": "docx", "file_path": fpath, "title": title, "generated": True}


# ═══════════════════════════════════════════════════════════════
# PPTX GENERATION — Health Reports, Campaign Decks
# ═══════════════════════════════════════════════════════════════

async def generate_pptx(
    title: str,
    slides: List[Dict],
    doc_type: str = "report",
    tenant_id: str = "aurem_platform",
) -> Dict:
    """
    Generate branded PPTX presentation.
    slides: [{"title": "...", "content": "...", "layout": "title|content|two_col|metrics"}]
    """
    from pptx import Presentation
    from pptx.util import Inches, Pt, Emu
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # Title Slide
    slide_layout = prs.slide_layouts[6]  # blank
    slide = prs.slides.add_slide(slide_layout)

    # Background
    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = RGBColor(0x2D, 0x2A, 0x2E)

    # Title text
    txBox = slide.shapes.add_textbox(Inches(1), Inches(2), Inches(11), Inches(2))
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    p.text = title
    p.font.size = Pt(44)
    p.font.color.rgb = RGBColor(0xF5, 0xF5, 0xF5)
    p.font.bold = True
    p.alignment = PP_ALIGN.LEFT

    # Accent line
    line = slide.shapes.add_shape(1, Inches(1), Inches(4.2), Inches(3), Emu(36000))
    line.fill.solid()
    line.fill.fore_color.rgb = RGBColor(0xD4, 0xAF, 0x37)
    line.line.fill.background()

    # Subtitle
    txBox2 = slide.shapes.add_textbox(Inches(1), Inches(4.5), Inches(8), Inches(1))
    tf2 = txBox2.text_frame
    p2 = tf2.paragraphs[0]
    p2.text = f"Generated by AUREM AI — {datetime.now(timezone.utc).strftime('%B %Y')}"
    p2.font.size = Pt(16)
    p2.font.color.rgb = RGBColor(0xD4, 0xAF, 0x37)

    # Content slides
    for sl in slides:
        slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank
        bg = slide.background
        fill = bg.fill
        fill.solid()
        fill.fore_color.rgb = RGBColor(0xF5, 0xF5, 0xF5)

        # Slide title
        txBox = slide.shapes.add_textbox(Inches(0.8), Inches(0.4), Inches(11), Inches(1))
        tf = txBox.text_frame
        p = tf.paragraphs[0]
        p.text = sl.get("title", "")
        p.font.size = Pt(28)
        p.font.color.rgb = RGBColor(0x2D, 0x2A, 0x2E)
        p.font.bold = True

        # Content
        content = sl.get("content", "")
        if isinstance(content, list):
            content = "\n".join(f"• {item}" for item in content)

        txBox2 = slide.shapes.add_textbox(Inches(0.8), Inches(1.6), Inches(11), Inches(5))
        tf2 = txBox2.text_frame
        tf2.word_wrap = True
        p2 = tf2.paragraphs[0]
        p2.text = str(content)
        p2.font.size = Pt(16)
        p2.font.color.rgb = RGBColor(0x44, 0x44, 0x44)

    # Save
    doc_id = f"pptx_{secrets.token_hex(6)}"
    fpath = f"{DOC_DIR}/{doc_id}.pptx"
    prs.save(fpath)

    db = _get_db()
    if db:
        await db.generated_documents.insert_one({
            "doc_id": doc_id, "type": doc_type, "format": "pptx", "title": title,
            "tenant_id": tenant_id, "file_path": fpath, "slides": len(slides) + 1,
            "created_at": datetime.now(timezone.utc).isoformat(),
        })

    return {"doc_id": doc_id, "format": "pptx", "file_path": fpath, "title": title, "slides": len(slides) + 1, "generated": True}


# ═══════════════════════════════════════════════════════════════
# PDF GENERATION — Formal Reports
# ═══════════════════════════════════════════════════════════════

async def generate_pdf(
    title: str,
    sections: List[Dict],
    doc_type: str = "report",
    tenant_id: str = "aurem_platform",
) -> Dict:
    """Generate branded PDF report via reportlab."""
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib.colors import HexColor
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

    doc_id = f"pdf_{secrets.token_hex(6)}"
    fpath = f"{DOC_DIR}/{doc_id}.pdf"

    doc = SimpleDocTemplate(fpath, pagesize=letter, topMargin=0.75*inch, bottomMargin=0.75*inch)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("AuremTitle", parent=styles["Title"], fontSize=24, textColor=HexColor("#2D2A2E"), spaceAfter=6)
    heading_style = ParagraphStyle("AuremH2", parent=styles["Heading2"], fontSize=16, textColor=HexColor("#2D2A2E"), spaceBefore=16, spaceAfter=8)
    body_style = ParagraphStyle("AuremBody", parent=styles["Normal"], fontSize=11, textColor=HexColor("#333333"), spaceAfter=8, leading=16)
    accent_style = ParagraphStyle("AuremAccent", parent=styles["Normal"], fontSize=9, textColor=HexColor("#D4AF37"), spaceAfter=4)

    elements = []
    elements.append(Paragraph(title, title_style))
    elements.append(Paragraph("━" * 80, accent_style))
    elements.append(Spacer(1, 12))

    for sec in sections:
        heading = sec.get("heading", "")
        content = sec.get("content", "")
        style = sec.get("style", "normal")

        if heading:
            elements.append(Paragraph(heading, heading_style))

        if style == "bullet" and isinstance(content, list):
            for item in content:
                elements.append(Paragraph(f"• {item}", body_style))
        elif style == "table" and isinstance(content, list) and content:
            if isinstance(content[0], dict):
                cols = list(content[0].keys())
                data = [cols] + [[str(row.get(c, "")) for c in cols] for row in content]
            else:
                data = [[str(c)] for c in content]
            t = Table(data)
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), HexColor("#2D2A2E")),
                ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#FFFFFF")),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#CCCCCC")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#FFFFFF"), HexColor("#F9F9F9")]),
            ]))
            elements.append(t)
        else:
            elements.append(Paragraph(str(content), body_style))

        elements.append(Spacer(1, 8))

    elements.append(Spacer(1, 24))
    elements.append(Paragraph("Generated by AUREM AI — Sovereign Business Automation", accent_style))

    doc.build(elements)

    db = _get_db()
    if db:
        await db.generated_documents.insert_one({
            "doc_id": doc_id, "type": doc_type, "format": "pdf", "title": title,
            "tenant_id": tenant_id, "file_path": fpath, "sections": len(sections),
            "created_at": datetime.now(timezone.utc).isoformat(),
        })

    return {"doc_id": doc_id, "format": "pdf", "file_path": fpath, "title": title, "generated": True}


# ═══════════════════════════════════════════════════════════════
# CRM AUTO-TRIGGERS
# ═══════════════════════════════════════════════════════════════

async def on_new_client_proposal(client_name: str, business: str, services: List[str] = None, tenant_id: str = "aurem_platform") -> Dict:
    """CRM: New client onboarded → auto-generate welcome proposal DOCX."""
    services = services or ["SEO Auto-Fix", "Content Engine", "Omnichannel Outreach"]
    return await generate_docx(
        title=f"Welcome Proposal — {client_name}",
        doc_type="welcome_proposal",
        metadata={"Prepared for": client_name, "Business": business, "Date": datetime.now(timezone.utc).strftime("%B %d, %Y")},
        sections=[
            {"heading": "Executive Summary", "content": f"AUREM AI is pleased to present this proposal for {business}. Our sovereign AI platform will automate your marketing, SEO, and customer engagement operations."},
            {"heading": "Proposed Services", "content": services, "style": "bullet"},
            {"heading": "Why AUREM?", "content": ["Zero monthly AI costs — sovereign infrastructure", "41 MCP tools for comprehensive automation", "24/7 autonomous operation — no human intervention needed", "Brand-consistent content across all channels"], "style": "bullet"},
            {"heading": "Pricing", "content": [{"Plan": "Starter", "Price": "$97/mo", "Posts": "50/mo", "Images": "50/mo"}, {"Plan": "Growth", "Price": "$297/mo", "Posts": "500/mo", "Images": "500/mo"}, {"Plan": "Enterprise", "Price": "$997/mo", "Posts": "Unlimited", "Images": "Unlimited"}], "style": "table"},
            {"heading": "Next Steps", "content": "Schedule a 15-minute demo call to see AUREM in action. We'll set up your account within 24 hours of signing."},
        ],
        tenant_id=tenant_id,
    )


async def on_campaign_complete_report(campaign_name: str, metrics: Dict = None, tenant_id: str = "aurem_platform") -> Dict:
    """CRM: Campaign completed → auto-generate performance report PDF."""
    m = metrics or {"posts_published": 15, "impressions": 12500, "clicks": 890, "conversions": 45, "roi": "340%"}
    return await generate_pdf(
        title=f"Campaign Report — {campaign_name}",
        doc_type="campaign_report",
        sections=[
            {"heading": "Campaign Overview", "content": f"Performance summary for '{campaign_name}' campaign generated by AUREM Content Engine."},
            {"heading": "Key Metrics", "content": [{"Metric": k.replace("_", " ").title(), "Value": str(v)} for k, v in m.items()], "style": "table"},
            {"heading": "AI-Generated Insights", "content": "Campaign performed above industry benchmarks. Recommended: increase posting frequency by 20% and expand to additional social channels for next campaign."},
        ],
        tenant_id=tenant_id,
    )


async def on_forensic_miner_lead(lead_domain: str, health_score: int, issues: List[str] = None, tenant_id: str = "aurem_platform") -> Dict:
    """CRM: Forensic Miner lead found → auto-generate outreach proposal DOCX."""
    issues = issues or ["Missing meta descriptions", "No JSON-LD schema", "Images without alt-text"]
    return await generate_docx(
        title=f"Free SEO Audit — {lead_domain}",
        doc_type="outreach_proposal",
        metadata={"Website": lead_domain, "Health Score": f"{health_score}/100", "Generated": datetime.now(timezone.utc).strftime("%B %d, %Y")},
        sections=[
            {"heading": "Your Store Needs Attention", "content": f"Our AI scanned {lead_domain} and found {len(issues)} critical SEO issues affecting your search visibility and sales."},
            {"heading": "Issues Found", "content": issues, "style": "bullet"},
            {"heading": "What We Fix (FREE)", "content": ["Alt-text for all product images", "Meta descriptions for every page", "JSON-LD structured data markup", "Page title optimization"], "style": "bullet"},
            {"heading": "Why It's Free", "content": "SEO fixes are always free with AUREM. We only charge $2 per recovered abandoned cart sale — you only pay when we make you money."},
            {"heading": "Get Started", "content": "Reply to this email or visit aurem.live to install our free Shopify app. Your store will be optimized within 24 hours."},
        ],
        tenant_id=tenant_id,
    )


async def generate_health_deck(shop: str, metrics: Dict = None, tenant_id: str = "aurem_platform") -> Dict:
    """Monthly Shopify health report as PPTX presentation for merchant."""
    m = metrics or {"products": 45, "avg_health_score": 72, "seo_fixes_applied": 128, "carts_recovered": 12, "revenue_recovered": "$24"}
    return await generate_pptx(
        title=f"Monthly Health Report — {shop}",
        doc_type="health_report",
        slides=[
            {"title": "Store Health Overview", "content": [f"Products: {m['products']}", f"Average SEO Health: {m['avg_health_score']}/100", f"Fixes Applied This Month: {m['seo_fixes_applied']}"]},
            {"title": "Revenue Impact", "content": [f"Abandoned Carts Recovered: {m['carts_recovered']}", f"Revenue Recovered: {m['revenue_recovered']}", "SEO Fixes: FREE (acquisition hook)", "Cart Recovery: $2/recovered sale"]},
            {"title": "Recommendations", "content": ["Increase product descriptions to 150+ words", "Add schema markup to all collection pages", "Enable automated social posting via Content Engine", "Schedule weekly Pulse scans for continuous improvement"]},
        ],
        tenant_id=tenant_id,
    )


async def get_document_history(tenant_id: str = None, limit: int = 20) -> List[Dict]:
    db = _get_db()
    if not db:
        return []
    q = {"tenant_id": tenant_id} if tenant_id else {}
    return await db.generated_documents.find(q, {"_id": 0}).sort("created_at", -1).limit(limit).to_list(limit)
