"""
Monday Morning Brief — scheduler (iter 311)
============================================
Every Monday 7 AM Toronto time, pull the last 3-5 intelligence scans,
re-run the council synth on each, merge into one brief, and notify TJ
via WhatsApp + Email (Resend).

Public:
  await maybe_send_monday_brief(db) -> dict   (run by scheduler every hour;
                                                no-op if not Mon 7-8 AM TO)
  await send_monday_brief_now(db, count=5) -> dict   (admin-trigger force send)
"""
from __future__ import annotations

import logging
import os
from datetime import datetime, timezone, timedelta
from typing import Any, Dict, List

import httpx

logger = logging.getLogger(__name__)

FOUNDER_WHATSAPP = os.environ.get("FOUNDER_WHATSAPP", "+16134000000")
FOUNDER_EMAIL = os.environ.get("FOUNDER_EMAIL", "teji.ss1986@gmail.com")
TZ_OFFSET_HOURS = -4  # Toronto EDT (handles EST too, brief tolerates 1h drift)


def _toronto_now() -> datetime:
    return datetime.now(timezone.utc) + timedelta(hours=TZ_OFFSET_HOURS)


def _is_monday_7am_window() -> bool:
    n = _toronto_now()
    return n.weekday() == 0 and n.hour == 7


async def _build_brief_text(scans: List[Dict[str, Any]]) -> str:
    today = _toronto_now().strftime("%Y-%m-%d")
    lines = [f"📊 *AUREM Monday Brief* — {today}", ""]
    if not scans:
        lines.append("No intelligence scans saved this week. Fire the MEGA "
                     "Console to seed Monday's brief.")
        return "\n".join(lines)

    # Highest confidence BUILD = priority
    builds = [s for s in scans if s.get("council", {}).get("verdict") == "BUILD"]
    builds.sort(key=lambda s: s.get("council", {}).get("confidence", 0), reverse=True)

    for i, s in enumerate(scans, 1):
        c = s.get("council", {})
        topic = (s.get("inputs", {}) or {}).get("topic", "Untitled")[:80]
        verdict = c.get("verdict", "—")
        risk = c.get("risk", "—")
        # First move: extract from raw_markdown
        raw = c.get("raw_markdown", "") or ""
        first_move = ""
        for line in raw.split("\n"):
            if "FIRST MOVE" in line.upper():
                first_move = line.split(":", 1)[-1].strip(" *_")[:160]
                break
        lines.append(f"*{i}.* {topic}")
        lines.append(f"   Verdict: *{verdict}* · Risk: {risk}/10 · "
                     f"Conf: {c.get('confidence','—')}%")
        if first_move:
            lines.append(f"   Next: {first_move}")
        lines.append("")

    if builds:
        top = builds[0]
        priority_topic = (top.get("inputs", {}) or {}).get("topic", "")[:80]
        lines.append(f"🎯 *This week's priority:* {priority_topic}")
    return "\n".join(lines)


async def _send_email(subject: str, html: str) -> bool:
    api_key = os.environ.get("RESEND_API_KEY", "")
    from_addr = os.environ.get("RESEND_FROM_EMAIL", "ORA <ora@aurem.live>")
    if not api_key:
        return False
    try:
        async with httpx.AsyncClient(timeout=15) as c:
            r = await c.post(
                "https://api.resend.com/emails",
                headers={"authorization": f"Bearer {api_key}",
                          "content-type": "application/json"},
                json={"from": from_addr, "to": [FOUNDER_EMAIL],
                       "subject": subject, "html": html},
            )
            return r.status_code < 300
    except Exception as e:
        logger.warning(f"[monday-brief] email failed: {e}")
        return False


async def _send_whatsapp(text: str) -> bool:
    try:
        from routers.whatsapp_alerts import send_whatsapp
        out = await send_whatsapp(FOUNDER_WHATSAPP, text)
        return bool(out and out.get("ok"))
    except Exception as e:
        logger.warning(f"[monday-brief] wa failed: {e}")
        return False


async def send_monday_brief_now(db, count: int = 5) -> Dict[str, Any]:
    """Force-send brief regardless of time. Admin trigger."""
    cutoff = (datetime.now(timezone.utc) - timedelta(days=14)).isoformat()
    scans = await db.intelligence_scans.find(
        {"status": "done", "ts": {"$gte": cutoff}},
        {"_id": 0, "lenses": 0},
    ).sort("ts", -1).limit(count).to_list(count)

    text = await _build_brief_text(scans)
    html = (
        "<div style='font-family:Georgia,serif;max-width:600px'>"
        "<h2 style='color:#8a6d1c'>AUREM Monday Brief</h2>"
        f"<pre style='white-space:pre-wrap;background:#faf6e8;padding:16px;"
        f"border-left:3px solid #C9A227'>{text}</pre>"
        "<p style='font-size:11px;color:#888'>Generated by ORA · "
        "<a href='https://aurem.live/admin/console'>Founders Console</a></p>"
        "</div>"
    )

    email_ok = await _send_email(f"AUREM Monday Brief — {len(scans)} scans", html)
    wa_ok = await _send_whatsapp(text)

    record = {
        "ts": datetime.now(timezone.utc).isoformat(),
        "scan_count": len(scans),
        "scan_ids": [s.get("scan_id") for s in scans],
        "email_ok": email_ok, "whatsapp_ok": wa_ok,
        "preview": text[:400],
    }
    try:
        await db.monday_briefs.insert_one(dict(record))
    except Exception:
        pass
    record.pop("_id", None)
    return record


async def maybe_send_monday_brief(db) -> Dict[str, Any]:
    """Hourly tick — sends only during Mon 7-8 AM Toronto window, once/week."""
    if not _is_monday_7am_window():
        return {"ok": True, "skipped": "not_monday_7am_window"}

    # Idempotency: skip if already sent in last 24 h
    yday = (datetime.now(timezone.utc) - timedelta(hours=22)).isoformat()
    existing = await db.monday_briefs.find_one(
        {"ts": {"$gte": yday}}, {"_id": 0, "ts": 1},
    )
    if existing:
        return {"ok": True, "skipped": "already_sent_today",
                "last_ts": existing.get("ts")}

    return await send_monday_brief_now(db, count=5)
