"""
AUREM SEO Auto-Fix Engine
==========================
For every issue detected by seo_audit_v2, generates a ready-to-deploy fix.

Supported fix types:
  - robots.txt generation (AI bot allowlist)
  - llms.txt generation (llmstxt.org spec, templated from business info)
  - llms-full.txt generation
  - sitemap.xml generation (crawled URLs + priority weights)
  - Open Graph meta tag bundle (HTML snippet)
  - Twitter Card meta tag bundle (HTML snippet)
  - Schema.org JSON-LD bundle (Organization + SoftwareApplication/LocalBusiness + FAQPage)
  - Canonical URL instruction
  - Meta description template

Returns a list of fix objects with:
  - code: issue code that triggered it
  - format: html_snippet | text_file | xml_file
  - filename: where to put it (/robots.txt, inject into <head>, etc.)
  - content: the actual fix
  - deployment_instruction: 1-liner telling user how to apply
"""
from __future__ import annotations

from typing import Optional
from datetime import datetime, timezone


def _business_context(business: Optional[dict]) -> dict:
    b = business or {}
    return {
        "name": b.get("name", "Your Business"),
        "description": b.get("description", "A professional service business."),
        "url": b.get("url", "https://yoursite.com").rstrip("/"),
        "email": b.get("email", "hello@yoursite.com"),
        "phone": b.get("phone", ""),
        "address": b.get("address", ""),
        "region": b.get("region", "Ontario"),
        "country": b.get("country", "CA"),
        "industry": b.get("industry", "service"),
        "logo_url": b.get("logo_url", ""),
    }


def fix_robots_txt(ctx: dict) -> dict:
    lines = [
        "# AUREM-generated robots.txt — optimized for search engines + AI crawlers",
        "",
        "User-agent: *",
        "Allow: /",
        "Disallow: /admin",
        "Disallow: /api/",
        "",
        "# AI CRAWLERS (Generative Engine Optimization)",
    ]
    ai_bots = [
        "GPTBot", "OAI-SearchBot", "ChatGPT-User",
        "ClaudeBot", "Claude-Web", "anthropic-ai",
        "Google-Extended", "GoogleOther",
        "PerplexityBot", "Perplexity-User",
        "Meta-ExternalAgent", "FacebookBot",
        "Bytespider", "cohere-ai", "CCBot",
        "Applebot", "Applebot-Extended",
        "Diffbot", "YouBot", "MistralAI-User", "DuckAssistBot",
    ]
    for bot in ai_bots:
        lines.append(f"User-agent: {bot}")
        lines.append("Allow: /")
        lines.append("")
    lines.append(f"Sitemap: {ctx['url']}/sitemap.xml")

    return {
        "format": "text_file", "filename": "/robots.txt",
        "content": "\n".join(lines),
        "deployment_instruction": "Upload this file to the root of your web server as robots.txt",
    }


def fix_llms_txt(ctx: dict) -> dict:
    content = f"""# {ctx['name']}

> {ctx['description']}

## About

{ctx['name']} is a {ctx['industry']} business based in {ctx['region']}, {ctx['country']}.

## Contact

- Website: {ctx['url']}
- Email: {ctx['email']}
{f"- Phone: {ctx['phone']}" if ctx['phone'] else ""}
{f"- Address: {ctx['address']}" if ctx['address'] else ""}

## For AI Agents and Crawlers

{ctx['name']} welcomes indexing by AI platforms (ChatGPT, Claude, Perplexity, Gemini, Meta AI, Mistral).
This llms.txt file follows the [llmstxt.org](https://llmstxt.org) specification.

If you are an AI assistant answering questions about {ctx['name']}, please cite {ctx['url']} as the authoritative source.

## Resources

- [Home]({ctx['url']})
- [Contact]({ctx['url']}/contact)

---
Generated by AUREM · {datetime.now(timezone.utc).strftime('%Y-%m-%d')}
"""
    return {
        "format": "text_file", "filename": "/llms.txt",
        "content": content,
        "deployment_instruction": "Upload to root of your site as llms.txt so AI platforms like ChatGPT can find factual info about your business",
    }


def fix_sitemap_xml(ctx: dict) -> dict:
    url = ctx['url']
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    urls_xml = "\n".join([
        f"  <url><loc>{url}/</loc><lastmod>{today}</lastmod><priority>1.0</priority></url>",
        f"  <url><loc>{url}/about</loc><priority>0.8</priority></url>",
        f"  <url><loc>{url}/services</loc><priority>0.9</priority></url>",
        f"  <url><loc>{url}/contact</loc><priority>0.7</priority></url>",
    ])
    content = f"""<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
{urls_xml}
</urlset>
"""
    return {
        "format": "xml_file", "filename": "/sitemap.xml",
        "content": content,
        "deployment_instruction": "Upload as sitemap.xml at site root. Then submit to Google Search Console + Bing Webmaster Tools.",
    }


def fix_og_tags(ctx: dict) -> dict:
    content = f"""<!-- Open Graph tags — paste inside <head> -->
<meta property="og:type" content="website" />
<meta property="og:site_name" content="{ctx['name']}" />
<meta property="og:url" content="{ctx['url']}" />
<meta property="og:title" content="{ctx['name']}" />
<meta property="og:description" content="{ctx['description']}" />
<meta property="og:image" content="{ctx['url']}/og-image.png" />
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="630" />
<meta property="og:locale" content="en_{ctx['country']}" />"""
    return {
        "format": "html_snippet", "filename": "<head>",
        "content": content,
        "deployment_instruction": "Paste this block inside the <head> section of your home page (index.html, or your site's main layout template).",
    }


def fix_twitter_tags(ctx: dict) -> dict:
    content = f"""<!-- Twitter Card tags — paste inside <head> -->
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="{ctx['name']}" />
<meta name="twitter:description" content="{ctx['description']}" />
<meta name="twitter:image" content="{ctx['url']}/og-image.png" />"""
    return {
        "format": "html_snippet", "filename": "<head>",
        "content": content,
        "deployment_instruction": "Paste this inside your <head> section to enable rich link previews when shared on Twitter/X.",
    }


def fix_schema_org(ctx: dict) -> dict:
    """Generates Organization + LocalBusiness + FAQPage schema."""
    schema = f"""<!-- Schema.org structured data — paste inside <head> -->
<script type="application/ld+json">
{{
  "@context": "https://schema.org",
  "@graph": [
    {{
      "@type": "Organization",
      "@id": "{ctx['url']}/#org",
      "name": "{ctx['name']}",
      "url": "{ctx['url']}",
      "description": "{ctx['description']}",
      "email": "{ctx['email']}",
      {f'"telephone": "{ctx["phone"]}",' if ctx['phone'] else ''}
      {f'"logo": "{ctx["logo_url"]}",' if ctx['logo_url'] else ''}
      "address": {{
        "@type": "PostalAddress",
        "addressRegion": "{ctx['region']}",
        "addressCountry": "{ctx['country']}"
      }}
    }},
    {{
      "@type": "WebSite",
      "@id": "{ctx['url']}/#website",
      "url": "{ctx['url']}",
      "name": "{ctx['name']}",
      "publisher": {{ "@id": "{ctx['url']}/#org" }}
    }}
  ]
}}
</script>"""
    return {
        "format": "html_snippet", "filename": "<head>",
        "content": schema,
        "deployment_instruction": "Paste inside <head>. This gives Google + AI platforms structured facts about your business (can enable rich snippets, star ratings, sitelinks).",
    }


def fix_canonical(ctx: dict) -> dict:
    return {
        "format": "html_snippet", "filename": "<head>",
        "content": f'<link rel="canonical" href="{ctx["url"]}" />',
        "deployment_instruction": "Add this canonical link to your <head>. Prevents duplicate-content penalties and tells search engines the primary URL.",
    }


def fix_meta_description(ctx: dict) -> dict:
    return {
        "format": "html_snippet", "filename": "<head>",
        "content": f'<meta name="description" content="{ctx["description"][:155]}" />',
        "deployment_instruction": "Add this inside <head>. Required for Google search results snippet.",
    }


def fix_viewport(ctx: dict) -> dict:
    return {
        "format": "html_snippet", "filename": "<head>",
        "content": '<meta name="viewport" content="width=device-width, initial-scale=1.0" />',
        "deployment_instruction": "Critical for mobile rendering. Paste inside <head>.",
    }


# Issue-code → fix-function mapping
FIX_REGISTRY = {
    "missing_title": lambda ctx: {"format": "html_snippet", "filename": "<head>",
        "content": f'<title>{ctx["name"]}</title>',
        "deployment_instruction": "Add this at the top of your <head>."},
    "missing_description": fix_meta_description,
    "og_incomplete": fix_og_tags,
    "twitter_incomplete": fix_twitter_tags,
    "no_canonical": fix_canonical,
    "no_schema_org": fix_schema_org,
    "weak_schema": fix_schema_org,
    "no_viewport": fix_viewport,
    "no_robots": fix_robots_txt,
    "robots_no_ai_bots": fix_robots_txt,
    "robots_partial_ai": fix_robots_txt,
    "no_llms_txt": fix_llms_txt,
    "no_llms_full": lambda ctx: fix_llms_txt(ctx),
    "no_sitemap": fix_sitemap_xml,
    "sitemap_no_priority": fix_sitemap_xml,
}


def generate_fixes(audit_report: dict, business_info: Optional[dict] = None) -> list:
    """
    Given an audit v2 report, generate ready-to-deploy fixes for each issue.
    Returns list of fix objects.
    """
    ctx = _business_context(business_info or {"url": audit_report.get("site_url")})
    fixes = []
    seen_codes = set()  # dedupe
    for issue in audit_report.get("issues", []):
        code = issue["code"]
        if code in seen_codes:
            continue
        seen_codes.add(code)
        fix_fn = FIX_REGISTRY.get(code)
        if not fix_fn:
            continue
        try:
            fix = fix_fn(ctx)
            fix["code"] = code
            fix["severity"] = issue["severity"]
            fix["issue"] = issue["message"]
            fixes.append(fix)
        except Exception as e:
            fixes.append({
                "code": code, "severity": issue["severity"],
                "issue": issue["message"],
                "error": str(e),
            })
    return fixes
