"""
services/social_autopilot.py — iter 330 FIX 6

Daily LinkedIn post via Brightbean (self-hosted) about Canadian SMB
lead generation. Topics rotate to keep the feed fresh:

  Mon  — Success story  (anonymised customer outcome)
  Tue  — Practical tip  (CASL-compliant outreach mechanics)
  Wed  — Market insight (regional SMB trends)
  Thu  — AUREM feature  (something the product does)
  Fri  — Founder voice  (short opinion / industry take)
  Sat  — Skipped (low engagement day)
  Sun  — Skipped (low engagement day)

The content is generated by the existing tiered LLM (emergent universal
key). Each post is persisted to `social_autopilot_posts` for audit.
Founder sees one line in the Morning Brief: "Posted to LinkedIn:
<title> (https://…)".
"""
from __future__ import annotations

import logging
import os
from datetime import datetime, timedelta, timezone

logger = logging.getLogger(__name__)

BRIGHTBEAN_URL = os.environ.get("BRIGHTBEAN_URL", "")
BRIGHTBEAN_API_KEY = os.environ.get("BRIGHTBEAN_API_KEY", "")

TOPIC_ROTATION = {
    0: "success_story",     # Monday
    1: "practical_tip",
    2: "market_insight",
    3: "aurem_feature",
    4: "founder_voice",
    5: None,                 # Saturday skip
    6: None,                 # Sunday skip
}

_TOPIC_PROMPTS: dict[str, str] = {
    "success_story": (
        "Write a 100-130 word LinkedIn post anonymising a Canadian "
        "small-business success story. Focus on a measurable outcome "
        "(new leads / new revenue / time saved). End with a one-line "
        "CTA about AUREM at aurem.live. No emojis except a single 🇨🇦."
    ),
    "practical_tip": (
        "Write a 100-130 word LinkedIn post giving Canadian small-"
        "business owners ONE concrete CASL-compliant outreach tip "
        "they can apply this week. Plain English, no fluff."
    ),
    "market_insight": (
        "Write a 100-130 word LinkedIn post sharing one insight about "
        "the current state of small-business lead-generation in "
        "Canada (ON / BC / AB / QC). Cite no fake numbers."
    ),
    "aurem_feature": (
        "Write a 100-130 word LinkedIn post about ONE thing AUREM "
        "(autonomous outreach platform) does for Canadian SMBs. "
        "Pick one — 4-channel blast, AI website preview, AI phone "
        "calls, CASL hard-stop, morning brief. Plain English."
    ),
    "founder_voice": (
        "Write a 100-130 word LinkedIn post in a confident founder "
        "voice. Topic: the founder's view on why most cold-outreach "
        "fails for Canadian small businesses and what works instead. "
        "Honest, no jargon."
    ),
}


def _now() -> datetime:
    return datetime.now(timezone.utc)


async def _toronto_now():
    """Return datetime in America/Toronto (handles DST)."""
    try:
        import pytz
        return datetime.now(pytz.timezone("America/Toronto"))
    except Exception:
        return datetime.utcnow()


async def _generate_post_text(topic_key: str) -> dict:
    """Call the emergent universal-key LLM (Claude Haiku 4.5 tier).

    Falls back to a deterministic skeleton if the LLM call fails so the
    cron never crashes — we'd rather post a generic version than skip.
    """
    prompt = _TOPIC_PROMPTS.get(topic_key, _TOPIC_PROMPTS["practical_tip"])
    try:
        from emergentintegrations.llm.chat import LlmChat, UserMessage
        chat = LlmChat(
            api_key=os.environ["EMERGENT_LLM_KEY"],
            session_id=f"social_autopilot_{topic_key}_{_now().strftime('%Y%m%d')}",
            system_message=(
                "You are AUREM's social voice. Plain Canadian English. "
                "No corporate jargon. No emojis except a single 🇨🇦. "
                "Strict 100-130 word window."
            ),
        ).with_model("anthropic", "claude-haiku-4-5")
        msg = UserMessage(text=prompt)
        text = await chat.send_message(msg)
        text = (text or "").strip()
        if not text:
            raise RuntimeError("empty LLM response")
        return {"ok": True, "text": text}
    except Exception as e:
        logger.warning(f"[social-autopilot] LLM failed for {topic_key}: {e}")
        # Deterministic fallback so the post still ships.
        return {"ok": True, "fallback": True, "text": (
            "Small wins, every week.\n\n"
            "Canadian small businesses don't need flashy growth hacks. "
            "They need a steady stream of qualified, CASL-compliant "
            "leads landing in their inbox. AUREM scouts your local "
            "market every morning, drafts a personalised website "
            "preview for each prospect, and runs a 4-channel cadence "
            "you don't have to babysit.\n\n"
            "See it: https://aurem.live · 🇨🇦"
        )}


async def _publish_via_brightbean(text: str, topic_key: str) -> dict:
    """POST to Brightbean's create endpoint. Returns {ok, post_id, url}."""
    if not BRIGHTBEAN_URL:
        return {"ok": False, "error": "BRIGHTBEAN_URL not set"}
    try:
        import httpx
        async with httpx.AsyncClient(timeout=15.0) as c:
            r = await c.post(
                f"{BRIGHTBEAN_URL.rstrip('/')}/api/posts/create/",
                headers={
                    "Authorization": f"Bearer {BRIGHTBEAN_API_KEY}" if BRIGHTBEAN_API_KEY else "",
                    "Content-Type":  "application/json",
                },
                json={
                    "platform":  "linkedin",
                    "content":   text,
                    "topic_key": topic_key,
                    "source":    "aurem_autopilot",
                },
            )
        if r.status_code in (200, 201):
            d = r.json() if r.headers.get("content-type", "").startswith("application/json") else {}
            return {"ok": True, "post_id": d.get("id"), "url": d.get("url")}
        return {"ok": False, "status": r.status_code, "body": r.text[:200]}
    except Exception as e:
        return {"ok": False, "error": str(e)[:200]}


async def run_daily_social_post(db) -> dict:
    """One-shot daily run. Wired to APScheduler at 10:00 America/Toronto."""
    if db is None:
        return {"ok": False, "error": "db unavailable"}
    tor_now = await _toronto_now()
    topic_key = TOPIC_ROTATION.get(tor_now.weekday())
    if not topic_key:
        return {"ok": True, "skipped": True, "reason": f"weekday={tor_now.weekday()} (weekend skip)"}

    # Idempotency — never double-post the same day.
    day_id = tor_now.strftime("%Y-%m-%d")
    existing = await db.social_autopilot_posts.find_one({"day_id": day_id})
    if existing:
        return {"ok": True, "skipped": True, "reason": "already posted today",
                "day_id": day_id, "topic": existing.get("topic_key")}

    gen = await _generate_post_text(topic_key)
    text = gen["text"]
    pub = await _publish_via_brightbean(text, topic_key)

    doc = {
        "day_id":      day_id,
        "ts":          _now(),
        "topic_key":   topic_key,
        "text":        text,
        "llm_ok":      not gen.get("fallback"),
        "publish_ok":  bool(pub.get("ok")),
        "publish":     pub,
    }
    try:
        await db.social_autopilot_posts.insert_one(doc)
    except Exception as e:
        logger.warning(f"[social-autopilot] persist failed: {e}")

    return {
        "ok":         True,
        "day_id":     day_id,
        "topic":      topic_key,
        "publish_ok": bool(pub.get("ok")),
        "text_chars": len(text),
        "publish":    pub,
    }


async def latest_social_post_line(db) -> dict:
    """Used by the Morning Brief for the "Posted to LinkedIn:" line."""
    if db is None:
        return {"line": ""}
    cutoff = _now() - timedelta(hours=30)
    row = await db.social_autopilot_posts.find_one(
        {"ts": {"$gte": cutoff}, "publish_ok": True},
        sort=[("ts", -1)],
    )
    if not row:
        return {"line": ""}
    url = ((row.get("publish") or {}).get("url") or "")
    snippet = (row.get("text") or "").split("\n", 1)[0][:80]
    if url:
        return {"line": f"Posted to LinkedIn: \"{snippet}\" ({url})"}
    return {"line": f"Posted to LinkedIn: \"{snippet}\""}
