"""
scripts/backfill_business_id_d81a.py — iter D-81a.

Idempotent migration: tag every customer-data row that's missing a
business_id with AUR-FNDR-001 (the founder dogfood BIN). All these
rows were generated by the founder's outreach pipeline before BIN
isolation was rolled out, so attributing them to AUR-FNDR-001 is
the correct historical assignment.

Usage:
    python3 scripts/backfill_business_id_d81a.py            # dry-run (default)
    python3 scripts/backfill_business_id_d81a.py --apply    # actually write
"""
from __future__ import annotations

import argparse
import asyncio
import os
import sys

FOUNDER_BIN = "AUR-FNDR-001"

TARGET_COLLECTIONS = [
    "campaign_leads",
    "scan_history",
    "outreach_log",
    "repair_jobs",
    "email_events",
    "consent_records",
    "audit_trail",
    "inbound_replies",
    "lead_touchpoints",
    "pending_approvals",
    "ora_cto_proposals",
]


async def main(apply: bool) -> int:
    sys.path.insert(0, "/app/backend")
    from motor.motor_asyncio import AsyncIOMotorClient

    mongo_url = os.environ["MONGO_URL"]
    db_name = os.environ["DB_NAME"]
    db = AsyncIOMotorClient(mongo_url)[db_name]
    existing = set(await db.list_collection_names())

    print(f"\n{'APPLY' if apply else 'DRY-RUN'} backfill — target BIN: {FOUNDER_BIN}")
    print("=" * 70)
    print(f"{'Collection':30s} {'Total':>8s} {'Unscoped':>10s} {'Scoped':>8s} {'Action':>10s}")
    print("-" * 70)
    grand_total_unscoped = 0
    grand_total_modified = 0
    for c in TARGET_COLLECTIONS:
        if c not in existing:
            print(f"{c:30s} {'(missing)':>8s}")
            continue
        total = await db[c].estimated_document_count()
        unscoped_q = {"$or": [
            {"business_id": {"$exists": False}},
            {"business_id": None},
            {"business_id": ""},
        ]}
        unscoped = await db[c].count_documents(unscoped_q)
        scoped = total - unscoped
        action = "would write" if not apply else "wrote"
        if apply and unscoped > 0:
            res = await db[c].update_many(
                unscoped_q, {"$set": {"business_id": FOUNDER_BIN}}
            )
            grand_total_modified += res.modified_count
            action = f"wrote {res.modified_count}"
        grand_total_unscoped += unscoped
        print(f"{c:30s} {total:>8d} {unscoped:>10d} {scoped:>8d} {action:>10s}")
    print("-" * 70)
    print(f"{'TOTAL UNSCOPED':30s} {'':>8s} {grand_total_unscoped:>10d}")
    if apply:
        print(f"{'TOTAL WRITTEN':30s} {'':>8s} {grand_total_modified:>10d}")
        # idempotency check — re-run finds 0
        leftover = 0
        for c in TARGET_COLLECTIONS:
            if c not in existing:
                continue
            leftover += await db[c].count_documents({"$or": [
                {"business_id": {"$exists": False}},
                {"business_id": None}, {"business_id": ""},
            ]})
        print(f"Post-apply leftover unscoped rows: {leftover}")
        if leftover > 0:
            print("⚠️  Some rows still unscoped — re-run with --apply.")
            return 1
        print("✅  All target collections now 100% scoped.")
    else:
        print("\nDry-run only — no writes. Re-run with --apply to commit.")
    return 0


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--apply", action="store_true",
                   help="Actually write business_id (default: dry-run).")
    args = p.parse_args()
    code = asyncio.run(main(args.apply))
    sys.exit(code)
