"""
scripts/wire_all_set_db.py — iter D-75 #4

Eliminates the 193-module set_db backlog in one shot.

Statically scans `/app/backend/routers/*.py` for any module that defines
`def set_db(`, generates an explicit wire-list, and writes it to
`/app/backend/routers/_set_db_wire_list.py`. `registry.py`'s
`_wire_top_unwired_set_db_modules` imports + extends `TOP_20_UNWIRED`
with everything in the generated list so every router with a `set_db`
gets the DB handle on boot.

After this runs:
  • 0 unwired modules (down from 193)
  • Founder can flip `AUREM_STRICT_SETDB_WIRING=true` in .env →
    boot-time detector raises RuntimeError on any future unwired
    module instead of silent 503s
  • Idempotent: re-running regenerates the list cleanly

Run:
    python3 /app/backend/scripts/wire_all_set_db.py [--dry-run]

Exit codes:
  0  = generated successfully
  1  = no modules found (something is wrong)
  2  = at least one module fails to import (named in stderr)
"""
from __future__ import annotations

import argparse
import importlib
import os
import re
import sys
from datetime import datetime

ROUTERS_DIR = "/app/backend/routers"
OUT_FILE = os.path.join(ROUTERS_DIR, "_set_db_wire_list.py")


def scan_modules_with_set_db() -> list[str]:
    """Return alphabetized list of router module names (without `.py`)
    that contain a `def set_db(` definition."""
    names: list[str] = []
    for fn in sorted(os.listdir(ROUTERS_DIR)):
        if not fn.endswith(".py") or fn.startswith("_") or fn == "registry.py":
            continue
        path = os.path.join(ROUTERS_DIR, fn)
        try:
            src = open(path).read()
        except Exception:
            continue
        if re.search(r"^\s*def\s+set_db\s*\(", src, re.M):
            names.append(fn[:-3])
    return names


def verify_imports(names: list[str]) -> list[tuple[str, str]]:
    """Try importing each one — flag any that crash so the user knows
    BEFORE registry.py tries to wire them at boot."""
    sys.path.insert(0, "/app/backend")
    broken: list[tuple[str, str]] = []
    for name in names:
        try:
            mod = importlib.import_module(f"routers.{name}")
            if not hasattr(mod, "set_db"):
                broken.append((name, "imported but has no set_db attribute"))
        except Exception as e:
            broken.append((name, f"{type(e).__name__}: {str(e)[:160]}"))
    return broken


def render_wire_list(names: list[str], broken: set[str]) -> str:
    """Render the generated module — a single literal list."""
    safe = [n for n in names if n not in broken]
    lines = [
        '"""',
        f"_set_db_wire_list.py — AUTO-GENERATED by",
        f"scripts/wire_all_set_db.py on {datetime.utcnow().isoformat()}Z.",
        "",
        f"{len(safe)} router modules verified to define `set_db(db)`.",
        f"{len(broken)} modules excluded (broken imports — see stderr of",
        f"the generator run).",
        "",
        "Do NOT edit by hand — re-run the generator if the list needs to",
        "change. The generator is idempotent.",
        '"""',
        "",
        "ALL_SET_DB_MODULES = [",
    ]
    for n in safe:
        lines.append(f'    "{n}",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--dry-run", action="store_true",
                   help="Print what would be written; don't touch the file")
    args = p.parse_args()

    names = scan_modules_with_set_db()
    if not names:
        print("ERROR: no router modules define set_db()", file=sys.stderr)
        return 1
    print(f"Scanned routers/ → {len(names)} modules define set_db()")

    print("Verifying imports…")
    broken = verify_imports(names)
    if broken:
        print(f"  {len(broken)} broken — excluded from wire-list:", file=sys.stderr)
        for name, err in broken:
            print(f"    {name}: {err}", file=sys.stderr)

    rendered = render_wire_list(names, {n for n, _ in broken})
    safe_count = rendered.count('    "')

    if args.dry_run:
        print(f"\n--- DRY RUN — would write to {OUT_FILE} ({safe_count} modules) ---")
        print(rendered[:800] + ("\n  …(truncated)" if len(rendered) > 800 else ""))
        return 0

    # Atomic write
    tmp = OUT_FILE + ".tmp"
    with open(tmp, "w") as f:
        f.write(rendered)
    os.replace(tmp, OUT_FILE)
    print(f"\nWrote {OUT_FILE} ({safe_count} modules)")
    print()
    print("Next steps:")
    print("  1. Restart backend: sudo supervisorctl restart backend")
    print("  2. Verify: grep 'set_db wiring' /var/log/supervisor/backend.err.log")
    print("  3. When safe, set AUREM_STRICT_SETDB_WIRING=true in .env")
    return 2 if broken else 0


if __name__ == "__main__":
    sys.exit(main())
