"""
iter 326vv — Morning brief scheduler + delivery audit
======================================================

Two real gaps in the existing morning_brief stack:

1. The helper `services.morning_brief.morning_brief_scheduler()` was
   defined but NEVER started anywhere — no asyncio.create_task, no
   APScheduler job registration. Briefs were being generated by
   ad-hoc internal callers (124 docs in `morning_briefs` collection
   as of 2026-05-22) but the actual 07:00 ET cron never ran.

2. `deliver_brief()` had no audit trail. WhatsApp/email/push outcomes
   were logged to backend.err.log only, never persisted. The
   `founder_brief_sends` collection had ZERO documents even though
   124 briefs had been "delivered". This blocked the System Overview
   debugging dashboard from showing delivery health.

Fixes:
  - `routers/registry.py` now registers `_morning_brief_job` with
    APScheduler — daily 07:00 America/Toronto, 15-min misfire grace.
  - `services/morning_brief.py::deliver_brief` now persists each
    delivery attempt to `founder_brief_sends` with per-channel
    `ok`/`error` outcome + the brief_id for audit.
"""
from __future__ import annotations

from pathlib import Path

BACKEND = Path(__file__).resolve().parent.parent


# ─────────────────────────────────────────────
# Gap 1 — scheduler wire-up
# ─────────────────────────────────────────────

def test_morning_brief_cron_registered_in_registry():
    src = (BACKEND / "routers" / "registry.py").read_text()
    assert "aurem_morning_brief_daily" in src
    assert "_morning_brief_job" in src
    # 07:00 America/Toronto
    assert 'timezone="America/Toronto"' in src
    assert "hour=7, minute=0" in src
    assert "from services.morning_brief import run_morning_brief" in src


def test_morning_brief_cron_uses_apscheduler():
    """Belt-and-braces: confirm the job is added via aurem_scheduler.add_job."""
    src = (BACKEND / "routers" / "registry.py").read_text()
    # Find the morning brief block
    idx = src.index("aurem_morning_brief_daily")
    block = src[max(0, idx - 400): idx + 400]
    assert "aurem_scheduler.add_job(" in block
    assert "replace_existing=True" in block


def test_morning_brief_cron_logs_outcome():
    """Watchdog signal: every cron run logs delivered/channels so we can
    grep the backend log for failed runs."""
    src = (BACKEND / "routers" / "registry.py").read_text()
    assert "[morning-brief]" in src
    assert "delivered=" in src
    assert "channels=" in src


# ─────────────────────────────────────────────
# Gap 2 — delivery audit trail in founder_brief_sends
# ─────────────────────────────────────────────

def test_deliver_brief_persists_outcome():
    src = (BACKEND / "services" / "morning_brief.py").read_text()
    # Audit row insert
    assert "founder_brief_sends.insert_one(" in src
    # Outcome dict has the right shape
    for f in ('"brief_id":', '"tenant_id":', '"channels":', '"results":',
              '"delivered":', '"ts":'):
        assert f in src, f"delivery_outcome missing key: {f}"


def test_deliver_brief_records_whatsapp_outcome():
    src = (BACKEND / "services" / "morning_brief.py").read_text()
    # Per-channel ok/error/reason
    assert '"ok": True, "to": wa_to' in src
    assert '"reason": "no_phone"' in src
    assert '"error": str(e)[:200]' in src


def test_deliver_brief_audit_is_best_effort_not_blocking():
    """If the audit write fails, brief delivery must still succeed."""
    src = (BACKEND / "services" / "morning_brief.py").read_text()
    # The insert is wrapped in try/except that only logs, never raises
    idx = src.index("founder_brief_sends.insert_one(")
    block = src[max(0, idx - 200): idx + 400]
    assert "try:" in block
    assert "except Exception" in block
    assert "audit log skipped" in block


# ─────────────────────────────────────────────
# Iter marker
# ─────────────────────────────────────────────

def test_iter_326vv_marker_present():
    src = (BACKEND / "routers" / "registry.py").read_text()
    assert "326vv" in src
    src2 = (BACKEND / "services" / "morning_brief.py").read_text()
    assert "326vv" in src2
