import { useState, useEffect, useRef, createContext, useContext } from "react";
import axios from "axios";
import { API } from "@/utils/api";
import { useAdminBrand } from "./useAdminBrand";

// Theme context for sub-components
const ExecThemeContext = createContext(null);
const useExecTheme = () => useContext(ExecThemeContext);

const MODULES = [
  { id: "briefing", label: "CEO Briefing", icon: "◈" },
  { id: "market", label: "Market Intel", icon: "◉" },
  { id: "customer", label: "Customer Intel", icon: "◎" },
  { id: "brand", label: "Brand Health", icon: "◍" },
  { id: "strategy", label: "Strategy Engine", icon: "◆" },
];

// Dynamic theme colors based on brand
const getThemeColors = (isLaVela) => isLaVela ? {
  bg: "#0D4D4D",
  bgDark: "#0A3C3C",
  surface: "#1A6B6B",
  surfaceAlt: "#1A6B6B40",
  border: "#D4A57440",
  borderLight: "#D4A57430",
  gold: "#D4A574",
  goldDim: "#E6BE8A",
  accent: "#D4A574",
  accentHover: "#E6BE8A",
  green: "#72B08A",
  text: "#FDF8F5",
  textDim: "#D4A574",
  textMuted: "#E8C4B8",
} : {
  bg: "#0a0c10",
  bgDark: "#080a0e",
  surface: "#0e1018",
  surfaceAlt: "#0c0e14",
  border: "rgb(31, 41, 55)",
  borderLight: "rgb(55, 65, 81)",
  gold: "#F8A5B8",
  goldDim: "#E8889A",
  accent: "#d97706", // amber-600
  accentHover: "#f59e0b", // amber-500
  green: "#15803d",
  text: "#e5e7eb",
  textDim: "#6b7280",
  textMuted: "#4b5563",
};

const SAMPLE_DATA = {
  sales: { weekly: "$14,280", growth: "+22%", topSKU: "PDRN Repair Serum 30ml", repurchaseRate: "64%" },
  reviews: [
    "The PDRN serum genuinely changed my skin texture after 3 weeks",
    "Wish there was a stronger concentration option",
    "Packaging feels very premium, love the brand story",
    "The product quality is exceptional",
    "My aesthetician recommended this and I'm a convert"
  ],
  competitors: ["Medik8 launched polynucleotide eye cream in CA", "Korean brand MEDI-PEEL expanding to Shopify CA", "Augustinus Bader now at Sephora Canada"],
  seo: { topKeyword: "PDRN Canada", position: 4, trend: "↑", monthlySearches: "1,200" },
};

// Sub-component: Module sidebar item
function ModuleItem({ module, isActive, onClick }) {
  const C = useExecTheme();
  return (
    <div
      className="px-5 py-3 cursor-pointer flex items-center gap-3 text-xs tracking-wide transition-all"
      style={{
        color: isActive ? C.gold : C.textMuted,
        backgroundColor: isActive ? `${C.gold}08` : 'transparent',
        borderRight: `2px solid ${isActive ? C.gold : 'transparent'}`
      }}
      onClick={onClick}
    >
      <span className="text-base">{module.icon}</span>
      {module.label}
    </div>
  );
}

// Sub-component: Metric card
function MetricCard({ label, value, sub }) {
  const C = useExecTheme();
  return (
    <div style={{ backgroundColor: C.surface, padding: '1rem 1.5rem' }}>
      <div className="text-[10px] tracking-widest uppercase mb-1" style={{ color: C.textMuted }}>{label}</div>
      <div className="text-xl" style={{ color: C.gold }}>{value}</div>
      <div className="text-xs mt-1" style={{ color: C.green }}>{sub}</div>
    </div>
  );
}

// Sub-component: Quick Metrics sidebar
function QuickMetrics({ metrics }) {
  const C = useExecTheme();
  return (
    <div className="mt-auto px-5 pt-5" style={{ borderTop: `1px solid ${C.border}` }}>
      <div className="text-[10px] tracking-widest mb-3 uppercase" style={{ color: C.textMuted }}>Quick Metrics</div>
      <div className="text-xs space-y-2" style={{ color: C.textMuted }}>
        <div className="flex justify-between">Revenue <span style={{ color: C.gold }}>{metrics.sales.weekly}</span></div>
        <div className="flex justify-between">Growth <span style={{ color: C.green }}>{metrics.sales.growth}</span></div>
        <div className="flex justify-between">Repurchase <span style={{ color: C.gold }}>{metrics.sales.repurchaseRate}</span></div>
        <div className="flex justify-between">SEO Rank <span style={{ color: C.gold }}>#{metrics.seo.position}</span></div>
      </div>
    </div>
  );
}

export default function ExecutiveIntelligence() {
  const { isLaVela, shortName, name: brandName } = useAdminBrand();
  const C = getThemeColors(isLaVela);
  
  const [activeModule, setActiveModule] = useState("briefing");
  const [inputData, setInputData] = useState("");
  const [aiResponse, setAiResponse] = useState("");
  const [loading, setLoading] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [metrics, setMetrics] = useState(SAMPLE_DATA);
  const [realMetrics, setRealMetrics] = useState(null);
  const responseRef = useRef(null);
  const token = localStorage.getItem('reroots_token');

  // Fetch real metrics from backend
  useEffect(() => {
    const fetchRealMetrics = async () => {
      try {
        const activeBrand = localStorage.getItem('admin_active_brand') || 'reroots';
        const [ordersRes, reviewsRes] = await Promise.all([
          axios.get(`${API}/admin/analytics?days=7&brand=${activeBrand}`, { headers: { Authorization: `Bearer ${token}` } }),
          axios.get(`${API}/reviews/recent?limit=5&brand=${activeBrand}`, { headers: { Authorization: `Bearer ${token}` } })
        ]);
        
        if (ordersRes.data) {
          setRealMetrics({
            sales: {
              weekly: `$${ordersRes.data.total_revenue?.toLocaleString() || '0'}`,
              growth: ordersRes.data.growth || '+0%',
              topSKU: ordersRes.data.top_product || 'PDRN Repair Serum',
              repurchaseRate: ordersRes.data.repurchase_rate || '64%'
            },
            reviews: reviewsRes.data?.map(r => r.content) || SAMPLE_DATA.reviews,
            competitors: SAMPLE_DATA.competitors,
            seo: SAMPLE_DATA.seo
          });
        }
      } catch (err) {
        console.log('Using sample metrics');
      }
    };
    fetchRealMetrics();
  }, [token, isLaVela]);

  useEffect(() => {
    if (!autoGenerated) {
      generateBriefing();
      setAutoGenerated(true);
    }
  }, []);

  useEffect(() => {
    if (responseRef.current) {
      responseRef.current.scrollTop = responseRef.current.scrollHeight;
    }
  }, [aiResponse]);

  const currentMetrics = realMetrics || metrics;

  const generateBriefing = async () => {
    setLoading(true);
    setAiResponse("");
    
    const prompt = `Generate a concise Executive CEO Briefing for ${brandName} brand this week based on this data:

SALES: Weekly Revenue ${currentMetrics.sales.weekly} (${currentMetrics.sales.growth} WoW), Top SKU: ${currentMetrics.sales.topSKU}, Repurchase Rate: ${currentMetrics.sales.repurchaseRate}

CUSTOMER VOICE (recent reviews):
${currentMetrics.reviews.map((r, i) => `${i + 1}. "${r}"`).join("\n")}

COMPETITOR ALERTS:
${currentMetrics.competitors.map((c, i) => `${i + 1}. ${c}`).join("\n")}

SEO: Ranking #${currentMetrics.seo.position} for "${currentMetrics.seo.topKeyword}" (${currentMetrics.seo.monthlySearches}/mo searches, trend: ${currentMetrics.seo.trend})

Format your response as:
## 🟢 WINS THIS WEEK
## ⚠️ WATCH LIST  
## 🎯 TOP 3 ACTIONS (this week)
## 💡 BRAND OPPORTUNITY

Be specific, actionable, and ${brandName}-brand-focused. Max 300 words.`;

    await callAI(prompt, "briefing");
  };

  const callAI = async (prompt, moduleType) => {
    try {
      const response = await axios.post(`${API}/admin/ai/executive-intel`, {
        prompt,
        module_type: moduleType
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      
      setAiResponse(response.data.response || "No response received.");
    } catch (err) {
      console.error('AI Error:', err);
      setAiResponse("⚠️ AI service temporarily unavailable. Please try again.");
    }
    setLoading(false);
  };

  const handleModuleQuery = async () => {
    if (!inputData.trim()) return;
    setLoading(true);
    setAiResponse("");

    const brandDescription = isLaVela 
      ? `${brandName} (Canadian teen luxury skincare brand)`
      : `${brandName} (Canadian biotech skincare brand specializing in PDRN)`;

    const modulePrompts = {
      market: `As Market Intelligence Analyst for ${brandDescription}, analyze this information and provide competitive insights, category trends, and market positioning recommendations:\n\n${inputData}`,
      customer: `As Customer Intelligence Analyst for ${brandName}, analyze this customer data/feedback and provide: key sentiment themes, persona insights, retention opportunities, and product feedback loops:\n\n${inputData}`,
      brand: `As Brand Health Analyst for ${brandName}, evaluate this brand data and provide: brand equity score assessment, perception gaps, differentiation strength vs competitors, and brand-building recommendations:\n\n${inputData}`,
      strategy: `As Chief Strategy Officer for ${brandName}, analyze this input and generate a strategic recommendation including: 30-day action plan, resource allocation, risk factors, and expected outcomes:\n\n${inputData}`,
    };

    await callAI(modulePrompts[activeModule] || modulePrompts.strategy, activeModule);
    setInputData("");
  };

  const formatResponse = (text) => {
    return text.split("\n").map((line, i) => {
      if (line.startsWith("## ")) return <h3 key={i} style={{ color: C.gold }} className="mt-5 mb-2 text-sm tracking-wide">{line.replace("## ", "")}</h3>;
      if (line.startsWith("**") && line.endsWith("**")) return <strong key={i} style={{ color: C.goldDim }} className="block">{line.replace(/\*\*/g, "")}</strong>;
      if (line.startsWith("- ") || line.match(/^\d\./)) return <div key={i} style={{ color: C.textMuted }} className="pl-4 mb-1 text-sm">{line}</div>;
      if (line.trim() === "") return <br key={i} />;
      return <p key={i} style={{ color: C.text }} className="mb-1 text-sm leading-relaxed">{line}</p>;
    });
  };

  const inputPlaceholders = {
    briefing: "Dashboard auto-generates. Click Refresh to regenerate...",
    market: "Paste competitor news, market data, or industry intel here...",
    customer: "Paste customer reviews, survey responses, or feedback here...",
    brand: "Paste brand metrics, social mentions, or perception data here...",
    strategy: "Describe a challenge, opportunity, or decision you need analyzed...",
  };

  return (
    <ExecThemeContext.Provider value={C}>
      <div 
        className="min-h-screen flex flex-col font-serif" 
        style={{ backgroundColor: C.bg, color: C.text }}
        data-testid="executive-intelligence"
      >
        {/* Header */}
        <div 
          className="px-6 py-4 flex items-center justify-between"
          style={{ 
            borderBottom: `1px solid ${C.border}`,
            background: isLaVela 
              ? 'linear-gradient(180deg, #0A3C3C 0%, transparent 100%)' 
              : 'linear-gradient(180deg, rgba(17, 24, 39, 0.5) 0%, transparent 100%)'
          }}
        >
          <div className="flex items-baseline gap-3">
            <span className="text-xl tracking-widest" style={{ color: C.gold }}>{shortName}</span>
            <span className="text-xs tracking-widest uppercase" style={{ color: C.textMuted }}>Executive Intelligence</span>
          </div>
          <div className="flex items-center gap-2 text-xs tracking-wide" style={{ color: C.green }}>
            <div 
              className="w-1.5 h-1.5 rounded-full animate-pulse"
              style={{ backgroundColor: C.green, boxShadow: `0 0 6px ${C.green}` }}
            />
            SYSTEM ACTIVE
          </div>
        </div>

        <div className="flex flex-1 overflow-hidden">
          {/* Sidebar */}
          <div 
            className="w-52 py-6 flex flex-col"
            style={{ borderRight: `1px solid ${C.border}` }}
          >
            <div className="text-[10px] tracking-widest px-5 mb-3 uppercase" style={{ color: C.textMuted }}>Intelligence Modules</div>
            {MODULES.map(m => (
              <ModuleItem 
                key={m.id}
                module={m}
                isActive={activeModule === m.id}
                onClick={() => { setActiveModule(m.id); setAiResponse(""); }}
              />
            ))}
            <QuickMetrics metrics={currentMetrics} />
          </div>

          {/* Main Content */}
          <div className="flex-1 flex flex-col overflow-hidden">
            {/* Metrics Bar */}
            <div className="grid grid-cols-4 gap-px" style={{ backgroundColor: C.border, borderBottom: `1px solid ${C.border}` }}>
              <MetricCard label="Weekly Revenue" value={currentMetrics.sales.weekly} sub={`${currentMetrics.sales.growth} vs last week`} />
              <MetricCard label="Top SKU" value="PDRN Serum" sub={currentMetrics.sales.topSKU} />
              <MetricCard label="Repurchase Rate" value={currentMetrics.sales.repurchaseRate} sub="28-day cycle" />
              <MetricCard label="PDRN Keyword" value={`#${currentMetrics.seo.position} CA`} sub={`${currentMetrics.seo.monthlySearches}/mo ${currentMetrics.seo.trend}`} />
            </div>

            {/* Response Area */}
            <div ref={responseRef} className="flex-1 p-8 overflow-auto">
              <div className="flex items-center justify-between mb-6">
                <span className="text-[10px] tracking-widest uppercase" style={{ color: C.textMuted }}>
                  {MODULES.find(m => m.id === activeModule)?.icon} {MODULES.find(m => m.id === activeModule)?.label}
                </span>
                {activeModule === "briefing" && (
                  <button 
                    className="text-[10px] tracking-widest px-4 py-2 transition-all disabled:opacity-50"
                    style={{ 
                      color: C.gold, 
                      border: `1px solid ${C.border}`,
                      ':hover': { borderColor: `${C.gold}50` }
                    }}
                    onClick={generateBriefing} 
                    disabled={loading}
                  >
                    {loading ? "Analyzing..." : "↻ Refresh Briefing"}
                  </button>
                )}
              </div>

              <div 
                className="p-6 min-h-[300px]"
                style={{ 
                  backgroundColor: C.surfaceAlt, 
                  border: `1px solid ${C.border}` 
                }}
              >
                {loading ? (
                  <div className="flex items-center gap-3 text-sm tracking-wide" style={{ color: C.textMuted }}>
                    <div className="flex gap-1">
                      {[0, 1, 2].map(i => (
                        <div 
                          key={i} 
                          className="w-1 h-1 rounded-full animate-pulse" 
                          style={{ backgroundColor: C.gold, animationDelay: `${i * 0.2}s` }}
                        />
                      ))}
                    </div>
                    <span>Intelligence engine processing...</span>
                  </div>
                ) : aiResponse ? (
                  <div>{formatResponse(aiResponse)}</div>
                ) : (
                  <div className="text-sm tracking-wide" style={{ color: C.textMuted }}>
                    {activeModule === "briefing" ? "Auto-generating CEO briefing..." : "Enter data below and submit for AI analysis →"}
                  </div>
                )}
              </div>
            </div>

            {/* Input Area */}
            {activeModule !== "briefing" && (
              <div 
                className="p-5 flex gap-4"
                style={{ borderTop: `1px solid ${C.border}`, backgroundColor: C.bg }}
              >
                <textarea
                  className="flex-1 px-4 py-3 text-sm font-serif outline-none resize-none"
                  style={{ 
                    backgroundColor: C.surface, 
                    border: `1px solid ${C.border}`,
                    color: C.text
                  }}
                  rows={3}
                  placeholder={inputPlaceholders[activeModule]}
                  value={inputData}
                  onChange={e => setInputData(e.target.value)}
                  onKeyDown={e => { if (e.key === "Enter" && e.metaKey) handleModuleQuery(); }}
                />
                <button 
                  className="px-8 text-xs tracking-widest uppercase font-serif transition-all"
                  style={{
                    backgroundColor: loading || !inputData.trim() ? C.border : C.accent,
                    color: loading || !inputData.trim() ? C.textMuted : C.bg,
                    cursor: loading || !inputData.trim() ? 'not-allowed' : 'pointer'
                  }}
                  onClick={handleModuleQuery} 
                  disabled={loading || !inputData.trim()}
                >
                  Analyze
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
    </ExecThemeContext.Provider>
  );
}
